# 📊 Aspectos básicos de los DataFrames con Pandas

Este notebook muestra cómo trabajar con DataFrames utilizando la biblioteca **Pandas** en Python. Aprenderás a:

- Cargar un archivo CSV.
- Visualizar registros.
- Consultar información básica del DataFrame.
- Conocer su estructura (filas, columnas, tipos de datos).

In [1]:
import pandas as pd

## 📥 Cargando datos desde un archivo CSV

Utilizamos `pd.read_csv()` para leer un archivo CSV y convertirlo automáticamente en un DataFrame, que es una estructura de datos tabular (como una hoja de cálculo).

In [2]:
estados = pd.read_csv("data/estados.csv")

## 👀 Explorando el contenido del DataFrame

Podemos visualizar el contenido completo del DataFrame (si no es muy grande) simplemente escribiendo su nombre.

In [3]:
# Mostrar el contenido del dataframe
estados

                  Estado Abreviatura Codigo
0                Alabama        Ala.     AL
1                 Alaska      Alaska     AK
2                Arizona       Ariz.     AZ
3               Arkansas        Ark.     AR
4             California      Calif.     CA
5               Colorado       Colo.     CO
6            Connecticut       Conn.     CT
7               Delaware        Del.     DE
8   District of Columbia        D.C.     DC
9                Florida        Fla.     FL
10               Georgia         Ga.     GA
11                Hawaii      Hawaii     HI
12                 Idaho       Idaho     ID
13              Illinois        Ill.     IL
14               Indiana        Ind.     IN
15                  Iowa        Iowa     IA
16                Kansas       Kans.     KS
17              Kentucky         Ky.     KY
18             Louisiana         La.     LA
19                 Maine       Maine     ME
20              Maryland         Md.     MD
21         Massachusetts       Mass.     MA
22              Michigan       Mich.     MI
23             Minnesota       Minn.     MN
24           Mississippi       Miss.     MS
25              Missouri         Mo.     MO
26               Montana       Mont.     MT
27              Nebraska       Nebr.     NE
28                Nevada        Nev.     NV
29         New Hampshire        N.H.     NH
30            New Jersey        N.J.     NJ
31            New Mexico        N.M.     NM
32              New York        N.Y.     NY
33        North Carolina        N.C.     NC
34          North Dakota        N.D.     ND
35                  Ohio        Ohio     OH
36              Oklahoma       Okla.     OK
37                Oregon        Ore.     OR
38          Pennsylvania         Pa.     PA
39          Rhode Island        R.I.     RI
40        South Carolina        S.C.     SC
41          South Dakota        S.D.     SD
42             Tennessee       Tenn.     TN
43                 Texas        Tex.     TX
44                  Utah        Utah     UT
45               Vermont         Vt.     VT
46              Virginia         Va.     VA
47            Washington       Wash.     WA
48         West Virginia       W.Va.     WV
49             Wisconsin        Wis.     WI
50               Wyoming        Wyo.     WY

## 🔍 Vistazos rápidos con `head()` y `tail()`

- `head(n)` muestra las primeras `n` filas del DataFrame.
- `tail(n)` muestra las últimas `n` filas.

Estas funciones son útiles para explorar cómo están estructurados los datos al inicio y al final.

### head() muestra los primeros 5 renglones

In [4]:
estados.head()

       Estado Abreviatura Codigo
0     Alabama        Ala.     AL
1      Alaska      Alaska     AK
2     Arizona       Ariz.     AZ
3    Arkansas        Ark.     AR
4  California      Calif.     CA

### head(12) muestra los primeros 12 renglones

In [5]:
estados.head(12)

                  Estado Abreviatura Codigo
0                Alabama        Ala.     AL
1                 Alaska      Alaska     AK
2                Arizona       Ariz.     AZ
3               Arkansas        Ark.     AR
4             California      Calif.     CA
5               Colorado       Colo.     CO
6            Connecticut       Conn.     CT
7               Delaware        Del.     DE
8   District of Columbia        D.C.     DC
9                Florida        Fla.     FL
10               Georgia         Ga.     GA
11                Hawaii      Hawaii     HI

### tail() muestra los últimos 5 renglones

In [6]:
estados.tail()

           Estado Abreviatura Codigo
46       Virginia         Va.     VA
47     Washington       Wash.     WA
48  West Virginia       W.Va.     WV
49      Wisconsin        Wis.     WI
50        Wyoming        Wyo.     WY

### tail(9) muestra los últimos 9 renglones

In [7]:
estados.tail(9)

           Estado Abreviatura Codigo
42      Tennessee       Tenn.     TN
43          Texas        Tex.     TX
44           Utah        Utah     UT
45        Vermont         Vt.     VT
46       Virginia         Va.     VA
47     Washington       Wash.     WA
48  West Virginia       W.Va.     WV
49      Wisconsin        Wis.     WI
50        Wyoming        Wyo.     WY

### Mostrar el nombre de las columnas

## 🏷️ Nombres de las columnas

Los nombres de las columnas se almacenan como un objeto tipo `Index`. Esto permite ver fácilmente qué atributos contiene cada registro.

In [8]:
estados.columns

Index(['Estado', 'Abreviatura', 'Codigo'], dtype='object')

### Mostrando información del Dataframe

## 🧠 Inspección general del DataFrame con `info()`

El método `estados.info()` nos da un resumen muy útil del DataFrame. Muestra:

- El número total de entradas (filas).
- El nombre y tipo de cada columna.
- Cuántos valores **no nulos** hay por columna.
- La **cantidad total de memoria** usada.

Esto es útil para:
- Detectar columnas con valores faltantes (null).
- Entender qué tipo de datos contiene cada columna.
- Comprobar si es necesario transformar datos (por ejemplo, cambiar de `object` a `int` o `datetime`).

In [9]:
estados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Estado       51 non-null     object
 1   Abreviatura  51 non-null     object
 2   Codigo       51 non-null     object
dtypes: object(3)
memory usage: 1.3+ KB

## 🧾 Tipos de datos de cada columna con `dtypes`

El atributo `estados.dtypes` nos muestra qué tipo de dato tiene cada columna del DataFrame. Los tipos más comunes en Pandas son:

- `object`: Texto (cadenas de caracteres).
- `int64`: Números enteros.
- `float64`: Números decimales.
- `bool`: Valores lógicos (True/False).
- `datetime64`: Fechas y horas.

🔎 **¿Para qué sirve esto?**
Conocer los tipos de datos es útil para:

- Saber si necesitas convertir algún dato (por ejemplo, texto a fecha).
- Aplicar funciones adecuadas según el tipo (por ejemplo, operaciones matemáticas en `int` o `float`).
- Identificar posibles errores en la carga de datos (como fechas que se cargaron como `object`).

### Mostrando los tipos de datos que guarda cada columna

In [10]:
estados.dtypes

Estado         object
Abreviatura    object
Codigo         object
dtype: object

## 🧾 Tamaño y estructura del DataFrame

- `type(estados)`: Muestra el tipo de objeto (debe ser `<class 'pandas.core.frame.DataFrame'>`).
- `len(estados)`: Cantidad de filas (registros).
- `estados.shape`: Una tupla con el número de filas y columnas.
- `estados.size`: Número total de elementos (filas × columnas).

In [11]:
type(estados)

pandas.core.frame.DataFrame

### Mostrando la cantidad de registros

In [12]:
len(estados)

51

### Mostrando la cantidad de registros y columnas

In [13]:
estados.shape

(51, 3)

### Mostrando la cantidad de casillas de todo el DataFrame

In [14]:
estados.size

153

## 🎯 Conclusión

Ya sabes cómo cargar, visualizar y explorar las propiedades básicas de un DataFrame. Estos pasos son esenciales antes de aplicar filtros, limpiar datos o crear visualizaciones.

Próximos pasos sugeridos:
- Filtrar registros por condiciones.
- Trabajar con columnas específicas.
- Detectar y tratar valores nulos.
- Crear gráficos con `matplotlib` o `seaborn`.