# Sobrevivientes del Titanic (2)
## `read_csv` con separadores sin coma

Cuando un archivo CSV usa un separador diferente a la coma, como una barra vertical (`|`), al cargarlo sin especificar el separador, Pandas interpreta todo como una sola columna.

Para que Pandas lea correctamente cada columna, debemos indicar explícitamente el separador usando el parámetro `sep`.

In [1]:
import pandas as pd

Primero, veamos qué pasa si cargamos el archivo sin especificar el separador:

In [2]:
titanic = pd.read_csv("data/titanic_v4.csv")
titanic

                                    pclass|survived|name|sex|age
1|1|Allen                       Miss. Elisabeth Walton|female|29
1|1|Allison                    Master. Hudson Trevor|male|0.9167
1|0|Allison                         Miss. Helen Loraine|female|2
1|0|Allison                  Mr. Hudson Joshua Creighton|male|30
1|0|Allison     Mrs. Hudson J C (Bessie Waldo Daniels)|female|25
...                                                          ...
3|0|Zabour                              Miss. Hileni|female|14.5
3|0|Zabour                                Miss. Thamine|female|?
3|0|Zakarian                           Mr. Mapriededer|male|26.5
3|0|Zakarian                                   Mr. Ortin|male|27
3|0|Zimmerman                                    Mr. Leo|male|29

[1309 rows x 1 columns]

Como podemos ver, todo queda en una sola columna porque el archivo está separado por `|`.

Ahora, le indicamos a Pandas que use `|` como separador para leer correctamente las columnas:

In [3]:
titanic = pd.read_csv("data/titanic_v4.csv", sep="|")
titanic

,pclass,survived,name,sex,age
0,1,1,"Allen, Miss. Elisabeth Walton",female,29
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167
2,1,0,"Allison, Miss. Helen Loraine",female,2
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25
...,...,...,...,...,...
1304,3,0,"Zabour, Miss. Hileni",female,14.5
1305,3,0,"Zabour, Miss. Thamine",female,?
1306,3,0,"Zakarian, Mr. Mapriededer",male,26.5
1307,3,0,"Zakarian, Mr. Ortin",male,27
1308,3,0,"Zimmerman, Mr. Leo",male,29