# 🛳️ Sobrevivientes del Titanic

En este notebook trabajamos con un subconjunto de datos del Titanic. Aprenderás cómo:
- Leer un archivo CSV que tiene encabezados personalizados.
- Reemplazar los nombres de columnas con otros nuevos.
- Corregir encabezados cuando el archivo ya tiene títulos en la primera fila.
- Detectar valores nulos en columnas del DataFrame.
- Identificar qué columna tiene más valores faltantes.
- Obtener un resumen estadístico de columnas numéricas y categóricas.
- Calcular sumas, medias y conteos con Pandas.

## 📦 Importar pandas

Primero, importamos la biblioteca `pandas`, que nos permite trabajar con estructuras de datos tabulares como los archivos `.csv`.

In [1]:
import pandas as pd

## 👁️ Visualizar el contenido original del archivo CSV

Cargamos el archivo sin modificar los encabezados para ver cómo vienen los nombres de columna originales.

In [2]:
titanic = pd.read_csv("data/titanic_v3.csv")
titanic.head()

,clase_pasajero,sobrevivio,nombre,sexo,edad
0,1,1,"Allen, Miss. Elisabeth Walton",female,29
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167
2,1,0,"Allison, Miss. Helen Loraine",female,2
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25

## 🏷️ Reemplazar los nombres de columnas con una lista personalizada

Si queremos usar nuestros propios nombres de columnas, podemos pasar una lista con ellos usando el parámetro `names`. Pero cuidado:
- Si no se especifica `header=0`, Pandas tratará la **primera fila de datos** como una **fila más**, no como encabezado.
- Esto puede duplicar el encabezado o alterar los datos.

👉 Primero veamos qué ocurre si no usamos `header=0`.

In [3]:
nombres_columnas = ['CLASE PASAJERO', 'SOBREVIVIENTE', 'NOMBRE', 'SEXO', 'EDAD']
titanic = pd.read_csv("data/titanic_v3.csv", names=nombres_columnas)
titanic.head()

,CLASE PASAJERO,SOBREVIVIENTE,NOMBRE,SEXO,EDAD
0,clase_pasajero,sobrevivio,nombre,sexo,edad
1,1,1,"Allen, Miss. Elisabeth Walton",female,29
2,1,1,"Allison, Master. Hudson Trevor",male,0.9167
3,1,0,"Allison, Miss. Helen Loraine",female,2
4,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30

## ✅ Reemplazar nombres correctamente con `header=0`

Ahora sí, indicamos explícitamente que el archivo ya tiene encabezados en la primera fila, usando `header=0`.
De esta forma, Pandas ignorará los encabezados originales y usará nuestra lista `nombres_columnas`.

In [4]:
nombres_columnas = ['CLASE PASAJERO', 'SOBREVIVIENTE', 'NOMBRE', 'SEXO', 'EDAD']
titanic = pd.read_csv("data/titanic_v3.csv", names=nombres_columnas, header=0)
titanic.head()

,CLASE PASAJERO,SOBREVIVIENTE,NOMBRE,SEXO,EDAD
0,1,1,"Allen, Miss. Elisabeth Walton",female,29
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167
2,1,0,"Allison, Miss. Helen Loraine",female,2
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25

## ➕ Suma de columnas numéricas

Usamos `titanic.sum(numeric_only=True)` para sumar los valores de todas las columnas **numéricas** del DataFrame.  
Esto ignora automáticamente columnas con texto u objetos.

```python
titanic.sum(numeric_only=True)

In [5]:
titanic.sum(numeric_only=True)

CLASE PASAJERO    3004
SOBREVIVIENTE      500
dtype: int64


## 🔢 Conteo de valores no nulos

El método `titanic.count()` cuenta cuántos valores **no nulos (non-null)** hay en cada columna.  
Permite detectar si faltan datos en alguna de ellas.

```python
titanic.count()

In [6]:
titanic.count()

CLASE PASAJERO    1309
SOBREVIVIENTE     1309
NOMBRE            1309
SEXO              1309
EDAD              1309
dtype: int64

## 📊 Estadísticas descriptivas de columnas numéricas

La función `titanic.describe()` muestra estadísticas generales (como media, desviación estándar, mínimo, máximo y percentiles)  
de todas las columnas **numéricas** del DataFrame.

```python
titanic.describe()

In [7]:
titanic.describe()

       CLASE PASAJERO  SOBREVIVIENTE
count     1309.000000    1309.000000
mean         2.294882       0.381971
std          0.837836       0.486055
min          1.000000       0.000000
25%          2.000000       0.000000
50%          3.000000       0.000000
75%          3.000000       1.000000
max          3.000000       1.000000

## 📝 Estadísticas descriptivas de columnas tipo texto (object)

La instrucción `titanic.describe(include=["object"])` muestra estadísticas como cantidad de valores, valor más frecuente (top)  
y cuántas veces aparece (freq), pero solo para las columnas **de tipo texto (object)**.

```python
titanic.describe(include=["object"])

In [8]:
titanic.describe(include=["object"])

                      NOMBRE  SEXO  EDAD
count                   1309  1309  1309
unique                  1307     2    99
top     Connolly, Miss. Kate  male     ?
freq                       2   843   263