# 📋 Series: Selección de una sola columna

Cuando trabajamos con **Pandas**, una de las tareas más comunes es acceder a la información de una sola columna de un conjunto de datos. Al seleccionar una columna, **Pandas devuelve un objeto llamado `Series`**, una estructura de datos unidimensional que almacena valores junto con su índice.

Las **Series** son ideales para realizar operaciones de análisis, filtrado, cálculos estadísticos y transformaciones sobre una sola variable del conjunto de datos. Además, muchas de las funciones más utilizadas de Pandas trabajan directamente sobre este tipo de estructura.

## 🎯 ¿Qué aprenderás?

En esta sección aprenderás a:

- 📌 Seleccionar una columna de un `DataFrame`.
- 📌 Comprender qué es una **Series** y cómo se diferencia de un `DataFrame`.
- 📌 Acceder a los valores y al índice de una Series.
- 📌 Aplicar operaciones básicas sobre una columna.
- 📌 Utilizar métodos comunes para explorar y analizar los datos.

## 💡 Ejemplo de uso

Imagina un conjunto de datos de estudiantes con las columnas:

| Nombre | Edad | Carrera |
|--------|------|----------|
| Ana | 20 | Informática |
| Luis | 21 | Civil |
| Sofía | 19 | Química |

Si únicamente seleccionamos la columna **Edad**, el resultado será una **Series** que contiene únicamente las edades de los estudiantes, manteniendo el índice correspondiente a cada registro.

> 🚀 Dominar las **Series** es el primer paso para realizar análisis de datos eficientes con Pandas, ya que la mayoría de las operaciones comienzan seleccionando una o varias columnas de un conjunto de datos.

## 📁 Conjunto de datos del Titanic

In [3]:
import pandas as pd

🔽 Cargando el conjunto de datos Titanic en un DataFrame para su análisis.

In [5]:
titanic = pd.read_csv("data/titanic_v5.csv")
titanic

,clase_pasajero,sobrevivio,nombre,sexo,edad
0,1,1,"Allen, Miss. Elisabeth Walton",female,29
1,1,1,"Astor, Mrs. John Jacob (Madeleine Talmadge Force)",female,18
2,1,1,"Aubart, Mme. Leontine Pauline",female,24
3,1,1,"Barber, Miss. Ellen 'Nellie'",female,26
4,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80
5,1,0,"Baxter, Mr. Quigg Edmond",male,24
6,1,1,"Baxter, Mrs. James (Helene DeLaudeniere Chaput)",female,50
7,1,1,"Bazzani, Miss. Albina",female,32
8,2,0,"Parker, Mr. Clifford Richard",male,28
9,2,1,"Parrish, Mrs. (Lutie Davis)",female,50
10,2,0,"Pengelly, Mr. Frederick William",male,19
11,2,0,"Peruschitz, Rev. Joseph Maria",male,41
12,2,1,"Phillips, Miss. Alice Frances Louisa",female,21
13,2,1,"Phillips, Miss. Kate Florence ('Mrs Kate Louis...",female,19
14,2,0,"Phillips, Mr. Escott Robert",male,43
15,2,1,"Pinsky, Mrs. (Rosa)",female,32
16,2,0,"Ponesell, Mr. Martin",male,34
17,3,0,"Abbing, Mr. Anthony",male,42
18,3,0,"Abbott, Master. Eugene Joseph",male,13
19,3,0,"Abbott, Mr. Rossmore Edward",male,16
20,3,1,"Abbott, Mrs. Stanton (Rosa Hunt)",female,35
21,3,1,"Abelseth, Miss. Karen Marie",female,16
22,3,0,"Andersen, Mr. Albert Karvin",male,32
23,3,1,"Andersen-Jensen, Miss. Carla Christine Nielsine",female,19
24,3,0,"Andersson, Master. Sigvard Harald Elias",male,4
25,3,0,"Andersson, Miss. Ebba Iris Alfrida",female,6
26,3,0,"Andersson, Miss. Ellis Anna Maria",female,2
27,3,1,"Andersson, Miss. Erna Alexandra",female,17

## 👤 Mostrando la columna `nombre` mediante la notación punto

In [7]:
titanic.nombre

0                         Allen, Miss. Elisabeth Walton
1     Astor, Mrs. John Jacob (Madeleine Talmadge Force)
2                         Aubart, Mme. Leontine Pauline
3                          Barber, Miss. Ellen 'Nellie'
4                  Barkworth, Mr. Algernon Henry Wilson
5                              Baxter, Mr. Quigg Edmond
6       Baxter, Mrs. James (Helene DeLaudeniere Chaput)
7                                 Bazzani, Miss. Albina
8                          Parker, Mr. Clifford Richard
9                           Parrish, Mrs. (Lutie Davis)
10                      Pengelly, Mr. Frederick William
11                        Peruschitz, Rev. Joseph Maria
12                 Phillips, Miss. Alice Frances Louisa
13    Phillips, Miss. Kate Florence ('Mrs Kate Louis...
14                          Phillips, Mr. Escott Robert
15                                  Pinsky, Mrs. (Rosa)
16                                 Ponesell, Mr. Martin
17                                  Abbing, Mr. Anthony
18                        Abbott, Master. Eugene Joseph
19                          Abbott, Mr. Rossmore Edward
20                     Abbott, Mrs. Stanton (Rosa Hunt)
21                          Abelseth, Miss. Karen Marie
22                          Andersen, Mr. Albert Karvin
23      Andersen-Jensen, Miss. Carla Christine Nielsine
24              Andersson, Master. Sigvard Harald Elias
25                   Andersson, Miss. Ebba Iris Alfrida
26                    Andersson, Miss. Ellis Anna Maria
27                      Andersson, Miss. Erna Alexandra
Name: nombre, dtype: object

## 🔎 Mostrando la columna `nombre` mediante la notación corchetes
### ✅ Esta notación es más flexible y recomendada.

In [9]:
titanic["nombre"]

0                         Allen, Miss. Elisabeth Walton
1     Astor, Mrs. John Jacob (Madeleine Talmadge Force)
2                         Aubart, Mme. Leontine Pauline
3                          Barber, Miss. Ellen 'Nellie'
4                  Barkworth, Mr. Algernon Henry Wilson
5                              Baxter, Mr. Quigg Edmond
6       Baxter, Mrs. James (Helene DeLaudeniere Chaput)
7                                 Bazzani, Miss. Albina
8                          Parker, Mr. Clifford Richard
9                           Parrish, Mrs. (Lutie Davis)
10                      Pengelly, Mr. Frederick William
11                        Peruschitz, Rev. Joseph Maria
12                 Phillips, Miss. Alice Frances Louisa
13    Phillips, Miss. Kate Florence ('Mrs Kate Louis...
14                          Phillips, Mr. Escott Robert
15                                  Pinsky, Mrs. (Rosa)
16                                 Ponesell, Mr. Martin
17                                  Abbing, Mr. Anthony
18                        Abbott, Master. Eugene Joseph
19                          Abbott, Mr. Rossmore Edward
20                     Abbott, Mrs. Stanton (Rosa Hunt)
21                          Abelseth, Miss. Karen Marie
22                          Andersen, Mr. Albert Karvin
23      Andersen-Jensen, Miss. Carla Christine Nielsine
24              Andersson, Master. Sigvard Harald Elias
25                   Andersson, Miss. Ebba Iris Alfrida
26                    Andersson, Miss. Ellis Anna Maria
27                      Andersson, Miss. Erna Alexandra
Name: nombre, dtype: object

## 🧠 Usar una variable para seleccionar una columna dinámicamente

In [11]:
nombre_columna = "edad"
titanic[nombre_columna]

0     29
1     18
2     24
3     26
4     80
5     24
6     50
7     32
8     28
9     50
10    19
11    41
12    21
13    19
14    43
15    32
16    34
17    42
18    13
19    16
20    35
21    16
22    32
23    19
24     4
25     6
26     2
27    17
Name: edad, dtype: int64

In [12]:
# 🧬 Verificamos el tipo: pandas.Series
type(titanic[nombre_columna])

pandas.core.series.Series

## ➕ Sumar los valores de una Series booleana como 'sobrevivio'

In [14]:
titanic["sobrevivio"].sum()

15

## 🔝 Obtener el valor máximo de la columna `edad`

In [16]:
titanic["edad"].max()

80

## 💾 Guardar una Series en una variable para manipularla después

In [18]:
nombres = titanic["nombre"]

In [19]:
nombres.values

array(['Allen, Miss. Elisabeth Walton',
       'Astor, Mrs. John Jacob (Madeleine Talmadge Force)',
       'Aubart, Mme. Leontine Pauline', "Barber, Miss. Ellen 'Nellie'",
       'Barkworth, Mr. Algernon Henry Wilson', 'Baxter, Mr. Quigg Edmond',
       'Baxter, Mrs. James (Helene DeLaudeniere Chaput)',
       'Bazzani, Miss. Albina', 'Parker, Mr. Clifford Richard',
       'Parrish, Mrs. (Lutie Davis)', 'Pengelly, Mr. Frederick William',
       'Peruschitz, Rev. Joseph Maria',
       'Phillips, Miss. Alice Frances Louisa',
       "Phillips, Miss. Kate Florence ('Mrs Kate Louise Phillips Marshall')",
       'Phillips, Mr. Escott Robert', 'Pinsky, Mrs. (Rosa)',
       'Ponesell, Mr. Martin', 'Abbing, Mr. Anthony',
       'Abbott, Master. Eugene Joseph', 'Abbott, Mr. Rossmore Edward',
       'Abbott, Mrs. Stanton (Rosa Hunt)', 'Abelseth, Miss. Karen Marie',
       'Andersen, Mr. Albert Karvin',
       'Andersen-Jensen, Miss. Carla Christine Nielsine',
       'Andersson, Master. Sigvard Harald Elias',
       'Andersson, Miss. Ebba Iris Alfrida',
       'Andersson, Miss. Ellis Anna Maria',
       'Andersson, Miss. Erna Alexandra'], dtype=object)

## 👀 Obtener algunas filas del inicio y final de la Series

In [21]:
titanic["nombre"].head()

0                        Allen, Miss. Elisabeth Walton
1    Astor, Mrs. John Jacob (Madeleine Talmadge Force)
2                        Aubart, Mme. Leontine Pauline
3                         Barber, Miss. Ellen 'Nellie'
4                 Barkworth, Mr. Algernon Henry Wilson
Name: nombre, dtype: object

In [22]:
titanic["nombre"].tail()

23    Andersen-Jensen, Miss. Carla Christine Nielsine
24            Andersson, Master. Sigvard Harald Elias
25                 Andersson, Miss. Ebba Iris Alfrida
26                  Andersson, Miss. Ellis Anna Maria
27                    Andersson, Miss. Erna Alexandra
Name: nombre, dtype: object

## 📊 Estadísticas descriptivas de la columna `edad`

In [24]:
titanic["edad"].describe()

count    28.000000
mean     27.571429
std      16.317290
min       2.000000
25%      17.750000
50%      25.000000
75%      34.250000
max      80.000000
Name: edad, dtype: float64

## 🔁 Valores únicos que aparecen en columnas categóricas o numéricas

In [26]:
titanic["clase_pasajero"].unique()

array([1, 2, 3])

In [27]:
titanic["edad"].unique()

array([29, 18, 24, 26, 80, 50, 32, 28, 19, 41, 21, 43, 34, 42, 13, 16, 35,
        4,  6,  2, 17])

In [28]:
titanic["sexo"].unique()

array(['female', 'male'], dtype=object)

## 🔢 Contar cuántos valores distintos hay por columna

In [30]:
titanic["clase_pasajero"].nunique()

3

In [31]:
titanic["edad"].nunique()

21

In [32]:
titanic["sexo"].nunique()

2

## 📈 Obtener los valores extremos (grandes y chicos) de `edad`

In [34]:
titanic["edad"].nlargest()

4     80
6     50
9     50
14    43
17    42
Name: edad, dtype: int64

In [35]:
titanic["edad"].nsmallest()

26     2
24     4
25     6
18    13
19    16
Name: edad, dtype: int64

### 👶 Edad más baja registrada

In [37]:
titanic["edad"].min()

2

### 👴 Edad más alta registrada

In [39]:
titanic["edad"].max()

80

### 🔸 Obtener la mediana (valor medio) de la columna `edad`

In [41]:
titanic["edad"].median()

25.0

### 🧮 Calcular la media solo de los primeros 5 registros

In [43]:
titanic["edad"].head().mean()

35.4

In [44]:
titanic["edad"].head()

0    29
1    18
2    24
3    26
4    80
Name: edad, dtype: int64

## 🔍 Mostrar los registros con mayores edades del dataset

In [46]:
titanic.nlargest(10, ["edad"])

,clase_pasajero,sobrevivio,nombre,sexo,edad
4,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80
6,1,1,"Baxter, Mrs. James (Helene DeLaudeniere Chaput)",female,50
9,2,1,"Parrish, Mrs. (Lutie Davis)",female,50
14,2,0,"Phillips, Mr. Escott Robert",male,43
17,3,0,"Abbing, Mr. Anthony",male,42
11,2,0,"Peruschitz, Rev. Joseph Maria",male,41
20,3,1,"Abbott, Mrs. Stanton (Rosa Hunt)",female,35
16,2,0,"Ponesell, Mr. Martin",male,34
7,1,1,"Bazzani, Miss. Albina",female,32
15,2,1,"Pinsky, Mrs. (Rosa)",female,32

## 🧓 Mostrar los 10 pasajeros más jóvenes

In [48]:
titanic.nsmallest(10, ["edad"])

,clase_pasajero,sobrevivio,nombre,sexo,edad
26,3,0,"Andersson, Miss. Ellis Anna Maria",female,2
24,3,0,"Andersson, Master. Sigvard Harald Elias",male,4
25,3,0,"Andersson, Miss. Ebba Iris Alfrida",female,6
18,3,0,"Abbott, Master. Eugene Joseph",male,13
19,3,0,"Abbott, Mr. Rossmore Edward",male,16
21,3,1,"Abelseth, Miss. Karen Marie",female,16
27,3,1,"Andersson, Miss. Erna Alexandra",female,17
1,1,1,"Astor, Mrs. John Jacob (Madeleine Talmadge Force)",female,18
10,2,0,"Pengelly, Mr. Frederick William",male,19
13,2,1,"Phillips, Miss. Kate Florence ('Mrs Kate Louis...",female,19