# 📋 DataFrame: Selección de múltiples columnas

En muchas ocasiones no basta con trabajar con una sola columna; es necesario analizar varias variables al mismo tiempo. En **Pandas**, cuando seleccionamos **dos o más columnas** de un `DataFrame`, el resultado sigue siendo un **DataFrame**, ya que conserva la estructura de filas y columnas.

Seleccionar múltiples columnas permite comparar información, crear subconjuntos de datos y preparar conjuntos de datos para análisis, visualizaciones o modelos de aprendizaje automático.

## 🎯 ¿Qué aprenderás?

En esta sección aprenderás a:

- 📌 Seleccionar dos o más columnas de un `DataFrame`.
- 📌 Comprender la diferencia entre obtener una **Series** y un **DataFrame**.
- 📌 Crear subconjuntos de datos con las columnas de interés.
- 📌 Cambiar el orden de las columnas seleccionadas.
- 📌 Preparar datos para su análisis o exportación.

## 💡 Ejemplo de uso

Imagina un conjunto de datos de estudiantes con las siguientes columnas:

| Nombre | Edad | Carrera | Promedio |
|---------|------|----------|-----------|
| Ana | 20 | Informática | 9.4 |
| Luis | 21 | Civil | 8.7 |
| Sofía | 19 | Química | 9.8 |

Si seleccionamos únicamente las columnas **Nombre** y **Promedio**, obtendremos un nuevo **DataFrame** que contiene solo esa información, manteniendo todas las filas del conjunto de datos original.

> 🚀 La selección de múltiples columnas es una técnica fundamental para trabajar únicamente con la información necesaria, facilitando el análisis, la limpieza y la manipulación de datos en Pandas.

## 📁 Cargando el conjunto de datos del Titanic
Usaremos los datos del Titanic 🛳️ para aprender a seleccionar más de una columna con pandas.

In [3]:
import pandas as pd

📌 Cargamos el archivo CSV y lo guardamos en un DataFrame llamado `titanic`.
Esto nos permitirá analizar la información de los pasajeros.

In [5]:
titanic = pd.read_csv("data/titanic_v5.csv")
titanic

,clase_pasajero,sobrevivio,nombre,sexo,edad
0,1,1,"Allen, Miss. Elisabeth Walton",female,29
1,1,1,"Astor, Mrs. John Jacob (Madeleine Talmadge Force)",female,18
2,1,1,"Aubart, Mme. Leontine Pauline",female,24
3,1,1,"Barber, Miss. Ellen 'Nellie'",female,26
4,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80
5,1,0,"Baxter, Mr. Quigg Edmond",male,24
6,1,1,"Baxter, Mrs. James (Helene DeLaudeniere Chaput)",female,50
7,1,1,"Bazzani, Miss. Albina",female,32
8,2,0,"Parker, Mr. Clifford Richard",male,28
9,2,1,"Parrish, Mrs. (Lutie Davis)",female,50
10,2,0,"Pengelly, Mr. Frederick William",male,19
11,2,0,"Peruschitz, Rev. Joseph Maria",male,41
12,2,1,"Phillips, Miss. Alice Frances Louisa",female,21
13,2,1,"Phillips, Miss. Kate Florence ('Mrs Kate Louis...",female,19
14,2,0,"Phillips, Mr. Escott Robert",male,43
15,2,1,"Pinsky, Mrs. (Rosa)",female,32
16,2,0,"Ponesell, Mr. Martin",male,34
17,3,0,"Abbing, Mr. Anthony",male,42
18,3,0,"Abbott, Master. Eugene Joseph",male,13
19,3,0,"Abbott, Mr. Rossmore Edward",male,16
20,3,1,"Abbott, Mrs. Stanton (Rosa Hunt)",female,35
21,3,1,"Abelseth, Miss. Karen Marie",female,16
22,3,0,"Andersen, Mr. Albert Karvin",male,32
23,3,1,"Andersen-Jensen, Miss. Carla Christine Nielsine",female,19
24,3,0,"Andersson, Master. Sigvard Harald Elias",male,4
25,3,0,"Andersson, Miss. Ebba Iris Alfrida",female,6
26,3,0,"Andersson, Miss. Ellis Anna Maria",female,2
27,3,1,"Andersson, Miss. Erna Alexandra",female,17

## 👀 Visualizando múltiples columnas: `nombre` y `edad`
Seleccionamos solo estas dos columnas y después mostramos las últimas 10 filas del resultado.

In [7]:
titanic[["nombre", "edad"]]

                                               nombre  edad
0                       Allen, Miss. Elisabeth Walton    29
1   Astor, Mrs. John Jacob (Madeleine Talmadge Force)    18
2                       Aubart, Mme. Leontine Pauline    24
3                        Barber, Miss. Ellen 'Nellie'    26
4                Barkworth, Mr. Algernon Henry Wilson    80
5                            Baxter, Mr. Quigg Edmond    24
6     Baxter, Mrs. James (Helene DeLaudeniere Chaput)    50
7                               Bazzani, Miss. Albina    32
8                        Parker, Mr. Clifford Richard    28
9                         Parrish, Mrs. (Lutie Davis)    50
10                    Pengelly, Mr. Frederick William    19
11                      Peruschitz, Rev. Joseph Maria    41
12               Phillips, Miss. Alice Frances Louisa    21
13  Phillips, Miss. Kate Florence ('Mrs Kate Louis...    19
14                        Phillips, Mr. Escott Robert    43
15                                Pinsky, Mrs. (Rosa)    32
16                               Ponesell, Mr. Martin    34
17                                Abbing, Mr. Anthony    42
18                      Abbott, Master. Eugene Joseph    13
19                        Abbott, Mr. Rossmore Edward    16
20                   Abbott, Mrs. Stanton (Rosa Hunt)    35
21                        Abelseth, Miss. Karen Marie    16
22                        Andersen, Mr. Albert Karvin    32
23    Andersen-Jensen, Miss. Carla Christine Nielsine    19
24            Andersson, Master. Sigvard Harald Elias     4
25                 Andersson, Miss. Ebba Iris Alfrida     6
26                  Andersson, Miss. Ellis Anna Maria     2
27                    Andersson, Miss. Erna Alexandra    17

In [8]:
titanic[["nombre", "edad"]].tail(10)

                                             nombre  edad
18                    Abbott, Master. Eugene Joseph    13
19                      Abbott, Mr. Rossmore Edward    16
20                 Abbott, Mrs. Stanton (Rosa Hunt)    35
21                      Abelseth, Miss. Karen Marie    16
22                      Andersen, Mr. Albert Karvin    32
23  Andersen-Jensen, Miss. Carla Christine Nielsine    19
24          Andersson, Master. Sigvard Harald Elias     4
25               Andersson, Miss. Ebba Iris Alfrida     6
26                Andersson, Miss. Ellis Anna Maria     2
27                  Andersson, Miss. Erna Alexandra    17

## 📊 Estadísticas de columnas numéricas: `sobrevivio` y `edad`
Con `.describe()` obtenemos información como la media, desviación estándar, valores mínimo y máximo, etc.

In [10]:
titanic[["sobrevivio", "edad"]].describe()

       sobrevivio       edad
count   28.000000  28.000000
mean     0.535714  27.571429
std      0.507875  16.317290
min      0.000000   2.000000
25%      0.000000  17.750000
50%      1.000000  25.000000
75%      1.000000  34.250000
max      1.000000  80.000000

## 🔝 Seleccionar los valores más grandes mezclando columnas
Con `nlargest()` mostramos los 10 registros con valores más altos combinando `clase_pasajero` y `edad`.
Ideal para encontrar adultos mayores en clases altas, por ejemplo.

In [12]:
# Ordenamos por clase de pasajero y edad de forma descendente
titanic.nlargest(10, ["clase_pasajero", "edad"])

,clase_pasajero,sobrevivio,nombre,sexo,edad
17,3,0,"Abbing, Mr. Anthony",male,42
20,3,1,"Abbott, Mrs. Stanton (Rosa Hunt)",female,35
22,3,0,"Andersen, Mr. Albert Karvin",male,32
23,3,1,"Andersen-Jensen, Miss. Carla Christine Nielsine",female,19
27,3,1,"Andersson, Miss. Erna Alexandra",female,17
19,3,0,"Abbott, Mr. Rossmore Edward",male,16
21,3,1,"Abelseth, Miss. Karen Marie",female,16
18,3,0,"Abbott, Master. Eugene Joseph",male,13
25,3,0,"Andersson, Miss. Ebba Iris Alfrida",female,6
24,3,0,"Andersson, Master. Sigvard Harald Elias",male,4

### 🛠️ Selección usando una lista de columnas
Podemos crear una lista con los nombres de las columnas que nos interesan 📋 y luego usarla para extraerlas del DataFrame.

In [14]:
columnas = ["nombre", "sexo", "edad"]
titanic[columnas]

                                               nombre    sexo  edad
0                       Allen, Miss. Elisabeth Walton  female    29
1   Astor, Mrs. John Jacob (Madeleine Talmadge Force)  female    18
2                       Aubart, Mme. Leontine Pauline  female    24
3                        Barber, Miss. Ellen 'Nellie'  female    26
4                Barkworth, Mr. Algernon Henry Wilson    male    80
5                            Baxter, Mr. Quigg Edmond    male    24
6     Baxter, Mrs. James (Helene DeLaudeniere Chaput)  female    50
7                               Bazzani, Miss. Albina  female    32
8                        Parker, Mr. Clifford Richard    male    28
9                         Parrish, Mrs. (Lutie Davis)  female    50
10                    Pengelly, Mr. Frederick William    male    19
11                      Peruschitz, Rev. Joseph Maria    male    41
12               Phillips, Miss. Alice Frances Louisa  female    21
13  Phillips, Miss. Kate Florence ('Mrs Kate Louis...  female    19
14                        Phillips, Mr. Escott Robert    male    43
15                                Pinsky, Mrs. (Rosa)  female    32
16                               Ponesell, Mr. Martin    male    34
17                                Abbing, Mr. Anthony    male    42
18                      Abbott, Master. Eugene Joseph    male    13
19                        Abbott, Mr. Rossmore Edward    male    16
20                   Abbott, Mrs. Stanton (Rosa Hunt)  female    35
21                        Abelseth, Miss. Karen Marie  female    16
22                        Andersen, Mr. Albert Karvin    male    32
23    Andersen-Jensen, Miss. Carla Christine Nielsine  female    19
24            Andersson, Master. Sigvard Harald Elias    male     4
25                 Andersson, Miss. Ebba Iris Alfrida  female     6
26                  Andersson, Miss. Ellis Anna Maria  female     2
27                    Andersson, Miss. Erna Alexandra  female    17