# 🎮 Pandas `loc` e `iloc` con DataFrames

Cuando trabajamos con un **DataFrame**, es muy común necesitar acceder a filas y columnas específicas. Para ello, **Pandas** ofrece dos herramientas muy poderosas: `loc` e `iloc`.

Aunque ambas permiten seleccionar datos, existe una diferencia importante: **`loc` utiliza etiquetas (índices y nombres de columnas)**, mientras que **`iloc` trabaja con posiciones numéricas**. Conocer cuándo utilizar cada una facilitará la consulta y manipulación de los datos.

En esta práctica utilizaremos un **conjunto de datos de ventas de videojuegos**, lo que permitirá aplicar estos conceptos en un escenario real de análisis de datos.

## 🎯 ¿Qué aprenderás?

En esta sección aprenderás a:

- 📌 Comprender la diferencia entre `loc` e `iloc`.
- 📌 Seleccionar filas utilizando etiquetas con `loc`.
- 📌 Seleccionar filas mediante posiciones numéricas con `iloc`.
- 📌 Acceder a columnas específicas o a combinaciones de filas y columnas.
- 📌 Extraer subconjuntos de un `DataFrame` para realizar análisis más específicos.

## 💡 Ejemplo de uso

Imagina un conjunto de datos con información sobre videojuegos:

| Juego | Plataforma | Género | Ventas (millones) |
|--------|------------|---------|-------------------|
| Minecraft | PC | Sandbox | 300 |
| Mario Kart 8 | Switch | Carreras | 75 |
| GTA V | Multiplataforma | Acción | 215 |
| FIFA 24 | Multiplataforma | Deportes | 25 |

Con **`loc`** podrías seleccionar el registro del videojuego **Minecraft** utilizando su etiqueta o índice, mientras que con **`iloc`** podrías obtener el primer registro simplemente indicando su posición (`0`). También es posible seleccionar varias filas y columnas para analizar únicamente la información que necesitas.

> 🚀 Dominar **`loc`** e **`iloc`** te permitirá navegar por cualquier `DataFrame` con facilidad, realizar consultas precisas y preparar los datos para análisis, visualizaciones o modelos de ciencia de datos.

📥 **Importamos la librería Pandas** para trabajar con DataFrames.

In [1]:
import pandas as pd

📄 **Cargamos el archivo CSV** con datos de ventas de videojuegos.

In [2]:
ventas = pd.read_csv("data/ventas_videojuegos.csv")

🔢 **Establecemos la columna `Titulo` como índice** para facilitar el uso de `loc`.

In [3]:
ventas.set_index("Titulo", inplace=True)
ventas

,Plataforma,Año,Genero,Publisher,Ventas_NA,Ventas_EU,Ventas_JP,Ventas_Globales
Titulo,,,,,,,,
Halo 3,X360,2007,Shooter,Microsoft Game Studios,14,5,2,22
FIFA 16,PS4,2015,Sports,Electronic Arts,7,9,9,20
FIFA Soccer 13,PS3,2012,Action,Electronic Arts,10,5,6,16
Kinect Sports,X360,2010,Sports,Microsoft Game Studios,9,4,1,15
The Last of Us,PS3,2013,Action,Sony Computer Entertainment,10,4,1,15
Batman: Arkham City,PS3,2011,Action,Warner Bros. Interactive Entertainment,6,6,3,14
Minecraft,PS3,2014,Misc,Sony Computer Entertainment,5,6,6,14
Final Fantasy XIII,PS3,2009,Role-Playing,Square Enix,8,4,1,13
Resident Evil 5,PS3,2009,Action,Capcom,8,4,8,13
Call of Duty: Modern Warfare 3,PS3,2011,Shooter,Activision,6,6,5,13

## 🔍 Recuperar registros con `loc[ ]`
`loc` permite acceder a filas por su etiqueta (nombre).

🎯 **Obtenemos un solo registro por su título.**

In [4]:
ventas.loc["Halo 3"]

Plataforma                           X360
Año                                  2007
Genero                            Shooter
Publisher          Microsoft Game Studios
Ventas_NA                              14
Ventas_EU                               5
Ventas_JP                               2
Ventas_Globales                        22
Name: Halo 3, dtype: object

📦 **Obtenemos un registro en formato DataFrame (doble corchete).**

In [5]:
ventas.loc[["Halo 3"]]

,Plataforma,Año,Genero,Publisher,Ventas_NA,Ventas_EU,Ventas_JP,Ventas_Globales
Titulo,,,,,,,,
Halo 3,X360,2007,Shooter,Microsoft Game Studios,14,5,2,22

🟩 **Buscamos otro videojuego por su título.**

In [6]:
ventas.loc[["Minecraft"]]

,Plataforma,Año,Genero,Publisher,Ventas_NA,Ventas_EU,Ventas_JP,Ventas_Globales
Titulo,,,,,,,,
Minecraft,PS3,2014,Misc,Sony Computer Entertainment,5,6,6,14

🗃️ **Buscamos varios videojuegos al mismo tiempo.**

In [7]:
ventas.loc[["Minecraft", "Halo 3", "Batman: Arkham City"]]

,Plataforma,Año,Genero,Publisher,Ventas_NA,Ventas_EU,Ventas_JP,Ventas_Globales
Titulo,,,,,,,,
Minecraft,PS3,2014,Misc,Sony Computer Entertainment,5,6,6,14
Halo 3,X360,2007,Shooter,Microsoft Game Studios,14,5,2,22
Batman: Arkham City,PS3,2011,Action,Warner Bros. Interactive Entertainment,6,6,3,14

🔠 **Ordenamos el DataFrame por el índice (títulos).**

In [8]:
ventas.sort_index(inplace=True)
ventas

,Plataforma,Año,Genero,Publisher,Ventas_NA,Ventas_EU,Ventas_JP,Ventas_Globales
Titulo,,,,,,,,
Batman: Arkham City,PS3,2011,Action,Warner Bros. Interactive Entertainment,6,6,3,14
Call of Duty: Modern Warfare 3,PS3,2011,Shooter,Activision,6,6,5,13
FIFA 16,PS4,2015,Sports,Electronic Arts,7,9,9,20
FIFA Soccer 13,PS3,2012,Action,Electronic Arts,10,5,6,16
Final Fantasy XIII,PS3,2009,Role-Playing,Square Enix,8,4,1,13
Halo 3,X360,2007,Shooter,Microsoft Game Studios,14,5,2,22
Kinect Sports,X360,2010,Sports,Microsoft Game Studios,9,4,1,15
Minecraft,PS3,2014,Misc,Sony Computer Entertainment,5,6,6,14
Resident Evil 5,PS3,2009,Action,Capcom,8,4,8,13
The Last of Us,PS3,2013,Action,Sony Computer Entertainment,10,4,1,15

🔍 **Seleccionamos un rango de títulos (inclusive).**

In [9]:
ventas.loc["FIFA Soccer 13": "Kinect Sports"]

,Plataforma,Año,Genero,Publisher,Ventas_NA,Ventas_EU,Ventas_JP,Ventas_Globales
Titulo,,,,,,,,
FIFA Soccer 13,PS3,2012,Action,Electronic Arts,10,5,6,16
Final Fantasy XIII,PS3,2009,Role-Playing,Square Enix,8,4,1,13
Halo 3,X360,2007,Shooter,Microsoft Game Studios,14,5,2,22
Kinect Sports,X360,2010,Sports,Microsoft Game Studios,9,4,1,15

🧩 **Seleccionamos un rango de títulos y columnas específicas.**

In [10]:
ventas.loc["Kinect Sports":"Resident Evil 5", ['Plataforma', 'Publisher']]

                Plataforma                    Publisher
Titulo
Kinect Sports         X360       Microsoft Game Studios
Minecraft              PS3  Sony Computer Entertainment
Resident Evil 5        PS3                       Capcom

📊 **Seleccionamos columnas de género y ventas en Norteamérica.**

In [11]:
ventas.loc["FIFA Soccer 13": "Kinect Sports", ["Genero", "Ventas_NA"]]

                          Genero  Ventas_NA
Titulo
FIFA Soccer 13            Action         10
Final Fantasy XIII  Role-Playing          8
Halo 3                   Shooter         14
Kinect Sports             Sports          9

## 🔢 Recuperar registros con índice numérico usando `loc`
`loc` también se puede usar con índices numéricos si no hay un índice personalizado.

🔄 **Volvemos a cargar los datos para usar el índice numérico.**

In [12]:
ventas = pd.read_csv("data/ventas_videojuegos.csv")
ventas

,Titulo,Plataforma,Año,Genero,Publisher,Ventas_NA,Ventas_EU,Ventas_JP,Ventas_Globales
0,Halo 3,X360,2007,Shooter,Microsoft Game Studios,14,5,2,22
1,FIFA 16,PS4,2015,Sports,Electronic Arts,7,9,9,20
2,FIFA Soccer 13,PS3,2012,Action,Electronic Arts,10,5,6,16
3,Kinect Sports,X360,2010,Sports,Microsoft Game Studios,9,4,1,15
4,The Last of Us,PS3,2013,Action,Sony Computer Entertainment,10,4,1,15
5,Batman: Arkham City,PS3,2011,Action,Warner Bros. Interactive Entertainment,6,6,3,14
6,Minecraft,PS3,2014,Misc,Sony Computer Entertainment,5,6,6,14
7,Final Fantasy XIII,PS3,2009,Role-Playing,Square Enix,8,4,1,13
8,Resident Evil 5,PS3,2009,Action,Capcom,8,4,8,13
9,Call of Duty: Modern Warfare 3,PS3,2011,Shooter,Activision,6,6,5,13

📌 **Seleccionamos registros específicos por su número de fila.**

In [13]:
ventas.loc[[1, 6, 9]]

,Titulo,Plataforma,Año,Genero,Publisher,Ventas_NA,Ventas_EU,Ventas_JP,Ventas_Globales
1,FIFA 16,PS4,2015,Sports,Electronic Arts,7,9,9,20
6,Minecraft,PS3,2014,Misc,Sony Computer Entertainment,5,6,6,14
9,Call of Duty: Modern Warfare 3,PS3,2011,Shooter,Activision,6,6,5,13

📚 **Seleccionamos un rango de filas continuas.**

In [14]:
ventas.loc[5:9]

,Titulo,Plataforma,Año,Genero,Publisher,Ventas_NA,Ventas_EU,Ventas_JP,Ventas_Globales
5,Batman: Arkham City,PS3,2011,Action,Warner Bros. Interactive Entertainment,6,6,3,14
6,Minecraft,PS3,2014,Misc,Sony Computer Entertainment,5,6,6,14
7,Final Fantasy XIII,PS3,2009,Role-Playing,Square Enix,8,4,1,13
8,Resident Evil 5,PS3,2009,Action,Capcom,8,4,8,13
9,Call of Duty: Modern Warfare 3,PS3,2011,Shooter,Activision,6,6,5,13

⏩ **Seleccionamos filas con un paso de 2 en el rango.**

In [15]:
ventas.loc[5:9:2]

,Titulo,Plataforma,Año,Genero,Publisher,Ventas_NA,Ventas_EU,Ventas_JP,Ventas_Globales
5,Batman: Arkham City,PS3,2011,Action,Warner Bros. Interactive Entertainment,6,6,3,14
7,Final Fantasy XIII,PS3,2009,Role-Playing,Square Enix,8,4,1,13
9,Call of Duty: Modern Warfare 3,PS3,2011,Shooter,Activision,6,6,5,13

🔢 **Buscamos cuántas veces aparece un valor específico en una columna.**

In [16]:
ventas["Ventas_NA"].value_counts().loc[14]

1

## 🎯 Recuperar registros con `iloc`
`iloc` se usa para acceder a registros por su posición numérica.

🧱 **Establecemos `Titulo` como índice de nuevo para futuras operaciones.**

In [17]:
ventas.set_index("Titulo", inplace=True)
ventas

,Plataforma,Año,Genero,Publisher,Ventas_NA,Ventas_EU,Ventas_JP,Ventas_Globales
Titulo,,,,,,,,
Halo 3,X360,2007,Shooter,Microsoft Game Studios,14,5,2,22
FIFA 16,PS4,2015,Sports,Electronic Arts,7,9,9,20
FIFA Soccer 13,PS3,2012,Action,Electronic Arts,10,5,6,16
Kinect Sports,X360,2010,Sports,Microsoft Game Studios,9,4,1,15
The Last of Us,PS3,2013,Action,Sony Computer Entertainment,10,4,1,15
Batman: Arkham City,PS3,2011,Action,Warner Bros. Interactive Entertainment,6,6,3,14
Minecraft,PS3,2014,Misc,Sony Computer Entertainment,5,6,6,14
Final Fantasy XIII,PS3,2009,Role-Playing,Square Enix,8,4,1,13
Resident Evil 5,PS3,2009,Action,Capcom,8,4,8,13
Call of Duty: Modern Warfare 3,PS3,2011,Shooter,Activision,6,6,5,13

🔖 **Seleccionamos el primer registro con `iloc`.**

In [18]:
ventas.iloc[[0]]

,Plataforma,Año,Genero,Publisher,Ventas_NA,Ventas_EU,Ventas_JP,Ventas_Globales
Titulo,,,,,,,,
Halo 3,X360,2007,Shooter,Microsoft Game Studios,14,5,2,22

🎯 **Seleccionamos múltiples filas específicas por posición.**

In [19]:
ventas.iloc[[1, 4, 5, 8]]

,Plataforma,Año,Genero,Publisher,Ventas_NA,Ventas_EU,Ventas_JP,Ventas_Globales
Titulo,,,,,,,,
FIFA 16,PS4,2015,Sports,Electronic Arts,7,9,9,20
The Last of Us,PS3,2013,Action,Sony Computer Entertainment,10,4,1,15
Batman: Arkham City,PS3,2011,Action,Warner Bros. Interactive Entertainment,6,6,3,14
Resident Evil 5,PS3,2009,Action,Capcom,8,4,8,13

📏 **Seleccionamos un rango de filas por posición.**

In [20]:
ventas.iloc[1:4]

,Plataforma,Año,Genero,Publisher,Ventas_NA,Ventas_EU,Ventas_JP,Ventas_Globales
Titulo,,,,,,,,
FIFA 16,PS4,2015,Sports,Electronic Arts,7,9,9,20
FIFA Soccer 13,PS3,2012,Action,Electronic Arts,10,5,6,16
Kinect Sports,X360,2010,Sports,Microsoft Game Studios,9,4,1,15

🔃 **Ordenamos el DataFrame por el título.**

In [21]:
ventas.sort_values("Titulo", inplace=True)
ventas

,Plataforma,Año,Genero,Publisher,Ventas_NA,Ventas_EU,Ventas_JP,Ventas_Globales
Titulo,,,,,,,,
Batman: Arkham City,PS3,2011,Action,Warner Bros. Interactive Entertainment,6,6,3,14
Call of Duty: Modern Warfare 3,PS3,2011,Shooter,Activision,6,6,5,13
FIFA 16,PS4,2015,Sports,Electronic Arts,7,9,9,20
FIFA Soccer 13,PS3,2012,Action,Electronic Arts,10,5,6,16
Final Fantasy XIII,PS3,2009,Role-Playing,Square Enix,8,4,1,13
Halo 3,X360,2007,Shooter,Microsoft Game Studios,14,5,2,22
Kinect Sports,X360,2010,Sports,Microsoft Game Studios,9,4,1,15
Minecraft,PS3,2014,Misc,Sony Computer Entertainment,5,6,6,14
Resident Evil 5,PS3,2009,Action,Capcom,8,4,8,13
The Last of Us,PS3,2013,Action,Sony Computer Entertainment,10,4,1,15

🔖 **Mostramos el primer registro luego de ordenar.**

In [22]:
ventas.iloc[[0]]

,Plataforma,Año,Genero,Publisher,Ventas_NA,Ventas_EU,Ventas_JP,Ventas_Globales
Titulo,,,,,,,,
Batman: Arkham City,PS3,2011,Action,Warner Bros. Interactive Entertainment,6,6,3,14

📌 **Accedemos nuevamente a múltiples filas por posición.**

In [23]:
ventas.iloc[[1, 4, 5, 8]]

,Plataforma,Año,Genero,Publisher,Ventas_NA,Ventas_EU,Ventas_JP,Ventas_Globales
Titulo,,,,,,,,
Call of Duty: Modern Warfare 3,PS3,2011,Shooter,Activision,6,6,5,13
Final Fantasy XIII,PS3,2009,Role-Playing,Square Enix,8,4,1,13
Halo 3,X360,2007,Shooter,Microsoft Game Studios,14,5,2,22
Resident Evil 5,PS3,2009,Action,Capcom,8,4,8,13

🧮 **Usamos `iloc` con un rango de posiciones.**

In [24]:
ventas.iloc[1:4]

,Plataforma,Año,Genero,Publisher,Ventas_NA,Ventas_EU,Ventas_JP,Ventas_Globales
Titulo,,,,,,,,
Call of Duty: Modern Warfare 3,PS3,2011,Shooter,Activision,6,6,5,13
FIFA 16,PS4,2015,Sports,Electronic Arts,7,9,9,20
FIFA Soccer 13,PS3,2012,Action,Electronic Arts,10,5,6,16

🔄 **Volvemos a cargar los datos desde cero.**

In [25]:
ventas = pd.read_csv("data/ventas_videojuegos.csv")
ventas

,Titulo,Plataforma,Año,Genero,Publisher,Ventas_NA,Ventas_EU,Ventas_JP,Ventas_Globales
0,Halo 3,X360,2007,Shooter,Microsoft Game Studios,14,5,2,22
1,FIFA 16,PS4,2015,Sports,Electronic Arts,7,9,9,20
2,FIFA Soccer 13,PS3,2012,Action,Electronic Arts,10,5,6,16
3,Kinect Sports,X360,2010,Sports,Microsoft Game Studios,9,4,1,15
4,The Last of Us,PS3,2013,Action,Sony Computer Entertainment,10,4,1,15
5,Batman: Arkham City,PS3,2011,Action,Warner Bros. Interactive Entertainment,6,6,3,14
6,Minecraft,PS3,2014,Misc,Sony Computer Entertainment,5,6,6,14
7,Final Fantasy XIII,PS3,2009,Role-Playing,Square Enix,8,4,1,13
8,Resident Evil 5,PS3,2009,Action,Capcom,8,4,8,13
9,Call of Duty: Modern Warfare 3,PS3,2011,Shooter,Activision,6,6,5,13

🔽 **Ordenamos el índice en orden descendente.**

In [26]:
ventas.sort_index(ascending=False, inplace=True)
ventas

,Titulo,Plataforma,Año,Genero,Publisher,Ventas_NA,Ventas_EU,Ventas_JP,Ventas_Globales
9,Call of Duty: Modern Warfare 3,PS3,2011,Shooter,Activision,6,6,5,13
8,Resident Evil 5,PS3,2009,Action,Capcom,8,4,8,13
7,Final Fantasy XIII,PS3,2009,Role-Playing,Square Enix,8,4,1,13
6,Minecraft,PS3,2014,Misc,Sony Computer Entertainment,5,6,6,14
5,Batman: Arkham City,PS3,2011,Action,Warner Bros. Interactive Entertainment,6,6,3,14
4,The Last of Us,PS3,2013,Action,Sony Computer Entertainment,10,4,1,15
3,Kinect Sports,X360,2010,Sports,Microsoft Game Studios,9,4,1,15
2,FIFA Soccer 13,PS3,2012,Action,Electronic Arts,10,5,6,16
1,FIFA 16,PS4,2015,Sports,Electronic Arts,7,9,9,20
0,Halo 3,X360,2007,Shooter,Microsoft Game Studios,14,5,2,22

🎯 **Mostramos el primer registro después del orden descendente.**

In [27]:
ventas.iloc[[0]]

,Titulo,Plataforma,Año,Genero,Publisher,Ventas_NA,Ventas_EU,Ventas_JP,Ventas_Globales
9,Call of Duty: Modern Warfare 3,PS3,2011,Shooter,Activision,6,6,5,13