# ❗ Filtrado de datos usando negaciones
Aprenderemos a usar **negaciones (~)** para filtrar registros en un DataFrame utilizando pandas 🐼.

## 📥 1. Importar la librería pandas
Usamos la biblioteca `pandas` para manejar datos en forma de tablas (DataFrames) 📊.

In [1]:
import pandas as pd

## 📄 2. Cargar el archivo CSV del Titanic
Leemos el archivo `titanic_v5.csv` que contiene información sobre los pasajeros del Titanic 🛳️.

In [2]:
titanic = pd.read_csv("data/titanic_v5.csv")

## 👀 3. Visualizar el DataFrame completo
Mostremos una vista general del conjunto de datos cargado 🧾.

In [3]:
titanic

,clase_pasajero,sobrevivio,nombre,sexo,edad
0,1,1,"Allen, Miss. Elisabeth Walton",female,29
1,1,1,"Astor, Mrs. John Jacob (Madeleine Talmadge Force)",female,18
2,1,1,"Aubart, Mme. Leontine Pauline",female,24
3,1,1,"Barber, Miss. Ellen 'Nellie'",female,26
4,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80
5,1,0,"Baxter, Mr. Quigg Edmond",male,24
6,1,1,"Baxter, Mrs. James (Helene DeLaudeniere Chaput)",female,50
7,1,1,"Bazzani, Miss. Albina",female,32
8,2,0,"Parker, Mr. Clifford Richard",male,28
9,2,1,"Parrish, Mrs. (Lutie Davis)",female,50
10,2,0,"Pengelly, Mr. Frederick William",male,19
11,2,0,"Peruschitz, Rev. Joseph Maria",male,41
12,2,1,"Phillips, Miss. Alice Frances Louisa",female,21
13,2,1,"Phillips, Miss. Kate Florence ('Mrs Kate Louis...",female,19
14,2,0,"Phillips, Mr. Escott Robert",male,43
15,2,1,"Pinsky, Mrs. (Rosa)",female,32
16,2,0,"Ponesell, Mr. Martin",male,34
17,3,0,"Abbing, Mr. Anthony",male,42
18,3,0,"Abbott, Master. Eugene Joseph",male,13
19,3,0,"Abbott, Mr. Rossmore Edward",male,16
20,3,1,"Abbott, Mrs. Stanton (Rosa Hunt)",female,35
21,3,1,"Abelseth, Miss. Karen Marie",female,16
22,3,0,"Andersen, Mr. Albert Karvin",male,32
23,3,1,"Andersen-Jensen, Miss. Carla Christine Nielsine",female,19
24,3,0,"Andersson, Master. Sigvard Harald Elias",male,4
25,3,0,"Andersson, Miss. Ebba Iris Alfrida",female,6
26,3,0,"Andersson, Miss. Ellis Anna Maria",female,2
27,3,1,"Andersson, Miss. Erna Alexandra",female,17

## 🙋‍♀️ 4. Visualizar las primeras 5 personas
Usamos `head()` para ver las primeras filas del DataFrame y enfocarnos en un subconjunto de datos.

In [4]:
primeras_5_personas = titanic.head()
primeras_5_personas

,clase_pasajero,sobrevivio,nombre,sexo,edad
0,1,1,"Allen, Miss. Elisabeth Walton",female,29
1,1,1,"Astor, Mrs. John Jacob (Madeleine Talmadge Force)",female,18
2,1,1,"Aubart, Mme. Leontine Pauline",female,24
3,1,1,"Barber, Miss. Ellen 'Nellie'",female,26
4,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80

## ✅ 5. Crear una serie booleana para identificar mujeres
Creamos una condición que evalúa si la columna `sexo` es igual a `'female'`. Devuelve una serie booleana de `True` o `False`.

In [5]:
mujeres = primeras_5_personas["sexo"] == "female"
mujeres

0     True
1     True
2     True
3     True
4    False
Name: sexo, dtype: bool

## 🔄 6. Crear la negación con `~`
Usamos `~` para negar la serie booleana anterior, invirtiendo `True` por `False` y viceversa.

In [6]:
~mujeres

0    False
1    False
2    False
3    False
4     True
Name: sexo, dtype: bool

## 👨 7. Filtrar personas que **no sean mujeres**
Aplicamos la negación para mostrar a quienes **no** sean de sexo femenino (es decir, los hombres).

In [7]:
primeras_5_personas[~mujeres]

,clase_pasajero,sobrevivio,nombre,sexo,edad
4,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80

## ❌ 8. Filtrar pasajeros que **no sobrevivieron** y **no eran de primera clase**
Combinamos dos condiciones negadas:
- Que **no sobrevivieron** (`~sobrevivieron`)
- Que **no viajaban en primera clase** (`~primera_clase`)

Usamos el operador `&` para aplicar ambas condiciones al mismo tiempo.

In [8]:
# Condición: pasajeros que sobrevivieron
sobrevivieron = titanic["sobrevivio"] == 1

# Condición: pasajeros de primera clase
primera_clase = titanic["clase_pasajero"] == 1

# Negación de ambas condiciones combinadas
titanic[ ~sobrevivieron & ~primera_clase ]

,clase_pasajero,sobrevivio,nombre,sexo,edad
8,2,0,"Parker, Mr. Clifford Richard",male,28
10,2,0,"Pengelly, Mr. Frederick William",male,19
11,2,0,"Peruschitz, Rev. Joseph Maria",male,41
14,2,0,"Phillips, Mr. Escott Robert",male,43
16,2,0,"Ponesell, Mr. Martin",male,34
17,3,0,"Abbing, Mr. Anthony",male,42
18,3,0,"Abbott, Master. Eugene Joseph",male,13
19,3,0,"Abbott, Mr. Rossmore Edward",male,16
22,3,0,"Andersen, Mr. Albert Karvin",male,32
24,3,0,"Andersson, Master. Sigvard Harald Elias",male,4
25,3,0,"Andersson, Miss. Ebba Iris Alfrida",female,6
26,3,0,"Andersson, Miss. Ellis Anna Maria",female,2