# 📺 Filtrado de datos usando el operador OR (|). Títulos de Netflix

📥 **Importamos la librería `pandas`** para poder trabajar con datos en forma de tabla (DataFrames).

In [1]:
import pandas as pd

📄 **Leemos el archivo CSV** que contiene los títulos disponibles en Netflix.

In [2]:
netflix = pd.read_csv("data/titulos_netflix.csv")

🔍 **Visualizamos los últimos registros** del DataFrame para conocer su estructura y contenido.

In [3]:
netflix.tail()

,show_id,tipo,título,director,año_lanzamiento,clasificación,duración
8802,s8803,Movie,Zodiac,David Fincher,2007,R,158 min
8803,s8804,TV Show,Zombie Dumb,NaN,2018,TV-Y7,2 Seasons
8804,s8805,Movie,Zombieland,Ruben Fleischer,2009,R,88 min
8805,s8806,Movie,Zoom,Peter Hewitt,2006,PG,88 min
8806,s8807,Movie,Zubaan,Mozez Singh,2015,TV-14,111 min

🎬 **Filtramos los títulos que son películas o que tienen clasificación PG-13** usando el operador `|` (OR).

In [4]:
# Mostrar los programas de Netflix que sean películas o cuya clasificación sea PG-13
peliculas = netflix["tipo"] == "Movie"
clasificacion_pg_13 = netflix["clasificación"] == "PG-13"
netflix[peliculas | clasificacion_pg_13]

,show_id,tipo,título,director,año_lanzamiento,clasificación,duración
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,2020,PG-13,90 min
6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha",2021,PG,91 min
7,s8,Movie,Sankofa,Haile Gerima,1993,TV-MA,125 min
9,s10,Movie,The Starling,Theodore Melfi,2021,PG-13,104 min
12,s13,Movie,Je Suis Karl,Christian Schwochow,2021,TV-MA,127 min
...,...,...,...,...,...,...,...
8801,s8802,Movie,Zinzana,Majid Al Ansari,2015,TV-MA,96 min
8802,s8803,Movie,Zodiac,David Fincher,2007,R,158 min
8804,s8805,Movie,Zombieland,Ruben Fleischer,2009,R,88 min
8805,s8806,Movie,Zoom,Peter Hewitt,2006,PG,88 min
8806,s8807,Movie,Zubaan,Mozez Singh,2015,TV-14,111 min

📅 **Filtramos los mismos programas anteriores pero ahora los ordenamos por año de lanzamiento** para ver cómo han cambiado con el tiempo.

In [5]:
peliculas = netflix["tipo"] == "Movie"
clasificacion_pg_13 = netflix["clasificación"] == "PG-13"
programas = netflix[peliculas | clasificacion_pg_13]
programas.sort_values("año_lanzamiento")

,show_id,tipo,título,director,año_lanzamiento,clasificación,duración
7790,s7791,Movie,Prelude to War,Frank Capra,1942,TV-14,52 min
8205,s8206,Movie,The Battle of Midway,John Ford,1942,TV-14,18 min
8660,s8661,Movie,Undercover: How to Operate Behind Enemy Lines,John Ford,1943,TV-PG,61 min
8763,s8764,Movie,WWII: Report from the Aleutians,John Huston,1943,TV-PG,45 min
8739,s8740,Movie,Why We Fight: The Battle of Russia,"Frank Capra, Anatole Litvak",1943,TV-PG,82 min
...,...,...,...,...,...,...,...
1420,s1421,Movie,"Crack: Cocaine, Corruption & Conspiracy",Stanley Nelson,2021,TV-MA,90 min
373,s374,Movie,The Last Mercenary,David Charhon,2021,TV-MA,112 min
1424,s1425,Movie,Charming,Ross Venokur,2021,TV-Y7,85 min
372,s373,Movie,Rurouni Kenshin: The Beginning,Keishi Otomo,2021,TV-MA,138 min
394,s395,Movie,African America,Muzi Mthembu,2021,TV-MA,97 min

🎥 **Filtramos los programas dirigidos por David Fincher o Martin Scorsese**, dos directores muy reconocidos.

In [6]:
david = netflix["director"] == "David Fincher"
martin = netflix["director"] == "Martin Scorsese"
netflix[ david | martin]

,show_id,tipo,título,director,año_lanzamiento,clasificación,duración
600,s601,Movie,The Game,David Fincher,1997,R,129 min
1358,s1359,Movie,Shutter Island,Martin Scorsese,2010,R,139 min
1595,s1596,Movie,MANK,David Fincher,2020,R,133 min
2632,s2633,Movie,No Direction Home: Bob Dylan,Martin Scorsese,2005,TV-MA,208 min
2860,s2861,Movie,Hugo,Martin Scorsese,2011,PG,127 min
3227,s3228,Movie,The Irishman,Martin Scorsese,2019,R,209 min
3759,s3760,Movie,Rolling Thunder Revue: A Bob Dylan Story by Ma...,Martin Scorsese,2019,TV-MA,142 min
6111,s6112,Movie,Alice Doesn't Live Here Anymore,Martin Scorsese,1974,PG,112 min
6826,s6827,Movie,Gangs of New York,Martin Scorsese,2002,R,167 min
6880,s6881,Movie,GoodFellas,Martin Scorsese,1990,R,145 min
7431,s7432,Movie,Mean Streets,Martin Scorsese,1973,R,112 min
7701,s7702,Movie,Panic Room,David Fincher,2002,R,112 min
7820,s7821,Movie,Raging Bull,Martin Scorsese,1980,R,129 min
8272,s8273,Movie,The Departed,Martin Scorsese,2006,R,151 min
8320,s8321,Movie,The Girl with the Dragon Tattoo,David Fincher,2011,R,158 min
8511,s8512,Movie,The Social Network,David Fincher,2010,PG-13,121 min
8735,s8736,Movie,Who's That Knocking at My Door?,Martin Scorsese,1967,R,90 min
8802,s8803,Movie,Zodiac,David Fincher,2007,R,158 min

🔤 **Mostramos los mismos programas pero ahora ordenados por título** para una mejor organización alfabética.

In [7]:
david = netflix["director"] == "David Fincher"
martin = netflix["director"] == "Martin Scorsese"
netflix[ david | martin].sort_values("título")

,show_id,tipo,título,director,año_lanzamiento,clasificación,duración
6111,s6112,Movie,Alice Doesn't Live Here Anymore,Martin Scorsese,1974,PG,112 min
6826,s6827,Movie,Gangs of New York,Martin Scorsese,2002,R,167 min
6880,s6881,Movie,GoodFellas,Martin Scorsese,1990,R,145 min
2860,s2861,Movie,Hugo,Martin Scorsese,2011,PG,127 min
1595,s1596,Movie,MANK,David Fincher,2020,R,133 min
7431,s7432,Movie,Mean Streets,Martin Scorsese,1973,R,112 min
2632,s2633,Movie,No Direction Home: Bob Dylan,Martin Scorsese,2005,TV-MA,208 min
7701,s7702,Movie,Panic Room,David Fincher,2002,R,112 min
7820,s7821,Movie,Raging Bull,Martin Scorsese,1980,R,129 min
3759,s3760,Movie,Rolling Thunder Revue: A Bob Dylan Story by Ma...,Martin Scorsese,2019,TV-MA,142 min
1358,s1359,Movie,Shutter Island,Martin Scorsese,2010,R,139 min
8272,s8273,Movie,The Departed,Martin Scorsese,2006,R,151 min
600,s601,Movie,The Game,David Fincher,1997,R,129 min
8320,s8321,Movie,The Girl with the Dragon Tattoo,David Fincher,2011,R,158 min
3227,s3228,Movie,The Irishman,Martin Scorsese,2019,R,209 min
8511,s8512,Movie,The Social Network,David Fincher,2010,PG-13,121 min
8735,s8736,Movie,Who's That Knocking at My Door?,Martin Scorsese,1967,R,90 min
8802,s8803,Movie,Zodiac,David Fincher,2007,R,158 min

📆 **Filtramos los programas dirigidos por Fincher o Scorsese que fueron lanzados después de 2015**. ¡Veamos sus obras más recientes!

In [8]:
david = netflix["director"] == "David Fincher"
martin = netflix["director"] == "Martin Scorsese"
anio_lanzamiento = netflix["año_lanzamiento"] > 2015
netflix[ (david | martin) & anio_lanzamiento ]

,show_id,tipo,título,director,año_lanzamiento,clasificación,duración
1595,s1596,Movie,MANK,David Fincher,2020,R,133 min
3227,s3228,Movie,The Irishman,Martin Scorsese,2019,R,209 min
3759,s3760,Movie,Rolling Thunder Revue: A Bob Dylan Story by Ma...,Martin Scorsese,2019,TV-MA,142 min

✅ **¡Listo! Hemos practicado cómo filtrar datos usando el operador OR (`|`) en Pandas con ejemplos de títulos de Netflix.**