# 🔍 Filtrado de datos usando Series Booleanas
Aprenderemos a usar condiciones simples para filtrar registros en un DataFrame utilizando pandas 🐼.

### 📥 1. Importar la librería pandas
Usamos pandas para manejar datos en forma de tablas (DataFrames).

In [1]:
import pandas as pd

### 📄 2. Cargar el archivo CSV del Titanic
Leemos el archivo `titanic_v5.csv` con los datos de los pasajeros 🛳️.

In [2]:
titanic = pd.read_csv("data/titanic_v5.csv")

### 👀 3. Visualizar el DataFrame completo
Veamos una vista general del conjunto de datos cargado.

In [3]:
titanic

,clase_pasajero,sobrevivio,nombre,sexo,edad
0,1,1,"Allen, Miss. Elisabeth Walton",female,29
1,1,1,"Astor, Mrs. John Jacob (Madeleine Talmadge Force)",female,18
2,1,1,"Aubart, Mme. Leontine Pauline",female,24
3,1,1,"Barber, Miss. Ellen 'Nellie'",female,26
4,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80
5,1,0,"Baxter, Mr. Quigg Edmond",male,24
6,1,1,"Baxter, Mrs. James (Helene DeLaudeniere Chaput)",female,50
7,1,1,"Bazzani, Miss. Albina",female,32
8,2,0,"Parker, Mr. Clifford Richard",male,28
9,2,1,"Parrish, Mrs. (Lutie Davis)",female,50
10,2,0,"Pengelly, Mr. Frederick William",male,19
11,2,0,"Peruschitz, Rev. Joseph Maria",male,41
12,2,1,"Phillips, Miss. Alice Frances Louisa",female,21
13,2,1,"Phillips, Miss. Kate Florence ('Mrs Kate Louis...",female,19
14,2,0,"Phillips, Mr. Escott Robert",male,43
15,2,1,"Pinsky, Mrs. (Rosa)",female,32
16,2,0,"Ponesell, Mr. Martin",male,34
17,3,0,"Abbing, Mr. Anthony",male,42
18,3,0,"Abbott, Master. Eugene Joseph",male,13
19,3,0,"Abbott, Mr. Rossmore Edward",male,16
20,3,1,"Abbott, Mrs. Stanton (Rosa Hunt)",female,35
21,3,1,"Abelseth, Miss. Karen Marie",female,16
22,3,0,"Andersen, Mr. Albert Karvin",male,32
23,3,1,"Andersen-Jensen, Miss. Carla Christine Nielsine",female,19
24,3,0,"Andersson, Master. Sigvard Harald Elias",male,4
25,3,0,"Andersson, Miss. Ebba Iris Alfrida",female,6
26,3,0,"Andersson, Miss. Ellis Anna Maria",female,2
27,3,1,"Andersson, Miss. Erna Alexandra",female,17

### 🙋‍♀️ 4. Visualizar la columna `sexo`
Mostramos solo los valores de la columna `sexo` para entender su contenido.

In [4]:
titanic["sexo"]

0     female
1     female
2     female
3     female
4       male
5       male
6     female
7     female
8       male
9     female
10      male
11      male
12    female
13    female
14      male
15    female
16      male
17      male
18      male
19      male
20    female
21    female
22      male
23    female
24      male
25    female
26    female
27    female
Name: sexo, dtype: object

### ✅ 5. Crear una serie booleana: mujeres
Esto devuelve `True` o `False` dependiendo si el valor es `"female"`.

In [5]:
titanic["sexo"] == "female"

0      True
1      True
2      True
3      True
4     False
5     False
6      True
7      True
8     False
9      True
10    False
11    False
12     True
13     True
14    False
15     True
16    False
17    False
18    False
19    False
20     True
21     True
22    False
23     True
24    False
25     True
26     True
27     True
Name: sexo, dtype: bool

### 👩 6. Filtrar mujeres pasajeras
Usamos la condición booleana anterior para mostrar solo a las mujeres.

In [6]:
# Mostrar a las personas de sexo femenino ("female")
titanic[titanic["sexo"] == "female"]

,clase_pasajero,sobrevivio,nombre,sexo,edad
0,1,1,"Allen, Miss. Elisabeth Walton",female,29
1,1,1,"Astor, Mrs. John Jacob (Madeleine Talmadge Force)",female,18
2,1,1,"Aubart, Mme. Leontine Pauline",female,24
3,1,1,"Barber, Miss. Ellen 'Nellie'",female,26
6,1,1,"Baxter, Mrs. James (Helene DeLaudeniere Chaput)",female,50
7,1,1,"Bazzani, Miss. Albina",female,32
9,2,1,"Parrish, Mrs. (Lutie Davis)",female,50
12,2,1,"Phillips, Miss. Alice Frances Louisa",female,21
13,2,1,"Phillips, Miss. Kate Florence ('Mrs Kate Louis...",female,19
15,2,1,"Pinsky, Mrs. (Rosa)",female,32
20,3,1,"Abbott, Mrs. Stanton (Rosa Hunt)",female,35
21,3,1,"Abelseth, Miss. Karen Marie",female,16
23,3,1,"Andersen-Jensen, Miss. Carla Christine Nielsine",female,19
25,3,0,"Andersson, Miss. Ebba Iris Alfrida",female,6
26,3,0,"Andersson, Miss. Ellis Anna Maria",female,2
27,3,1,"Andersson, Miss. Erna Alexandra",female,17

### ❌ 7. Filtrar pasajeros que no sobrevivieron
Filtramos las filas donde la columna `sobrevivio` es igual a 0.

In [7]:
# Mostrar los pasajeros que no sobrevivieron
titanic[titanic["sobrevivio"] == 0]

,clase_pasajero,sobrevivio,nombre,sexo,edad
5,1,0,"Baxter, Mr. Quigg Edmond",male,24
8,2,0,"Parker, Mr. Clifford Richard",male,28
10,2,0,"Pengelly, Mr. Frederick William",male,19
11,2,0,"Peruschitz, Rev. Joseph Maria",male,41
14,2,0,"Phillips, Mr. Escott Robert",male,43
16,2,0,"Ponesell, Mr. Martin",male,34
17,3,0,"Abbing, Mr. Anthony",male,42
18,3,0,"Abbott, Master. Eugene Joseph",male,13
19,3,0,"Abbott, Mr. Rossmore Edward",male,16
22,3,0,"Andersen, Mr. Albert Karvin",male,32
24,3,0,"Andersson, Master. Sigvard Harald Elias",male,4
25,3,0,"Andersson, Miss. Ebba Iris Alfrida",female,6
26,3,0,"Andersson, Miss. Ellis Anna Maria",female,2

### ✅ 8. Filtrar pasajeros que sobrevivieron
Ahora mostramos las filas donde `sobrevivio` es igual a 1.

In [8]:
# Mostrar los pasajeros que sobrevivieron
titanic[titanic["sobrevivio"] == 1]

,clase_pasajero,sobrevivio,nombre,sexo,edad
0,1,1,"Allen, Miss. Elisabeth Walton",female,29
1,1,1,"Astor, Mrs. John Jacob (Madeleine Talmadge Force)",female,18
2,1,1,"Aubart, Mme. Leontine Pauline",female,24
3,1,1,"Barber, Miss. Ellen 'Nellie'",female,26
4,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80
6,1,1,"Baxter, Mrs. James (Helene DeLaudeniere Chaput)",female,50
7,1,1,"Bazzani, Miss. Albina",female,32
9,2,1,"Parrish, Mrs. (Lutie Davis)",female,50
12,2,1,"Phillips, Miss. Alice Frances Louisa",female,21
13,2,1,"Phillips, Miss. Kate Florence ('Mrs Kate Louis...",female,19
15,2,1,"Pinsky, Mrs. (Rosa)",female,32
20,3,1,"Abbott, Mrs. Stanton (Rosa Hunt)",female,35
21,3,1,"Abelseth, Miss. Karen Marie",female,16
23,3,1,"Andersen-Jensen, Miss. Carla Christine Nielsine",female,19
27,3,1,"Andersson, Miss. Erna Alexandra",female,17

### 👶 9. Filtrar por edad específica (18 años)
Mostramos los registros donde la edad es exactamente 18.

In [9]:
# Mostrar a los pasajeros cuya edad sea 18
titanic[titanic["edad"] == 18]

,clase_pasajero,sobrevivio,nombre,sexo,edad
1,1,1,"Astor, Mrs. John Jacob (Madeleine Talmadge Force)",female,18

### ✈️ 10. Filtrar pasajeros que **no** viajaban en primera clase
Se muestran los pasajeros cuya clase no es igual a 1 (primera clase).

In [10]:
# Mostrar a los pasajeros que no iban en primera clase
titanic[titanic["clase_pasajero"] != 1]

,clase_pasajero,sobrevivio,nombre,sexo,edad
8,2,0,"Parker, Mr. Clifford Richard",male,28
9,2,1,"Parrish, Mrs. (Lutie Davis)",female,50
10,2,0,"Pengelly, Mr. Frederick William",male,19
11,2,0,"Peruschitz, Rev. Joseph Maria",male,41
12,2,1,"Phillips, Miss. Alice Frances Louisa",female,21
13,2,1,"Phillips, Miss. Kate Florence ('Mrs Kate Louis...",female,19
14,2,0,"Phillips, Mr. Escott Robert",male,43
15,2,1,"Pinsky, Mrs. (Rosa)",female,32
16,2,0,"Ponesell, Mr. Martin",male,34
17,3,0,"Abbing, Mr. Anthony",male,42
18,3,0,"Abbott, Master. Eugene Joseph",male,13
19,3,0,"Abbott, Mr. Rossmore Edward",male,16
20,3,1,"Abbott, Mrs. Stanton (Rosa Hunt)",female,35
21,3,1,"Abelseth, Miss. Karen Marie",female,16
22,3,0,"Andersen, Mr. Albert Karvin",male,32
23,3,1,"Andersen-Jensen, Miss. Carla Christine Nielsine",female,19
24,3,0,"Andersson, Master. Sigvard Harald Elias",male,4
25,3,0,"Andersson, Miss. Ebba Iris Alfrida",female,6
26,3,0,"Andersson, Miss. Ellis Anna Maria",female,2
27,3,1,"Andersson, Miss. Erna Alexandra",female,17