# 🎬 Filtrado de datos: Condición simple, `between`, `isin`
Exploraremos cómo filtrar datos en un DataFrame de Netflix usando condiciones simples, rangos de años (`between`) y listas de valores (`isin`).

📥 **Importamos la librería `pandas`** para trabajar con DataFrames.

In [1]:
import pandas as pd

📄 **Cargamos el archivo CSV** que contiene los títulos de Netflix.

In [2]:
netflix = pd.read_csv("data/titulos_netflix.csv")

👀 **Mostramos todo el DataFrame** para conocer su estructura y columnas disponibles.

In [3]:
netflix

,show_id,tipo,título,director,año_lanzamiento,clasificación,duración
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,2020,PG-13,90 min
1,s2,TV Show,Blood & Water,NaN,2021,TV-MA,2 Seasons
2,s3,TV Show,Ganglands,Julien Leclercq,2021,TV-MA,1 Season
3,s4,TV Show,Jailbirds New Orleans,NaN,2021,TV-MA,1 Season
4,s5,TV Show,Kota Factory,NaN,2021,TV-MA,2 Seasons
...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,2007,R,158 min
8803,s8804,TV Show,Zombie Dumb,NaN,2018,TV-Y7,2 Seasons
8804,s8805,Movie,Zombieland,Ruben Fleischer,2009,R,88 min
8805,s8806,Movie,Zoom,Peter Hewitt,2006,PG,88 min
8806,s8807,Movie,Zubaan,Mozez Singh,2015,TV-14,111 min

📅 **Filtramos las películas que se lanzaron después de 2018** usando una condición simple (`>`).

In [4]:
netflix[netflix["año_lanzamiento"] > 2018]

,show_id,tipo,título,director,año_lanzamiento,clasificación,duración
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,2020,PG-13,90 min
1,s2,TV Show,Blood & Water,NaN,2021,TV-MA,2 Seasons
2,s3,TV Show,Ganglands,Julien Leclercq,2021,TV-MA,1 Season
3,s4,TV Show,Jailbirds New Orleans,NaN,2021,TV-MA,1 Season
4,s5,TV Show,Kota Factory,NaN,2021,TV-MA,2 Seasons
...,...,...,...,...,...,...,...
8516,s8517,Movie,The Spy Who Fell to Earth,Thomas Meadmore,2019,TV-MA,94 min
8631,s8632,Movie,Trixie Mattel: Moving Parts,Nicholas Zeig-Owens,2019,TV-MA,91 min
8718,s8719,Movie,Westside vs. the World,Michael Fahey,2019,TV-MA,96 min
8752,s8753,Movie,Wish Man,Theo Davies,2019,TV-14,108 min
8756,s8757,Movie,Woodstock,Barak Goodman,2019,TV-MA,97 min

🎥 **Películas lanzadas en 2020 o después** usando la condición `>=`.

In [5]:
netflix[netflix["año_lanzamiento"] >= 2020]

,show_id,tipo,título,director,año_lanzamiento,clasificación,duración
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,2020,PG-13,90 min
1,s2,TV Show,Blood & Water,NaN,2021,TV-MA,2 Seasons
2,s3,TV Show,Ganglands,Julien Leclercq,2021,TV-MA,1 Season
3,s4,TV Show,Jailbirds New Orleans,NaN,2021,TV-MA,1 Season
4,s5,TV Show,Kota Factory,NaN,2021,TV-MA,2 Seasons
...,...,...,...,...,...,...,...
7594,s7595,Movie,Norm of the North: Family Vacation,Anthony Bell,2020,TV-Y7,89 min
8099,s8100,Movie,Straight Up,James Sweeney,2020,TV-MA,96 min
8125,s8126,TV Show,Super Wings,NaN,2020,TV-Y,3 Seasons
8132,s8133,TV Show,Surviving R. Kelly Part II: The Reckoning,NaN,2020,TV-MA,1 Season
8437,s8438,TV Show,The Netflix Afterparty,NaN,2021,TV-MA,1 Season

📼 **Películas más antiguas**: lanzadas **antes del año 2000**.

In [6]:
netflix[netflix["año_lanzamiento"] < 2000]

,show_id,tipo,título,director,año_lanzamiento,clasificación,duración
7,s8,Movie,Sankofa,Haile Gerima,1993,TV-MA,125 min
22,s23,Movie,Avvai Shanmughi,K.S. Ravikumar,1996,TV-PG,161 min
24,s25,Movie,Jeans,S. Shankar,1998,TV-14,166 min
26,s27,Movie,Minsara Kanavu,Rajiv Menon,1997,TV-PG,147 min
41,s42,Movie,Jaws,Steven Spielberg,1975,PG,124 min
...,...,...,...,...,...,...,...
8745,s8746,Movie,Willy Wonka & the Chocolate Factory,Mel Stuart,1971,G,100 min
8748,s8749,Movie,Winter of Our Dreams,John Duigan,1981,NR,86 min
8763,s8764,Movie,WWII: Report from the Aleutians,John Huston,1943,TV-PG,45 min
8764,s8765,Movie,Wyatt Earp,Lawrence Kasdan,1994,PG-13,191 min
8792,s8793,Movie,Young Tiger,Mu Chu,1973,NR,81 min

📆 **Películas entre 2000 y 2005**, incluyendo ambos extremos. Utilizamos `.between()` para mayor legibilidad.

In [7]:
netflix[netflix["año_lanzamiento"].between(2000, 2005)]

,show_id,tipo,título,director,año_lanzamiento,clasificación,duración
48,s49,Movie,Training Day,Antoine Fuqua,2001,R,122 min
51,s52,Movie,InuYasha the Movie 2: The Castle Beyond the Lo...,Toshiya Shinohara,2002,TV-14,99 min
52,s53,Movie,InuYasha the Movie 3: Swords of an Honorable R...,Toshiya Shinohara,2003,TV-14,99 min
53,s54,Movie,InuYasha the Movie 4: Fire on the Mystic Island,Toshiya Shinohara,2004,TV-PG,88 min
54,s55,Movie,InuYasha the Movie: Affections Touching Across...,Toshiya Shinohara,2001,TV-PG,100 min
...,...,...,...,...,...,...,...
8766,s8767,Movie,XXx,Rob Cohen,2002,PG-13,124 min
8767,s8768,Movie,XXX: State of the Union,Lee Tamahori,2005,PG-13,101 min
8768,s8769,Movie,Y Tu Mamá También,Alfonso Cuarón,2001,R,106 min
8770,s8771,Movie,Yaadein,Subhash Ghai,2001,TV-14,171 min
8793,s8794,Movie,"Yours, Mine and Ours",Raja Gosnell,2005,PG,88 min

🎬 **Filtramos las películas dirigidas por ciertos directores** usando `isin()` con una lista de nombres.

In [8]:
directores =["Alfonso Cuarón","Tim Burton", "Steven Spielberg"]
netflix[netflix['director'].isin(directores)]

,show_id,tipo,título,director,año_lanzamiento,clasificación,duración
41,s42,Movie,Jaws,Steven Spielberg,1975,PG,124 min
161,s162,Movie,Mars Attacks!,Tim Burton,1996,PG-13,106 min
329,s330,Movie,Catch Me If You Can,Steven Spielberg,2002,PG-13,142 min
1203,s1204,Movie,The BFG,Steven Spielberg,2016,PG,118 min
4306,s4307,Movie,ROMA,Alfonso Cuarón,2018,R,135 min
6446,s6447,Movie,Charlie and the Chocolate Factory,Tim Burton,2005,PG,115 min
7070,s7071,Movie,Indiana Jones and the Kingdom of the Crystal S...,Steven Spielberg,2008,PG-13,123 min
7071,s7072,Movie,Indiana Jones and the Last Crusade,Steven Spielberg,1989,PG-13,127 min
7072,s7073,Movie,Indiana Jones and the Raiders of the Lost Ark,Steven Spielberg,1981,PG,116 min
7073,s7074,Movie,Indiana Jones and the Temple of Doom,Steven Spielberg,1984,PG,119 min
7308,s7309,Movie,Lincoln,Steven Spielberg,2012,PG-13,150 min
7957,s7958,Movie,Schindler's List,Steven Spielberg,1993,R,195 min
8050,s8051,Movie,Solo Con Tu Pareja,Alfonso Cuarón,1991,NR,94 min
8138,s8139,Movie,Sweeney Todd: The Demon Barber of Fleet Street,Tim Burton,2007,R,116 min
8184,s8185,Movie,The Adventures of Tintin,Steven Spielberg,2011,PG,107 min
8696,s8697,Movie,War Horse,Steven Spielberg,2011,PG-13,147 min
8768,s8769,Movie,Y Tu Mamá También,Alfonso Cuarón,2001,R,106 min

📊 **Contamos cuántas películas tiene cada uno de estos directores**.

In [9]:
netflix[netflix['director'].isin(directores)]['director'].value_counts()

Steven Spielberg    11
Tim Burton           3
Alfonso Cuarón       3
Name: director, dtype: int64

🔞 **Filtramos películas con clasificación para adultos**: "TV-MA", "R" y "NR".

In [10]:
adultos = netflix["clasificación"].isin(["TV-MA", "R", "NR"])
netflix[adultos]

,show_id,tipo,título,director,año_lanzamiento,clasificación,duración
1,s2,TV Show,Blood & Water,NaN,2021,TV-MA,2 Seasons
2,s3,TV Show,Ganglands,Julien Leclercq,2021,TV-MA,1 Season
3,s4,TV Show,Jailbirds New Orleans,NaN,2021,TV-MA,1 Season
4,s5,TV Show,Kota Factory,NaN,2021,TV-MA,2 Seasons
5,s6,TV Show,Midnight Mass,Mike Flanagan,2021,TV-MA,1 Season
...,...,...,...,...,...,...,...
8792,s8793,Movie,Young Tiger,Mu Chu,1973,NR,81 min
8798,s8799,Movie,Zed Plus,Chandra Prakash Dwivedi,2014,TV-MA,131 min
8801,s8802,Movie,Zinzana,Majid Al Ansari,2015,TV-MA,96 min
8802,s8803,Movie,Zodiac,David Fincher,2007,R,158 min
8804,s8805,Movie,Zombieland,Ruben Fleischer,2009,R,88 min

📈 **Contamos cuántas películas hay por cada una de estas clasificaciones para adultos**.

In [11]:
netflix[adultos]['clasificación'].value_counts()

TV-MA    3207
R         799
NR         80
Name: clasificación, dtype: int64