# 📊 Filtrado de datos: Calificaciones

📥 **Importar datos:**
Vamos a leer un archivo CSV que contiene las calificaciones de varios alumnos. Veremos todo el DataFrame para entender su estructura.

In [1]:
import pandas as pd

In [2]:
calificaciones = pd.read_csv("data/calificaciones.csv")
calificaciones

    Alumnos  Parcial 1  Parcial 2  Parcial 3
0    Carlos         87         96         70
1       Eva        100         87         77
2       Sam         94         77         90
3  Catalina        100         81         82
4   Roberto         83         65         85

🔍 **Filtrar alumnos con más de 90 en el primer parcial:**
Utilizamos una condición para ver quiénes obtuvieron una calificación superior a 90 en el `Parcial 1`.

In [3]:
# Mostrar alumnos que sacaron más de 90 en el primer parcial
calificaciones[calificaciones['Parcial 1'] > 90]

    Alumnos  Parcial 1  Parcial 2  Parcial 3
1       Eva        100         87         77
2       Sam         94         77         90
3  Catalina        100         81         82

🧠 **Filtrar solo la columna de calificación:**
Aquí usamos una condición booleana para filtrar y mostrar únicamente las calificaciones del primer parcial que son mayores a 90.

In [4]:
print("Calificaciones del primer parcial que sean mayores que 90")
calificaciones_mayor_90 = calificaciones["Parcial 1"] > 90
# Mostrar solo la columna primer parcial
calificaciones[calificaciones_mayor_90]["Parcial 1"]

Calificaciones del primer parcial que sean mayores que 90

1    100
2     94
3    100
Name: Parcial 1, dtype: int64

🔍 **Filtrar por condición menor a 90 y mostrar dos columnas:**
En este caso mostramos las calificaciones del `Parcial 1` y `Parcial 2` solo de los alumnos que sacaron **menos de 90** en el primer parcial.

In [5]:
# Mostrar las calificaciones del primer y segundo parcial
# cuyo primer parcial sea menor a 90
califMenorA90 = calificaciones['Parcial 1'] < 90
columnas=["Parcial 1", "Parcial 2"]
calificaciones[califMenorA90][columnas]

   Parcial 1  Parcial 2
0         87         96
4         83         65

❌ **Filtrar los que no aprobaron el segundo parcial:**
Aquí seleccionamos a los alumnos que sacaron menos de 70 en el `Parcial 2`, asumiendo que 70 es la calificación mínima aprobatoria.

In [6]:
# Mostrar las calificaciones de los alumnos que no hayan
# aprobado el segundo parcial
menor70 = calificaciones['Parcial 2'] < 70  # condicion
calificaciones[menor70]

   Alumnos  Parcial 1  Parcial 2  Parcial 3
4  Roberto         83         65         85

✅ ¡Listo! Ahora ya sabes cómo filtrar datos en Pandas usando condiciones simples. Puedes adaptar estas técnicas para cualquier conjunto de datos similar. 💪📈