# 🧠 Uso de Apply( ), Map( ) y ApplyMap( )

📥 **Importamos la librería `pandas`** para trabajar con DataFrames.

In [1]:
import pandas as pd

📄 **Cargamos el archivo CSV del Titanic** y reemplazamos valores '?' por `None`, luego convertimos columnas a tipo `float`.

In [2]:
titanic = pd.read_csv("data/titanic.csv")
titanic["age"] = titanic["age"].replace(["?"], [None]).astype("float")
titanic["fare"] = titanic["fare"].replace(["?"], [None]).astype("float")

## The Series apply( ) method

### 📅 Convertir edades de años a días

Se define una función llamada `years_to_days()` que recibe una edad en años y la multiplica por **365** para obtener una aproximación de la edad en días.

```python
def years_to_days(yrs):
    return yrs * 365

titanic["age"].apply(years_to_days)

La función apply() aplica esta conversión a cada valor de la columna age, devolviendo una nueva serie con las edades expresadas en días. 🚢

In [3]:
def years_to_days(yrs):
    return yrs*365

titanic["age"].apply(years_to_days)

0       10585.0000
1         334.5955
2         730.0000
3       10950.0000
4        9125.0000
           ...
1304     5292.5000
1305           NaN
1306     9672.5000
1307     9855.0000
1308    10585.0000
Name: age, Length: 1309, dtype: float64

### 📅 Convertir edades de años a días usando operaciones vectorizadas

```python
titanic["age"] * 365

Esta expresión multiplica cada valor de la columna age por 365, obteniendo una estimación de la edad en días.

A diferencia de apply(), esta operación aprovecha las capacidades vectorizadas de Pandas, por lo que suele ser más rápida y sencilla cuando se realizan cálculos matemáticos sobre una columna completa. 🚢📊

In [4]:
titanic["age"] * 365

0       10585.0000
1         334.5955
2         730.0000
3       10950.0000
4        9125.0000
           ...
1304     5292.5000
1305           NaN
1306     9672.5000
1307     9855.0000
1308    10585.0000
Name: age, Length: 1309, dtype: float64

### 👥 Clasificar pasajeros por grupo de edad
Se define una función llamada get_age_group() que clasifica una edad en diferentes categorías:

👶 infant: menor de 2 años.
🧒 child: de 2 a 11 años.
🧑 teen: de 12 a 17 años.
👨 adult: de 18 a 49 años.
👴 senior: 50 años o más.

La función apply() se utiliza para aplicar esta clasificación a cada valor de la columna age, creando una nueva columna llamada age_group con el grupo de edad correspondiente para cada pasajero. 🚢

In [5]:
def get_age_group(age):
    if age < 2:
        return "infant"
    elif age < 12:
        return "child"
    elif age < 18:
        return "teen"
    elif age < 50:
        return "adult"
    else:
        return "senior"

In [6]:
titanic["age_group"] = titanic["age"].apply(get_age_group)

### 📊 Contar pasajeros por grupo de edad

El método `value_counts()` cuenta cuántas veces aparece cada categoría dentro de la columna `age_group`.

El resultado muestra el número de pasajeros que pertenecen a cada grupo de edad (`infant`, `child`, `teen`, `adult` y `senior`), ordenados desde el grupo más frecuente hasta el menos frecuente.

Esta operación es útil para analizar la distribución de edades de los pasajeros y conocer qué grupos de edad estaban más representados en el conjunto de datos del Titanic. 🚢👥

In [7]:
titanic.age_group.value_counts()

age_group
adult     782
senior    373
child      69
teen       63
infant     22
Name: count, dtype: int64

### 📊 Calcular la tasa de supervivencia por grupo de edad

Esta operación agrupa a los pasajeros según su grupo de edad (`age_group`) y calcula el promedio de la columna `survived` para cada grupo.

Como la columna `survived` suele contener valores de **1** (sobrevivió) y **0** (no sobrevivió), el promedio representa la proporción o porcentaje de pasajeros que sobrevivieron dentro de cada grupo de edad.

Este análisis permite comparar las tasas de supervivencia entre infantes, niños, adolescentes, adultos y personas mayores, ayudando a identificar posibles diferencias en las probabilidades de supervivencia según la edad. 🚢📈

In [8]:
titanic.groupby("age_group").survived.mean()

age_group
adult     0.386189
child     0.492754
infant    0.772727
senior    0.313673
teen      0.476190
Name: survived, dtype: float64

### 📊 Calcular la tasa de supervivencia por grupo de edad y sexo

Esta operación agrupa a los pasajeros utilizando dos criterios: el grupo de edad (`age_group`) y el sexo (`sex`). Posteriormente, calcula el promedio de la columna `survived` para cada combinación de categorías.

Dado que la columna `survived` contiene valores de **1** para los pasajeros que sobrevivieron y **0** para los que no sobrevivieron, el promedio obtenido representa la tasa de supervivencia de cada grupo.

Este análisis permite comparar las probabilidades de supervivencia entre hombres y mujeres dentro de cada grupo de edad, facilitando la identificación de patrones relacionados con la edad y el sexo de los pasajeros. 🚢👥📈

In [9]:
titanic.groupby(["age_group", "sex"]).survived.mean()

age_group  sex
adult      female    0.748201
           male      0.186508
child      female    0.515152
           male      0.472222
infant     female    0.888889
           male      0.692308
senior     female    0.698276
           male      0.140078
teen       female    0.833333
           male      0.151515
Name: survived, dtype: float64

# Apply con Lambdas

### 💰 Multiplicar la tarifa por 24

Esta operación multiplica cada valor de la columna `fare` por **24**, generando una nueva serie con los resultados.

Pandas realiza esta operación sobre todos los registros de forma vectorizada, aplicando la multiplicación a cada tarifa individual sin necesidad de utilizar ciclos o funciones adicionales.

El resultado puede utilizarse para realizar conversiones, estimaciones o cálculos derivados a partir de la tarifa original de cada pasajero. 🚢📊

In [10]:
titanic["fare"] * 24

0       5072.1000
1       3637.2000
2       3637.2000
3       3637.2000
4       3637.2000
          ...
1304     346.9008
1305     346.9008
1306     173.4000
1307     173.4000
1308     189.0000
Name: fare, Length: 1309, dtype: float64

🧪 **Usamos `apply()` con `lambda`** para aplicar una función personalizada a una columna.

### 💰 Formatear y transformar las tarifas

Esta operación aplica una función anónima (*lambda*) a cada valor de la columna `fare`.

Para cada tarifa, el valor se multiplica por **24** y posteriormente se convierte en una cadena de texto con el símbolo **$** al inicio.

El resultado es una nueva serie con las tarifas transformadas y formateadas como valores monetarios, lo que puede facilitar su visualización en reportes o tablas. 🚢💵

In [11]:
titanic["fare"].apply(lambda x: f"${x*24}")

0                   $5072.1
1       $3637.2000000000003
2       $3637.2000000000003
3       $3637.2000000000003
4       $3637.2000000000003
               ...
1304              $346.9008
1305              $346.9008
1306    $173.39999999999998
1307    $173.39999999999998
1308                 $189.0
Name: fare, Length: 1309, dtype: object

### 🔧 Definir una función para convertir y formatear valores monetarios

Esta función recibe dos parámetros: un número (`num`) y un multiplicador (`multiplier`).

El valor numérico se multiplica por el factor indicado y el resultado se devuelve como una cadena de texto con el símbolo **$** al inicio, simulando un formato monetario.

Esta función puede reutilizarse para realizar diferentes conversiones simplemente cambiando el valor del multiplicador, evitando repetir la misma lógica en varias partes del código. 💰📊

In [12]:
def convert_currency(num, multiplier):
    return f"${num*multiplier}"

### 💰 Aplicar una función personalizada con argumentos adicionales

Esta operación aplica la función `convert_currency()` a cada valor de la columna `fare`.

Además del valor de la tarifa, se envía un argumento adicional mediante `args`, indicando que cada tarifa debe multiplicarse por **24** antes de ser formateada como texto monetario.

El resultado es una nueva serie donde cada tarifa aparece convertida y precedida por el símbolo **$**. Este enfoque es útil cuando una función requiere más de un parámetro y se desea reutilizar con distintos valores de configuración. 🚢📊💵

In [13]:
titanic["fare"].apply(convert_currency, args=(24,))

0                   $5072.1
1       $3637.2000000000003
2       $3637.2000000000003
3       $3637.2000000000003
4       $3637.2000000000003
               ...
1304              $346.9008
1305              $346.9008
1306    $173.39999999999998
1307    $173.39999999999998
1308                 $189.0
Name: fare, Length: 1309, dtype: object

## Apply() w/ DataFrames: Columns

In [14]:
df = titanic[["pclass", "survived", "age", "fare"]]

In [15]:
df

      pclass  survived      age      fare
0          1         1  29.0000  211.3375
1          1         1   0.9167  151.5500
2          1         0   2.0000  151.5500
3          1         0  30.0000  151.5500
4          1         0  25.0000  151.5500
...      ...       ...      ...       ...
1304       3         0  14.5000   14.4542
1305       3         0      NaN   14.4542
1306       3         0  26.5000    7.2250
1307       3         0  27.0000    7.2250
1308       3         0  29.0000    7.8750

[1309 rows x 4 columns]

In [16]:
def get_range(s):
    return s.max() - s.min()

### 📊 Calcular el rango de cada columna

Esta operación aplica la función `get_range()` a cada columna del DataFrame.

La función obtiene el valor máximo y el valor mínimo de una columna, y luego calcula la diferencia entre ambos. Esta diferencia se conoce como **rango** y representa la amplitud de los datos.

El resultado es una serie donde cada valor indica cuánto varían los datos dentro de una columna, lo que permite comparar rápidamente la dispersión de las diferentes variables del conjunto de datos. 📈

In [17]:
df.apply(get_range)

pclass        2.0000
survived      1.0000
age          79.8333
fare        512.3292
dtype: float64

### 📊 Calcular el rango de cada columna

Esta operación aplica la función `get_range()` a lo largo de las columnas del DataFrame (`axis=0`).

Para cada columna, la función calcula la diferencia entre el valor máximo y el valor mínimo, obteniendo así el rango de los datos.

El resultado es una serie que muestra el rango de cada columna, permitiendo conocer la amplitud o variabilidad de los valores en cada variable del conjunto de datos. 📈

In [18]:
df.apply(get_range, axis=0)

pclass        2.0000
survived      1.0000
age          79.8333
fare        512.3292
dtype: float64

## Apply() w/ DataFrames: Rows

### 📊 Calcular el rango de cada fila

Esta operación aplica la función `get_range()` a lo largo de las filas del DataFrame (`axis=1`).

Para cada fila, se identifica el valor máximo y el valor mínimo entre sus columnas y se calcula la diferencia entre ambos. El resultado representa el rango de valores dentro de cada registro.

La salida es una serie donde cada valor corresponde al rango de una fila, lo que permite analizar la variación de los datos en cada observación del conjunto de datos. 📈

In [19]:
df.apply(get_range, axis=1)

0       210.3375
1       150.6333
2       151.5500
3       151.5500
4       151.5500
          ...
1304     14.5000
1305     14.4542
1306     26.5000
1307     27.0000
1308     29.0000
Length: 1309, dtype: float64

In [20]:
def get_fam_size(s):
    fam_size = s.sibsp + s.parch
    if fam_size == 0:
        return "solo"
    elif fam_size < 5:
        return "average"
    else:
        return "large"

### 👨‍👩‍👧‍👦 Clasificar pasajeros según el tamaño de su familia

Esta operación aplica la función `get_fam_size()` a cada fila del DataFrame (`axis=1`).

La función calcula el tamaño de la familia sumando los valores de las columnas `sibsp` (hermanos o cónyuges a bordo) y `parch` (padres o hijos a bordo). Con base en este total, asigna una categoría:

- 👤 `solo`: el pasajero viaja sin familiares.
- 👨‍👩‍👧 `average`: el pasajero viaja con una familia de tamaño pequeño o mediano.
- 👨‍👩‍👧‍👦‍👦 `large`: el pasajero viaja con una familia numerosa.

El resultado es una serie que indica la categoría de tamaño familiar correspondiente a cada pasajero del Titanic. 🚢

In [21]:
titanic.apply(get_fam_size, axis=1)

0          solo
1       average
2       average
3       average
4       average
         ...
1304    average
1305    average
1306       solo
1307       solo
1308       solo
Length: 1309, dtype: object

### 👨‍👩‍👧‍👦 Contar pasajeros según el tamaño de su familia

Primero se crea una nueva columna llamada `fam_size`, que almacena la categoría de tamaño familiar asignada a cada pasajero.

Posteriormente, se utiliza `value_counts()` para contar cuántos pasajeros pertenecen a cada categoría:

- 👤 `solo`: pasajeros que viajaban sin familiares.
- 👨‍👩‍👧 `average`: pasajeros que viajaban con una familia pequeña o mediana.
- 👨‍👩‍👧‍👦‍👦 `large`: pasajeros que viajaban con una familia numerosa.

El resultado muestra la cantidad de pasajeros en cada grupo, ordenados desde la categoría más frecuente hasta la menos frecuente. Este análisis permite comprender mejor cómo estaba distribuido el tamaño de las familias a bordo del Titanic. 🚢📊

In [22]:
titanic["fam_size"] = titanic.apply(get_fam_size, axis=1)

In [23]:
titanic["fam_size"].value_counts()

fam_size
solo       790
average    459
large       60
Name: count, dtype: int64

### 📊 Calcular la tasa de supervivencia según el tamaño de la familia

Esta operación agrupa a los pasajeros de acuerdo con la categoría de tamaño familiar almacenada en `fam_size` y calcula el promedio de la columna `survived` para cada grupo.

Como la columna `survived` contiene valores de **1** para los pasajeros que sobrevivieron y **0** para los que no sobrevivieron, el promedio representa la tasa de supervivencia de cada categoría familiar.

El resultado permite comparar las probabilidades de supervivencia entre pasajeros que viajaban solos, con familias pequeñas o medianas, y con familias numerosas, ayudando a identificar si el tamaño de la familia pudo influir en las posibilidades de sobrevivir al desastre del Titanic. 🚢👨‍👩‍👧‍👦📈

In [24]:
titanic.groupby("fam_size").survived.mean()

fam_size
average    0.549020
large      0.150000
solo       0.302532
Name: survived, dtype: float64

### 📊 Calcular la tasa de supervivencia según el tamaño de la familia y el sexo

Esta operación agrupa a los pasajeros utilizando dos criterios: la categoría de tamaño familiar (`fam_size`) y el sexo (`sex`). Luego, calcula el promedio de la columna `survived` para cada combinación de grupos.

Debido a que la columna `survived` contiene valores de **1** para los pasajeros que sobrevivieron y **0** para los que no sobrevivieron, el promedio obtenido representa la tasa de supervivencia de cada grupo.

Este análisis permite comparar las probabilidades de supervivencia entre hombres y mujeres que viajaban solos, con familias pequeñas o medianas, o con familias numerosas, facilitando la identificación de patrones relacionados con la composición familiar y el sexo de los pasajeros. 🚢👨‍👩‍👧‍👦👥📈

In [25]:
titanic.groupby(["fam_size", "sex"]).survived.mean()

fam_size  sex
average   female    0.771429
          male      0.294393
large     female    0.296296
          male      0.030303
solo      female    0.731959
          male      0.162752
Name: survived, dtype: float64

## The map( ) method

In [26]:
titanic["pclass"]

0       1
1       1
2       1
3       1
4       1
       ..
1304    3
1305    3
1306    3
1307    3
1308    3
Name: pclass, Length: 1309, dtype: int64

### 🚢 Convertir códigos de clase a etiquetas descriptivas

Esta operación utiliza `map()` para reemplazar los valores numéricos de la columna `pclass` por etiquetas más fáciles de interpretar.

Cada clase se transforma de la siguiente manera:

- 🥇 `1` → `1st`
- 🥈 `2` → `2nd`
- 🥉 `3` → `3rd`

El resultado es una nueva serie con nombres descriptivos en lugar de códigos numéricos, lo que facilita la lectura y el análisis de los datos. 📊

In [27]:
titanic["pclass"].map({1:"1st", 2:"2nd", 3:"3rd"})

0       1st
1       1st
2       1st
3       1st
4       1st
       ...
1304    3rd
1305    3rd
1306    3rd
1307    3rd
1308    3rd
Name: pclass, Length: 1309, dtype: object

### 👶 Identificar pasajeros menores de edad

Esta operación utiliza `map()` junto con una función anónima (*lambda*) para evaluar cada valor de la columna `age`.

Para cada edad, se verifica si es menor que **18 años**. El resultado es una serie de valores booleanos:

- ✅ `True`: el pasajero es menor de edad.
- ❌ `False`: el pasajero tiene 18 años o más.

Este tipo de transformación es útil para crear indicadores o filtros basados en una condición específica. 🚢📊

In [28]:
titanic["age"].map(lambda a: a < 18)

0       False
1        True
2        True
3       False
4       False
        ...
1304     True
1305    False
1306    False
1307    False
1308    False
Name: age, Length: 1309, dtype: bool

## The applymap( ) method

### 🔠 Convertir texto a mayúsculas en varias columnas

Esta operación aplica la función `str.upper()` a cada celda de las columnas seleccionadas.

Como resultado, todos los valores de texto se transforman a letras mayúsculas, incluyendo el nombre del pasajero, el sexo y el grupo de edad.

Este tipo de transformación es útil para estandarizar el formato de los datos, facilitando su lectura, comparación y presentación en reportes. 🚢📊🔤

In [29]:
titanic[["name", "sex", "age_group"]].applymap(str.upper)

/var/folders/v4/4ypzq9bd1q93lvm8pfcq5b1r0000gn/T/ipykernel_10999/3006038703.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  titanic[["name", "sex", "age_group"]].applymap(str.upper)

                                                 name     sex age_group
0                       ALLEN, MISS. ELISABETH WALTON  FEMALE     ADULT
1                      ALLISON, MASTER. HUDSON TREVOR    MALE    INFANT
2                        ALLISON, MISS. HELEN LORAINE  FEMALE     CHILD
3                ALLISON, MR. HUDSON JOSHUA CREIGHTON    MALE     ADULT
4     ALLISON, MRS. HUDSON J C (BESSIE WALDO DANIELS)  FEMALE     ADULT
...                                               ...     ...       ...
1304                             ZABOUR, MISS. HILENI  FEMALE      TEEN
1305                            ZABOUR, MISS. THAMINE  FEMALE    SENIOR
1306                        ZAKARIAN, MR. MAPRIEDEDER    MALE     ADULT
1307                              ZAKARIAN, MR. ORTIN    MALE     ADULT
1308                               ZIMMERMAN, MR. LEO    MALE     ADULT

[1309 rows x 3 columns]

### ✖️ Multiplicar cada elemento del DataFrame

Esta operación aplica una función a cada celda del DataFrame y multiplica su valor por **7**.

El resultado es un nuevo DataFrame con la misma estructura que el original, pero con todos sus elementos escalados por ese factor.

Este tipo de transformación es útil cuando se necesita realizar el mismo cálculo sobre todos los valores de un conjunto de datos de forma uniforme. 📊✨

> ⚠️ En versiones recientes de Pandas, `DataFrame.applymap()` ha sido marcado como obsoleto (*deprecated*). Se recomienda utilizar `DataFrame.map()` cuando se desee aplicar una función elemento por elemento.

In [30]:
df.applymap(lambda el: el * 7)

/var/folders/v4/4ypzq9bd1q93lvm8pfcq5b1r0000gn/T/ipykernel_10999/3862018355.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(lambda el: el * 7)

      pclass  survived       age       fare
0          7         7  203.0000  1479.3625
1          7         7    6.4169  1060.8500
2          7         0   14.0000  1060.8500
3          7         0  210.0000  1060.8500
4          7         0  175.0000  1060.8500
...      ...       ...       ...        ...
1304      21         0  101.5000   101.1794
1305      21         0       NaN   101.1794
1306      21         0  185.5000    50.5750
1307      21         0  189.0000    50.5750
1308      21         0  203.0000    55.1250

[1309 rows x 4 columns]

In [31]:
df * 7

      pclass  survived       age       fare
0          7         7  203.0000  1479.3625
1          7         7    6.4169  1060.8500
2          7         0   14.0000  1060.8500
3          7         0  210.0000  1060.8500
4          7         0  175.0000  1060.8500
...      ...       ...       ...        ...
1304      21         0  101.5000   101.1794
1305      21         0       NaN   101.1794
1306      21         0  185.5000    50.5750
1307      21         0  189.0000    50.5750
1308      21         0  203.0000    55.1250

[1309 rows x 4 columns]

### 📏 Calcular la longitud de los textos

Esta operación aplica la función `len()` a cada celda de las columnas seleccionadas.

El resultado es un nuevo DataFrame donde cada valor representa la cantidad de caracteres del texto original:

- 👤 `name`: número de caracteres del nombre del pasajero.
- 🚻 `sex`: número de caracteres de la categoría de sexo.
- 👥 `age_group`: número de caracteres de la categoría de edad.

Este tipo de transformación puede ser útil para analizar la longitud de los textos o generar métricas basadas en la cantidad de caracteres. 📊🔤

> ⚠️ En versiones recientes de Pandas, `DataFrame.applymap()` ha sido marcado como obsoleto (*deprecated*). Se recomienda utilizar `DataFrame.map()` para aplicar funciones elemento por elemento.

In [32]:
titanic[["name", "sex", "age_group"]].applymap(len)

/var/folders/v4/4ypzq9bd1q93lvm8pfcq5b1r0000gn/T/ipykernel_10999/323004148.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  titanic[["name", "sex", "age_group"]].applymap(len)

      name  sex  age_group
0       29    6          5
1       30    4          6
2       28    6          5
3       36    4          5
4       47    6          5
...    ...  ...        ...
1304    20    6          4
1305    21    6          6
1306    25    4          5
1307    19    4          5
1308    18    4          5

[1309 rows x 3 columns]