# 🔗 Combinación de DataFrames y Series

### 📚 Usando `pd.concat()` con Series

In [1]:
import pandas as pd

In [2]:
s1 = pd.Series(['a', 'b', 'c'])
s2 = pd.Series(['d', 'e', 'f', 'z'])

In [3]:
pd.concat([s1,s2])

0    a
1    b
2    c
0    d
1    e
2    f
3    z
dtype: object

### 🔗 Concatenar dos Series

Esta operación utiliza `pd.concat()` para unir las series `s2` y `s1` en una sola estructura.

Los elementos de `s2` se colocan primero y, a continuación, se agregan los elementos de `s1`, conservando sus índices originales.

El resultado es una nueva serie que contiene todos los valores de ambas series, permitiendo combinar datos que se encuentran separados en distintas estructuras. 📊🔗

In [4]:
pd.concat([s2, s1])

0    d
1    e
2    f
3    z
0    a
1    b
2    c
dtype: object

### 🔗 Concatenar dos Series y reiniciar los índices

Esta operación utiliza `pd.concat()` para unir las series `s2` y `s1` en una sola serie.

A diferencia de la concatenación estándar, el parámetro `ignore_index=True` hace que Pandas ignore los índices originales de ambas series y genere nuevos índices consecutivos comenzando desde **0**.

El resultado es una serie combinada con una numeración continua, lo que puede facilitar el trabajo con los datos cuando los índices originales ya no son necesarios. 📊🔢

In [5]:
pd.concat([s2, s1], ignore_index=True)

0    d
1    e
2    f
3    z
4    a
5    b
6    c
dtype: object

In [6]:
nums = pd.Series([65,69,99,23,56,54])
nums2 = pd.Series([11,111,1111])

### 🔗 Concatenar múltiples Series y reiniciar los índices

Esta operación utiliza `pd.concat()` para unir las series `s2`, `s1` y `nums` en una sola serie.

El parámetro `ignore_index=True` indica que los índices originales deben descartarse y reemplazarse por una nueva secuencia de índices consecutivos que comienza en **0**.

El resultado es una única serie que contiene todos los valores de las tres series en el orden en que fueron proporcionadas, facilitando el manejo de los datos como una sola colección continua. 📊🔢

In [7]:
pd.concat([s2, s1, nums], ignore_index=True)

0      d
1      e
2      f
3      z
4      a
5      b
6      c
7     65
8     69
9     99
10    23
11    56
12    54
dtype: object

In [8]:
pd.concat([nums, nums2, s1], ignore_index=True)

0       65
1       69
2       99
3       23
4       56
5       54
6       11
7      111
8     1111
9        a
10       b
11       c
dtype: object

### 📚 Usando `pd.concat()` con Series by Index

In [9]:
c1 = pd.Series(["red", "orange", "yellow"])
c2 = pd.Series(["green", "blue", "purple"])

In [10]:
pd.concat([c1,c2])

0       red
1    orange
2    yellow
0     green
1      blue
2    purple
dtype: object

### 📊 Concatenar Series por columnas

Esta operación utiliza `pd.concat()` para combinar las series `c1` y `c2` horizontalmente mediante `axis=1`.

En lugar de agregar los valores uno debajo de otro, las series se colocan lado a lado como columnas de un nuevo DataFrame.

Pandas alinea los datos utilizando los índices de ambas series. Si un índice existe en una serie pero no en la otra, se mostrarán valores faltantes (`NaN`) en las posiciones correspondientes.

El resultado es un DataFrame que reúne la información de ambas series en una estructura tabular. 📋🔗

In [11]:
pd.concat([c1,c2], axis=1)

        0       1
0     red   green
1  orange    blue
2  yellow  purple

### 🍎🐾 Crear dos Series con índices personalizados

Se crean dos objetos `Series` llamados `fruits` y `animals`, cada uno con tres elementos y con índices personalizados.

La serie **`fruits`** asocia cada índice con el nombre de una fruta, mientras que la serie **`animals`** asocia los mismos índices con nombres de animales.

Aunque ambas series contienen los índices `a`, `b` y `c`, estos aparecen en diferente orden. Esta característica es importante porque Pandas utiliza los índices para alinear los datos cuando se realizan operaciones entre series, como sumas, concatenaciones o combinaciones.

Este ejemplo ayuda a comprender cómo Pandas relaciona los datos mediante sus etiquetas de índice en lugar de depender únicamente de la posición de los elementos. 📊🔗

In [12]:
fruits = pd.Series(
    data=["apple", "banana", "cherry"], 
    index=["a","b", "c"]
)

animals = pd.Series(
    data=["badger", "cougar", "anaconda"], 
    index=["b", "c", "a"]
)

In [13]:
fruits

a     apple
b    banana
c    cherry
dtype: object

In [14]:
animals

b      badger
c      cougar
a    anaconda
dtype: object

### 📊 Combinar Series por columnas utilizando sus índices

Esta operación utiliza `pd.concat()` con `axis=1` para colocar las series `fruits` y `animals` una junto a la otra, formando un nuevo DataFrame.

Pandas alinea automáticamente los datos según los índices de cada serie. Aunque los elementos aparecen en distinto orden dentro de las series originales, los valores se emparejan correctamente porque comparten los mismos índices (`a`, `b` y `c`).

El resultado es un DataFrame donde cada fila reúne la fruta y el animal asociados al mismo índice, demostrando cómo Pandas utiliza las etiquetas de índice para organizar y combinar datos de manera inteligente. 🍎🐾📊

In [15]:
pd.concat([fruits, animals], axis=1)

        0         1
a   apple  anaconda
b  banana    badger
c  cherry    cougar

### 📊 Combinar Series por columnas asignando nombres a las columnas

Esta operación utiliza `pd.concat()` para unir las series `fruits` y `animals` horizontalmente (`axis=1`) y crear un DataFrame.

El parámetro `keys` permite asignar nombres a las columnas resultantes. En este caso, las columnas se etiquetan como **`fruit`** y **`animal`**, facilitando la identificación de la información que contiene cada una.

Pandas alinea automáticamente los datos utilizando los índices de las series, asegurando que los valores correspondientes queden agrupados en la misma fila.

El resultado es un DataFrame más descriptivo y fácil de interpretar, ya que cada columna cuenta con una etiqueta significativa. 🍎🐾📋

In [16]:
pd.concat([fruits, animals], axis=1, keys=["fruit", "animal"])

    fruit    animal
a   apple  anaconda
b  banana    badger
c  cherry    cougar

### 🔗 Concatenar Series por filas utilizando claves

Esta operación utiliza `pd.concat()` para unir las series `fruits` y `animals` verticalmente (`axis=0`), es decir, una debajo de la otra.

El parámetro `keys` agrega un nivel adicional al índice, indicando de qué serie proviene cada conjunto de datos. En este caso, los elementos quedarán agrupados bajo las etiquetas **`fruit`** y **`animal`**.

El resultado es una única serie con un índice jerárquico (*MultiIndex*), que permite identificar tanto la serie de origen como el índice original de cada elemento.

Esta técnica es útil cuando se desea combinar varios conjuntos de datos sin perder información sobre su procedencia. 🍎🐾📊

In [17]:
pd.concat([fruits, animals], axis=0, keys=["fruit", "animal"])

fruit   a       apple
        b      banana
        c      cherry
animal  b      badger
        c      cougar
        a    anaconda
dtype: object

### 🧱 Inner vs Outer Joins

In [18]:
fruits = pd.Series(
    data=["apple", "banana", "cherry", "durian"],
    index=["a","b", "c", "d"]
)

animals = pd.Series(
    data=["badger", "cougar", "anaconda", "elk", "pika"],
    index=["b", "c", "a", "e", "p"]
)

In [19]:
pd.concat([animals, fruits], ignore_index=True)

0      badger
1      cougar
2    anaconda
3         elk
4        pika
5       apple
6      banana
7      cherry
8      durian
dtype: object

In [20]:
pd.concat([animals, fruits], axis=1)

          0       1
b    badger  banana
c    cougar  cherry
a  anaconda   apple
e       elk     NaN
p      pika     NaN
d       NaN  durian

### 📊 Combinar Series por columnas utilizando una unión interna

Esta operación utiliza `pd.concat()` para unir las series `animals` y `fruits` horizontalmente (`axis=1`).

El parámetro `join="inner"` indica que solo se conservarán los índices que estén presentes en ambas series. De esta forma, el resultado incluirá únicamente las filas cuyos índices sean comunes a todos los objetos concatenados.

Como ambas series comparten los índices `a`, `b` y `c`, estos serán los únicos que aparecerán en el DataFrame resultante.

Esta opción es útil cuando se desea trabajar únicamente con los datos que existen en todas las estructuras involucradas en la combinación. 📊🔗

In [21]:
pd.concat([animals, fruits], axis=1, join="inner")

          0       1
b    badger  banana
c    cougar  cherry
a  anaconda   apple

## Concatenating DataFrames By Columns

### 🥔🌱 Crear dos DataFrames con información de cosechas

Se crean dos DataFrames llamados `harvest_21` y `harvest_22`, cada uno con datos de productos agrícolas y sus cantidades cosechadas.

Ambos DataFrames contienen dos columnas:

- 🌾 `crop`: nombre del cultivo.
- 📦 `qty`: cantidad cosechada.

El DataFrame `harvest_21` almacena información correspondiente a una cosecha, mientras que `harvest_22` contiene datos de otra cosecha diferente.

Algunos cultivos aparecen en ambos conjuntos de datos, como **garlic** y **onions**, mientras que otros son exclusivos de una sola cosecha. Esto permite realizar posteriormente operaciones de concatenación, combinación o comparación para analizar la evolución de las cantidades cosechadas entre ambos periodos. 📊🚜

In [22]:
harvest_21 = pd.DataFrame(
    [['potatoes', 900], ['garlic', 1350], ['onions', 875]], 
    columns=['crop', 'qty']
)

harvest_22 = pd.DataFrame(
    [['garlic', 1600], ['spinach', 560], ['turnips', 999], ['onions', 1000]], 
    columns=['crop', 'qty']
)

In [23]:
harvest_21

       crop   qty
0  potatoes   900
1    garlic  1350
2    onions   875

In [24]:
harvest_22

      crop   qty
0   garlic  1600
1  spinach   560
2  turnips   999
3   onions  1000

### 📊 Unir dos DataFrames y reiniciar los índices

Esta operación utiliza `pd.concat()` para combinar los DataFrames `harvest_21` y `harvest_22` verticalmente, agregando las filas de un DataFrame debajo de las del otro.

El parámetro `ignore_index=True` indica que los índices originales deben descartarse y reemplazarse por una nueva secuencia de índices consecutivos que comienza en **0**.

El resultado es un único DataFrame que contiene todos los registros de ambas cosechas, facilitando el análisis conjunto de la información sin preocuparse por posibles índices duplicados o desordenados. 🌾📦📊

In [25]:
pd.concat([harvest_21, harvest_22], ignore_index=True)

       crop   qty
0  potatoes   900
1    garlic  1350
2    onions   875
3    garlic  1600
4   spinach   560
5   turnips   999
6    onions  1000

### 📊 Unir dos DataFrames utilizando claves

Esta operación utiliza `pd.concat()` para combinar los DataFrames `harvest_21` y `harvest_22` verticalmente.

El parámetro `keys` agrega un nivel adicional al índice, permitiendo identificar el origen de cada fila. En este caso, las claves **2021** y **2022** indican a qué cosecha pertenece cada registro.

El resultado es un DataFrame con un índice jerárquico (*MultiIndex*), donde el primer nivel representa el año de la cosecha y el segundo nivel corresponde al índice original de cada fila.

Esta técnica es útil para conservar información sobre la procedencia de los datos después de combinarlos en una sola estructura. 🌾📦🗓️

In [26]:
pd.concat([harvest_21, harvest_22], keys=[2021, 2022])

            crop   qty
2021 0  potatoes   900
     1    garlic  1350
     2    onions   875
2022 0    garlic  1600
     1   spinach   560
     2   turnips   999
     3    onions  1000

### 🌾📦💰 Crear un DataFrame con cantidades y ganancias de cosecha

Se crea un DataFrame llamado `harvest_23` que almacena información sobre distintos cultivos, la cantidad cosechada y la ganancia obtenida.

El DataFrame contiene tres columnas:

- 🌱 `crop`: nombre del cultivo.
- 📦 `qty`: cantidad cosechada.
- 💰 `profit`: ganancia asociada a ese cultivo.

Cada fila representa un cultivo diferente junto con sus datos de producción y rentabilidad.

Este tipo de estructura permite analizar no solo la cantidad producida, sino también el beneficio económico generado por cada cultivo, facilitando comparaciones y estudios de rendimiento agrícola. 📊🚜💵

In [27]:
harvest_23 = pd.DataFrame(
    [['potatoes', 900, 500], ['garlic', 1350, 1200], ['onions', 875, 950]], 
    columns=['crop', 'qty', 'profit']
)

### 📊 Unir varios DataFrames con diferentes columnas

Esta operación utiliza `pd.concat()` para combinar verticalmente los DataFrames `harvest_21`, `harvest_22` y `harvest_23`.

Pandas incluye todas las columnas que aparecen en cualquiera de los DataFrames. Cuando una fila proviene de un DataFrame que no contiene alguna de esas columnas, se asigna un valor faltante (`NaN`) en la posición correspondiente.

En este caso, la columna **`profit`** solo existe en `harvest_23`, por lo que las filas provenientes de `harvest_21` y `harvest_22` tendrán valores faltantes en dicha columna.

El resultado es un único DataFrame que reúne toda la información disponible, conservando los datos de producción y, cuando existan, las ganancias asociadas a cada cultivo. 🌾📦💰

In [28]:
pd.concat([harvest_21, harvest_22, harvest_23])

       crop   qty  profit
0  potatoes   900     NaN
1    garlic  1350     NaN
2    onions   875     NaN
0    garlic  1600     NaN
1   spinach   560     NaN
2   turnips   999     NaN
3    onions  1000     NaN
0  potatoes   900   500.0
1    garlic  1350  1200.0
2    onions   875   950.0

### 📊 Unir varios DataFrames conservando solo las columnas comunes

Esta operación utiliza `pd.concat()` para combinar verticalmente los DataFrames `harvest_21`, `harvest_22` y `harvest_23`.

El parámetro `join="inner"` indica que únicamente deben conservarse las columnas que están presentes en **todos** los DataFrames involucrados.

Como la columna **`profit`** solo existe en `harvest_23`, esta será excluida del resultado. Únicamente se mantendrán las columnas comunes, como **`crop`** y **`qty`**.

El resultado es un DataFrame unificado que contiene únicamente la información compartida por todos los conjuntos de datos, evitando la aparición de valores faltantes (`NaN`) debido a diferencias en la estructura de las columnas. 🌾📦📊

In [29]:
pd.concat([harvest_21, harvest_22, harvest_23], join="inner")

       crop   qty
0  potatoes   900
1    garlic  1350
2    onions   875
0    garlic  1600
1   spinach   560
2   turnips   999
3    onions  1000
0  potatoes   900
1    garlic  1350
2    onions   875

## 📌 Concatenación de DataFrames por Índice

### 🐾📊 Crear dos DataFrames relacionados con animales

Se crean dos DataFrames llamados `livestock` y `weights`, ambos utilizando nombres de animales como índices.

#### 🏠 `livestock`
Contiene información sobre los animales y el lugar donde se encuentran, además de la cantidad registrada de cada uno.

Sus columnas son:

- 📍 `location`: ubicación del animal.
- 🔢 `qty`: cantidad registrada.

#### ⚖️ `weights`
Contiene información sobre los pesos mínimo y máximo asociados a cada tipo de animal.

Sus columnas son:

- ⚖️ `min_weight`: peso mínimo.
- 🏋️ `max_weight`: peso máximo.

Los índices de ambos DataFrames representan especies de animales. Algunos animales aparecen en ambos conjuntos de datos, como **alpaca**, **horse** y **chicken**, mientras que otros solo están presentes en uno de ellos.

Esta estructura es ideal para realizar operaciones de combinación (*merge* o *join*), ya que los índices pueden utilizarse para relacionar la información de ubicación, cantidad y peso de cada animal. 🐴🐔🦙📊

In [30]:
livestock = pd.DataFrame(
    [['pasture', 9], ['stable', 3], ['coop', 34]], 
    columns=['location', 'qty'],
    index=['alpaca', 'horse', 'chicken']
)
weights = pd.DataFrame(
    [[4,10], [900, 2000], [1.2, 4], [110, 150]], 
    columns=['min_weight', 'max_weight'],
    index=['chicken', 'horse', 'duck', 'alpaca']
)

In [31]:
livestock

        location  qty
alpaca   pasture    9
horse     stable    3
chicken     coop   34

In [32]:
weights

         min_weight  max_weight
chicken         4.0          10
horse         900.0        2000
duck            1.2           4
alpaca        110.0         150

### 📊 Unir DataFrames con columnas diferentes

Esta operación utiliza `pd.concat()` para combinar verticalmente los DataFrames `livestock` y `weights`, agregando las filas de uno debajo de las del otro.

Como ambos DataFrames tienen columnas distintas, Pandas crea un conjunto de columnas que incluye todas las existentes en ambos. Cuando una fila proviene de un DataFrame que no contiene alguna de esas columnas, se asigna un valor faltante (`NaN`).

El resultado es un único DataFrame que reúne información de ubicación, cantidad y pesos de los animales, aunque algunas celdas contendrán valores faltantes debido a las diferencias en la estructura original de los datos.

Esta forma de concatenación es útil para combinar conjuntos de datos relacionados, incluso cuando no comparten exactamente las mismas columnas. 🐔🐴🦙📊

In [33]:
pd.concat([livestock, weights])

        location   qty  min_weight  max_weight
alpaca   pasture   9.0         NaN         NaN
horse     stable   3.0         NaN         NaN
chicken     coop  34.0         NaN         NaN
chicken      NaN   NaN         4.0        10.0
horse        NaN   NaN       900.0      2000.0
duck         NaN   NaN         1.2         4.0
alpaca       NaN   NaN       110.0       150.0

### 📊 Combinar DataFrames por columnas utilizando los índices

Esta operación utiliza `pd.concat()` con `axis=1` para unir los DataFrames `livestock` y `weights` horizontalmente, colocando sus columnas lado a lado.

Pandas alinea automáticamente los datos utilizando los índices de ambos DataFrames. Los animales que aparecen en ambos conjuntos de datos tendrán toda su información en la misma fila.

Si un animal existe en un DataFrame pero no en el otro, las columnas faltantes se completarán con valores `NaN`.

El resultado es un nuevo DataFrame que reúne información sobre ubicación, cantidad y rango de peso para cada animal, aprovechando los índices como criterio de correspondencia. 🐔🐴🦙⚖️📊

In [34]:
pd.concat([livestock, weights], axis=1)

        location   qty  min_weight  max_weight
alpaca   pasture   9.0       110.0         150
horse     stable   3.0       900.0        2000
chicken     coop  34.0         4.0          10
duck         NaN   NaN         1.2           4

### 📊 Combinar DataFrames por columnas conservando solo los índices comunes

Esta operación utiliza `pd.concat()` para unir los DataFrames `livestock` y `weights` horizontalmente (`axis=1`).

El parámetro `join="inner"` indica que únicamente se conservarán las filas cuyos índices estén presentes en ambos DataFrames.

En este caso, solo aparecerán los animales que existen tanto en `livestock` como en `weights`, mientras que aquellos que estén presentes en uno solo de los DataFrames serán excluidos.

El resultado es un DataFrame que combina la información de ubicación, cantidad y peso únicamente para los animales compartidos por ambos conjuntos de datos, evitando la generación de valores faltantes (`NaN`). 🐔🐴🦙📊

In [35]:
pd.concat([livestock, weights], axis=1, join="inner")

        location  qty  min_weight  max_weight
alpaca   pasture    9       110.0         150
horse     stable    3       900.0        2000
chicken     coop   34         4.0          10

### 🔄 Combinando DataFrames con `merge()`

### 🏀📊 Crear un DataFrame con información de equipos

Se crea un DataFrame llamado `teams` que almacena información sobre varios equipos deportivos y su desempeño en la temporada.

El DataFrame contiene las siguientes columnas:

- 🏀 `team`: nombre del equipo.
- 🌆 `city`: ciudad a la que pertenece el equipo.
- ✅ `wins`: cantidad de victorias obtenidas.
- ❌ `losses`: cantidad de derrotas registradas.

Cada fila representa un equipo diferente junto con su ciudad y estadísticas de rendimiento.

Esta estructura permite realizar análisis sobre el desempeño de los equipos, comparar victorias y derrotas, calcular porcentajes de éxito o generar clasificaciones basadas en los resultados obtenidos. 📈🏆

In [36]:
teams = pd.DataFrame(
    [
        ["Suns", "Phoenix", 20, 4], 
        ["Mavericks", "Dallas", 11,12], 
        ["Rockets", "Houston", 7, 16],
        ['Nuggets', "Denver", 11, 12]
    ], 
    columns=["team", "city", "wins", "losses"]
)

### 🌆📊 Crear un DataFrame con información de ciudades

Se crea un DataFrame llamado `cities` que almacena información demográfica de varias ciudades.

El DataFrame contiene las siguientes columnas:

- 🌆 `city`: nombre de la ciudad.
- 🗺️ `state`: estado al que pertenece la ciudad.
- 👥 `population`: número de habitantes.

Cada fila representa una ciudad diferente junto con su estado y población estimada.

Esta estructura puede utilizarse para realizar análisis demográficos, comparar tamaños de población o combinarse con otros conjuntos de datos que también contengan información de ciudades, como el DataFrame `teams`. 📈🏙️

In [37]:
cities = pd.DataFrame(
    [
        ["Houston", "Texas", 2310000], 
        ["Phoenix", "Arizona", 1630000], 
        ["San Diego", "California", 1410000],
        ["Dallas", "Texas", 1310000]
    ],
    columns=["city", "state", "population"]
)

In [38]:
teams

        team     city  wins  losses
0       Suns  Phoenix    20       4
1  Mavericks   Dallas    11      12
2    Rockets  Houston     7      16
3    Nuggets   Denver    11      12

In [39]:
cities

        city       state  population
0    Houston       Texas     2310000
1    Phoenix     Arizona     1630000
2  San Diego  California     1410000
3     Dallas       Texas     1310000

### 🔗 Combinar información de equipos y ciudades

Esta operación utiliza `merge()` para combinar los DataFrames `teams` y `cities`.

Como ambos DataFrames comparten una columna llamada `city`, Pandas la utiliza automáticamente como clave de unión para relacionar los registros.

El resultado es un nuevo DataFrame que reúne la información de los equipos con los datos demográficos de sus respectivas ciudades, incluyendo el estado y la población.

Solo se conservarán las filas cuyas ciudades aparezcan en ambos DataFrames, ya que `merge()` realiza una unión interna (*inner join*) de forma predeterminada. Esto significa que las ciudades que no tengan correspondencia en ambos conjuntos de datos no aparecerán en el resultado. 🏀🌆📊

In [40]:
teams.merge(cities)

        team     city  wins  losses    state  population
0       Suns  Phoenix    20       4  Arizona     1630000
1  Mavericks   Dallas    11      12    Texas     1310000
2    Rockets  Houston     7      16    Texas     2310000

### Combinar() con uniones izquierda, derecha, interna y externa

### 🔗 Combinar información utilizando la columna `city`

Esta operación utiliza `merge()` para unir los DataFrames `teams` y `cities`, indicando explícitamente que la columna `city` debe utilizarse como clave de relación.

El resultado combina la información de cada equipo con los datos correspondientes de su ciudad, como el estado y la población.

Al igual que una unión interna (*inner join*), solo se incluirán las filas cuyas ciudades existan en ambos DataFrames. De esta manera, cada equipo queda asociado con la información demográfica de la ciudad a la que pertenece. 🏀🌆📊

In [41]:
teams.merge(cities, on="city")

        team     city  wins  losses    state  population
0       Suns  Phoenix    20       4  Arizona     1630000
1  Mavericks   Dallas    11      12    Texas     1310000
2    Rockets  Houston     7      16    Texas     2310000

### 🔗 Realizar una unión interna entre equipos y ciudades

Esta operación utiliza `merge()` para combinar los DataFrames `teams` y `cities` utilizando la columna `city` como clave de relación.

El parámetro `how="inner"` indica que se debe realizar una **unión interna** (*inner join*), conservando únicamente las filas que tengan una coincidencia en ambos DataFrames.

El resultado es un nuevo DataFrame que reúne la información de los equipos con los datos de sus respectivas ciudades, incluyendo el estado y la población.

Este tipo de unión es útil cuando solo se desea trabajar con registros que tienen información completa en ambos conjuntos de datos. 🏀🌆📊

In [42]:
teams.merge(cities, on="city", how="inner")

        team     city  wins  losses    state  population
0       Suns  Phoenix    20       4  Arizona     1630000
1  Mavericks   Dallas    11      12    Texas     1310000
2    Rockets  Houston     7      16    Texas     2310000

### 🔗 Realizar una unión izquierda entre equipos y ciudades

Esta operación utiliza `merge()` para combinar los DataFrames `teams` y `cities`, tomando como referencia la columna común `city`.

El parámetro `how="left"` indica que se debe realizar una **unión izquierda** (*left join*), por lo que se conservarán todas las filas del DataFrame `teams`.

Si una ciudad de `teams` tiene una coincidencia en `cities`, se agregarán sus datos correspondientes. En caso contrario, las columnas provenientes de `cities` contendrán valores faltantes (`NaN`).

El resultado permite mantener todos los equipos en el conjunto de datos, incluso cuando no exista información asociada de su ciudad en el segundo DataFrame. 🏀🌆📊

In [43]:
teams.merge(cities, how="left")

        team     city  wins  losses    state  population
0       Suns  Phoenix    20       4  Arizona   1630000.0
1  Mavericks   Dallas    11      12    Texas   1310000.0
2    Rockets  Houston     7      16    Texas   2310000.0
3    Nuggets   Denver    11      12      NaN         NaN

### 🔗 Realizar una unión derecha entre equipos y ciudades

Esta operación utiliza `merge()` para combinar los DataFrames `teams` y `cities`, utilizando la columna común `city` como criterio de relación.

El parámetro `how="right"` indica que se debe realizar una **unión derecha** (*right join*), por lo que se conservarán todas las filas del DataFrame `cities`.

Si una ciudad de `cities` tiene una coincidencia en `teams`, se agregarán los datos del equipo correspondiente. En caso contrario, las columnas provenientes de `teams` contendrán valores faltantes (`NaN`).

El resultado permite mantener todas las ciudades del DataFrame `cities`, incluso aquellas que no tienen un equipo asociado en el DataFrame `teams`. 🌆🏀📊

In [44]:
teams.merge(cities, how="right")

        team       city  wins  losses       state  population
0    Rockets    Houston   7.0    16.0       Texas     2310000
1       Suns    Phoenix  20.0     4.0     Arizona     1630000
2        NaN  San Diego   NaN     NaN  California     1410000
3  Mavericks     Dallas  11.0    12.0       Texas     1310000

### 🔗 Realizar una unión completa entre equipos y ciudades

Esta operación utiliza `merge()` para combinar los DataFrames `teams` y `cities` utilizando la columna común `city` como clave de relación.

El parámetro `how="outer"` indica que se debe realizar una **unión completa** (*outer join*), por lo que se conservarán todas las filas de ambos DataFrames.

Cuando exista una coincidencia entre las ciudades de ambos conjuntos de datos, la información se combinará en una misma fila. Si una ciudad aparece solo en uno de los DataFrames, las columnas correspondientes al otro DataFrame se rellenarán con valores faltantes (`NaN`).

El resultado proporciona una vista completa de toda la información disponible, incluyendo tanto los equipos como las ciudades, independientemente de que tengan o no una correspondencia en el otro conjunto de datos. 🏀🌆📊

In [45]:
teams.merge(cities, how="outer")

        team       city  wins  losses       state  population
0  Mavericks     Dallas  11.0    12.0       Texas   1310000.0
1    Nuggets     Denver  11.0    12.0         NaN         NaN
2    Rockets    Houston   7.0    16.0       Texas   2310000.0
3       Suns    Phoenix  20.0     4.0     Arizona   1630000.0
4        NaN  San Diego   NaN     NaN  California   1410000.0

### 🔗 Realizar una unión izquierda tomando las ciudades como referencia

Esta operación utiliza `merge()` para combinar los DataFrames `cities` y `teams` mediante la columna `city`.

El parámetro `how="left"` indica que se conservarán todas las filas del DataFrame `cities`, ya que este es el DataFrame situado a la izquierda de la operación.

Cuando una ciudad tenga un equipo asociado, se agregarán los datos del equipo correspondiente. Si una ciudad no tiene coincidencia en el DataFrame `teams`, las columnas relacionadas con el equipo contendrán valores faltantes (`NaN`).

El resultado permite visualizar todas las ciudades junto con la información de sus equipos cuando exista una relación entre ambos conjuntos de datos. 🌆🏀📊

In [46]:
cities.merge(teams, on="city", how="left")

        city       state  population       team  wins  losses
0    Houston       Texas     2310000    Rockets   7.0    16.0
1    Phoenix     Arizona     1630000       Suns  20.0     4.0
2  San Diego  California     1410000        NaN   NaN     NaN
3     Dallas       Texas     1310000  Mavericks  11.0    12.0

### 🔗 Realizar una unión derecha utilizando la columna `city`

Esta operación utiliza `merge()` para combinar los DataFrames `teams` y `cities` empleando la columna `city` como clave de relación.

El parámetro `how="right"` indica que se conservarán todas las filas del DataFrame `cities`, que es el DataFrame situado a la derecha de la operación.

Cuando una ciudad tenga un equipo asociado, los datos de ambos DataFrames se combinarán en la misma fila. Si una ciudad no tiene correspondencia en `teams`, las columnas relacionadas con el equipo contendrán valores faltantes (`NaN`).

El resultado incluye todas las ciudades registradas en `cities`, independientemente de que tengan o no un equipo asociado en el DataFrame `teams`. 🌆🏀📊

In [47]:
teams.merge(cities, on="city", how="right")

        team       city  wins  losses       state  population
0    Rockets    Houston   7.0    16.0       Texas     2310000
1       Suns    Phoenix  20.0     4.0     Arizona     1630000
2        NaN  San Diego   NaN     NaN  California     1410000
3  Mavericks     Dallas  11.0    12.0       Texas     1310000

### Merge() On y Argumentos de sufijos

### 🎓📊 Crear dos DataFrames con calificaciones de exámenes

Se crean dos DataFrames llamados `midterms` y `finals`, que almacenan información sobre estudiantes y sus resultados en diferentes evaluaciones.

#### 📝 `midterms`
Contiene las calificaciones obtenidas en los exámenes parciales.

Sus columnas son:

- 👤 `first`: nombre del estudiante.
- 👥 `last`: apellido del estudiante.
- 📊 `score`: calificación obtenida.

#### 🎯 `finals`
Contiene las calificaciones obtenidas en los exámenes finales.

Sus columnas son:

- 👤 `first`: nombre del estudiante.
- 👥 `last`: apellido del estudiante.
- 📊 `score`: calificación obtenida.
- ⭐ `extra_credit`: indica si el estudiante recibió puntos extra.

Algunos estudiantes aparecen en ambos DataFrames, mientras que otros solo están presentes en uno de ellos. Además, ambos conjuntos contienen columnas con el mismo nombre, como `first`, `last` y `score`.

Estos DataFrames son ideales para practicar operaciones de combinación (*merge*), permitiendo relacionar las calificaciones de los parciales y finales de cada estudiante mediante su nombre y apellido. 🎓📈

In [48]:
midterms = pd.DataFrame(
    [['alex', 'padilla', 92], ['rayna', 'wilson', 83], ['juan', 'gomez', 78], ['angela', 'smith', 66],['stephen', 'yu', 98]], 
    columns=['first', 'last', 'score']
)
finals = pd.DataFrame(
    [['alex','padilla', 97, False], ['rayna', 'wilson', 88, False], ['alex', 'smith', 86, True], ['juan', 'gomez', 71, True], ['stephen', 'yu', 78, False], ['sakura', 'steel', 100, True]], 
    columns=['first', 'last','score', 'extra_credit']
)

In [49]:
midterms

     first     last  score
0     alex  padilla     92
1    rayna   wilson     83
2     juan    gomez     78
3   angela    smith     66
4  stephen       yu     98

In [50]:
finals

     first     last  score  extra_credit
0     alex  padilla     97         False
1    rayna   wilson     88         False
2     alex    smith     86          True
3     juan    gomez     71          True
4  stephen       yu     78         False
5   sakura    steel    100          True

### 🔗 Combinar registros utilizando la calificación como clave

Esta operación utiliza `merge()` para unir los DataFrames `midterms` y `finals` empleando la columna `score` como criterio de relación.

Solo se combinarán las filas que tengan exactamente la misma calificación en ambos DataFrames. Si una calificación aparece en un DataFrame pero no en el otro, no formará parte del resultado.

Debido a que ambos DataFrames contienen columnas con los mismos nombres (`first` y `last`), Pandas agregará sufijos automáticos para distinguir las columnas provenientes de cada conjunto de datos.

Este tipo de unión permite identificar registros que comparten la misma puntuación, aunque no necesariamente correspondan al mismo estudiante. 🎓📊🔗

In [51]:
midterms.merge(finals, on="score")

  first_x last_x  score  first_y last_y  extra_credit
0    juan  gomez     78  stephen     yu         False

### 🔗 Combinar registros utilizando el nombre como clave

Esta operación utiliza `merge()` para unir los DataFrames `midterms` y `finals` empleando la columna `first` como criterio de relación.

Se combinarán las filas cuyos nombres coincidan en ambos DataFrames, independientemente de que los apellidos o las calificaciones sean diferentes.

Como ambos conjuntos de datos contienen columnas con los mismos nombres (`last` y `score`), Pandas agregará sufijos automáticos a estas columnas para distinguir los valores provenientes de cada DataFrame.

El resultado permite comparar la información de los exámenes parciales y finales para los estudiantes que comparten el mismo nombre. 🎓📊🔗

In [52]:
midterms.merge(finals, on="first")

     first   last_x  score_x   last_y  score_y  extra_credit
0     alex  padilla       92  padilla       97         False
1     alex  padilla       92    smith       86          True
2    rayna   wilson       83   wilson       88         False
3     juan    gomez       78    gomez       71          True
4  stephen       yu       98       yu       78         False

### 🔗 Combinar registros utilizando nombre y apellido

Esta operación utiliza `merge()` para unir los DataFrames `midterms` y `finals` empleando las columnas `first` y `last` como claves de relación.

El parámetro `how="inner"` indica que se realizará una **unión interna**, por lo que únicamente se conservarán los estudiantes que aparezcan en ambos DataFrames con el mismo nombre y apellido.

Como ambos conjuntos contienen una columna llamada `score`, Pandas agregará sufijos automáticos para diferenciar la calificación del examen parcial de la calificación del examen final.

El resultado permite comparar las calificaciones de los estudiantes que tienen registros tanto en los exámenes parciales como en los finales. 🎓📊🔗

In [53]:
midterms.merge(finals, on=["first", "last"], how="inner")

     first     last  score_x  score_y  extra_credit
0     alex  padilla       92       97         False
1    rayna   wilson       83       88         False
2     juan    gomez       78       71          True
3  stephen       yu       98       78         False

### 🔗 Combinar registros y personalizar los nombres de columnas duplicadas

Esta operación utiliza `merge()` para unir los DataFrames `midterms` y `finals` mediante las columnas `first` y `last`.

El parámetro `how="inner"` indica que solo se incluirán los estudiantes que aparezcan en ambos DataFrames con el mismo nombre y apellido.

Como ambos conjuntos contienen una columna llamada `score`, el parámetro `suffixes` permite personalizar los sufijos que Pandas añadirá a los nombres de las columnas duplicadas. De esta forma, las calificaciones del examen parcial y del examen final pueden identificarse fácilmente en el resultado.

El DataFrame resultante reúne la información académica de los estudiantes presentes en ambos exámenes, mostrando claramente el origen de cada calificación. 🎓📊🔗

In [54]:
midterms.merge(finals, on=["first", "last"], how="inner", suffixes=("_midterms", "_finals"))

     first     last  score_midterms  score_finals  extra_credit
0     alex  padilla              92            97         False
1    rayna   wilson              83            88         False
2     juan    gomez              78            71          True
3  stephen       yu              98            78         False

### 🔗 Crear un DataFrame combinado con calificaciones de parciales y finales

Esta operación realiza una unión entre los DataFrames `midterms` y `finals` utilizando las columnas `first` y `last` como claves de relación.

La unión es de tipo **interna** (*inner join*), por lo que solo se conservarán los estudiantes que aparezcan en ambos conjuntos de datos.

Los sufijos `_m` y `_f` se agregan a las columnas con nombres duplicados para distinguir claramente la información proveniente de los exámenes parciales y finales.

El resultado se almacena en un nuevo DataFrame llamado `combo`, que contiene la información consolidada de los estudiantes presentes en ambos exámenes, facilitando comparaciones y análisis posteriores de su desempeño académico. 🎓📊

In [55]:
combo = midterms.merge(finals, on=["first", "last"], how="inner", suffixes=("_m", "_f"))

### 📊 Calcular el promedio de las calificaciones

Esta operación crea una nueva columna llamada `avg` en el DataFrame `combo`.

Para cada estudiante, se suman las calificaciones del examen parcial (`score_m`) y del examen final (`score_f`), y posteriormente el resultado se divide entre **2** para obtener el promedio.

La nueva columna almacena la calificación promedio de cada estudiante, lo que facilita el análisis y la comparación de su desempeño general en ambas evaluaciones. 🎓📈

In [56]:
combo["avg"] = (combo["score_m"] + combo["score_f"])/2

In [57]:
combo

     first     last  score_m  score_f  extra_credit   avg
0     alex  padilla       92       97         False  94.5
1    rayna   wilson       83       88         False  85.5
2     juan    gomez       78       71          True  74.5
3  stephen       yu       98       78         False  88.0

### ⭐ Agregar puntos extra al promedio

Esta operación identifica a los estudiantes que tienen el valor `True` en la columna `extra_credit` y modifica su promedio almacenado en la columna `avg`.

A los estudiantes que recibieron puntos extra se les suman **5 puntos** a su promedio, mientras que los demás conservan su calificación original.

El uso de `loc` permite seleccionar únicamente las filas que cumplen la condición y actualizar sus valores de forma directa dentro del DataFrame.

Esta técnica es útil para aplicar ajustes o bonificaciones a grupos específicos de registros según ciertos criterios. 🎓⭐📈

In [58]:
combo.loc[combo["extra_credit"] == True, 'avg'] += 5

In [59]:
combo

     first     last  score_m  score_f  extra_credit   avg
0     alex  padilla       92       97         False  94.5
1    rayna   wilson       83       88         False  85.5
2     juan    gomez       78       71          True  79.5
3  stephen       yu       98       78         False  88.0