# 🔗 Combinación de DataFrames y Series

### 📚 Usando `pd.concat()` con Series

In [1]:
import pandas as pd

In [2]:
s1 = pd.Series(['a', 'b', 'c'])
s2 = pd.Series(['d', 'e', 'f', 'z'])

In [3]:
pd.concat([s1,s2])

0    a
1    b
2    c
0    d
1    e
2    f
3    z
dtype: object

### 🔗 Concatenar dos Series

Esta operación utiliza `pd.concat()` para unir las series `s2` y `s1` en una sola estructura.

Los elementos de `s2` se colocan primero y, a continuación, se agregan los elementos de `s1`, conservando sus índices originales.

El resultado es una nueva serie que contiene todos los valores de ambas series, permitiendo combinar datos que se encuentran separados en distintas estructuras. 📊🔗

In [4]:
pd.concat([s2, s1])

0    d
1    e
2    f
3    z
0    a
1    b
2    c
dtype: object

### 🔗 Concatenar dos Series y reiniciar los índices

Esta operación utiliza `pd.concat()` para unir las series `s2` y `s1` en una sola serie.

A diferencia de la concatenación estándar, el parámetro `ignore_index=True` hace que Pandas ignore los índices originales de ambas series y genere nuevos índices consecutivos comenzando desde **0**.

El resultado es una serie combinada con una numeración continua, lo que puede facilitar el trabajo con los datos cuando los índices originales ya no son necesarios. 📊🔢

In [5]:
pd.concat([s2, s1], ignore_index=True)

0    d
1    e
2    f
3    z
4    a
5    b
6    c
dtype: object

In [6]:
nums = pd.Series([65,69,99,23,56,54])
nums2 = pd.Series([11,111,1111])

### 🔗 Concatenar múltiples Series y reiniciar los índices

Esta operación utiliza `pd.concat()` para unir las series `s2`, `s1` y `nums` en una sola serie.

El parámetro `ignore_index=True` indica que los índices originales deben descartarse y reemplazarse por una nueva secuencia de índices consecutivos que comienza en **0**.

El resultado es una única serie que contiene todos los valores de las tres series en el orden en que fueron proporcionadas, facilitando el manejo de los datos como una sola colección continua. 📊🔢

In [7]:
pd.concat([s2, s1, nums], ignore_index=True)

0      d
1      e
2      f
3      z
4      a
5      b
6      c
7     65
8     69
9     99
10    23
11    56
12    54
dtype: object

In [8]:
pd.concat([nums, nums2, s1], ignore_index=True)

0       65
1       69
2       99
3       23
4       56
5       54
6       11
7      111
8     1111
9        a
10       b
11       c
dtype: object

### 📚 Usando `pd.concat()` con Series by Index

In [9]:
c1 = pd.Series(["red", "orange", "yellow"])
c2 = pd.Series(["green", "blue", "purple"])

In [10]:
pd.concat([c1,c2])

0       red
1    orange
2    yellow
0     green
1      blue
2    purple
dtype: object

### 📊 Concatenar Series por columnas

Esta operación utiliza `pd.concat()` para combinar las series `c1` y `c2` horizontalmente mediante `axis=1`.

En lugar de agregar los valores uno debajo de otro, las series se colocan lado a lado como columnas de un nuevo DataFrame.

Pandas alinea los datos utilizando los índices de ambas series. Si un índice existe en una serie pero no en la otra, se mostrarán valores faltantes (`NaN`) en las posiciones correspondientes.

El resultado es un DataFrame que reúne la información de ambas series en una estructura tabular. 📋🔗

In [11]:
pd.concat([c1,c2], axis=1)

        0       1
0     red   green
1  orange    blue
2  yellow  purple

### 🍎🐾 Crear dos Series con índices personalizados

Se crean dos objetos `Series` llamados `fruits` y `animals`, cada uno con tres elementos y con índices personalizados.

La serie **`fruits`** asocia cada índice con el nombre de una fruta, mientras que la serie **`animals`** asocia los mismos índices con nombres de animales.

Aunque ambas series contienen los índices `a`, `b` y `c`, estos aparecen en diferente orden. Esta característica es importante porque Pandas utiliza los índices para alinear los datos cuando se realizan operaciones entre series, como sumas, concatenaciones o combinaciones.

Este ejemplo ayuda a comprender cómo Pandas relaciona los datos mediante sus etiquetas de índice en lugar de depender únicamente de la posición de los elementos. 📊🔗

In [12]:
fruits = pd.Series(
    data=["apple", "banana", "cherry"], 
    index=["a","b", "c"]
)

animals = pd.Series(
    data=["badger", "cougar", "anaconda"], 
    index=["b", "c", "a"]
)

In [13]:
fruits

a     apple
b    banana
c    cherry
dtype: object

In [14]:
animals

b      badger
c      cougar
a    anaconda
dtype: object

### 📊 Combinar Series por columnas utilizando sus índices

Esta operación utiliza `pd.concat()` con `axis=1` para colocar las series `fruits` y `animals` una junto a la otra, formando un nuevo DataFrame.

Pandas alinea automáticamente los datos según los índices de cada serie. Aunque los elementos aparecen en distinto orden dentro de las series originales, los valores se emparejan correctamente porque comparten los mismos índices (`a`, `b` y `c`).

El resultado es un DataFrame donde cada fila reúne la fruta y el animal asociados al mismo índice, demostrando cómo Pandas utiliza las etiquetas de índice para organizar y combinar datos de manera inteligente. 🍎🐾📊

In [15]:
pd.concat([fruits, animals], axis=1)

        0         1
a   apple  anaconda
b  banana    badger
c  cherry    cougar

### 📊 Combinar Series por columnas asignando nombres a las columnas

Esta operación utiliza `pd.concat()` para unir las series `fruits` y `animals` horizontalmente (`axis=1`) y crear un DataFrame.

El parámetro `keys` permite asignar nombres a las columnas resultantes. En este caso, las columnas se etiquetan como **`fruit`** y **`animal`**, facilitando la identificación de la información que contiene cada una.

Pandas alinea automáticamente los datos utilizando los índices de las series, asegurando que los valores correspondientes queden agrupados en la misma fila.

El resultado es un DataFrame más descriptivo y fácil de interpretar, ya que cada columna cuenta con una etiqueta significativa. 🍎🐾📋

In [16]:
pd.concat([fruits, animals], axis=1, keys=["fruit", "animal"])

    fruit    animal
a   apple  anaconda
b  banana    badger
c  cherry    cougar

### 🔗 Concatenar Series por filas utilizando claves

Esta operación utiliza `pd.concat()` para unir las series `fruits` y `animals` verticalmente (`axis=0`), es decir, una debajo de la otra.

El parámetro `keys` agrega un nivel adicional al índice, indicando de qué serie proviene cada conjunto de datos. En este caso, los elementos quedarán agrupados bajo las etiquetas **`fruit`** y **`animal`**.

El resultado es una única serie con un índice jerárquico (*MultiIndex*), que permite identificar tanto la serie de origen como el índice original de cada elemento.

Esta técnica es útil cuando se desea combinar varios conjuntos de datos sin perder información sobre su procedencia. 🍎🐾📊

In [17]:
pd.concat([fruits, animals], axis=0, keys=["fruit", "animal"])

fruit   a       apple
        b      banana
        c      cherry
animal  b      badger
        c      cougar
        a    anaconda
dtype: object

### 🧱 Inner vs Outer Joins

In [18]:
fruits = pd.Series(
    data=["apple", "banana", "cherry", "durian"],
    index=["a","b", "c", "d"]
)

animals = pd.Series(
    data=["badger", "cougar", "anaconda", "elk", "pika"],
    index=["b", "c", "a", "e", "p"]
)

In [19]:
pd.concat([animals, fruits], ignore_index=True)

0      badger
1      cougar
2    anaconda
3         elk
4        pika
5       apple
6      banana
7      cherry
8      durian
dtype: object

In [20]:
pd.concat([animals, fruits], axis=1)

          0       1
b    badger  banana
c    cougar  cherry
a  anaconda   apple
e       elk     NaN
p      pika     NaN
d       NaN  durian

### 📊 Combinar Series por columnas utilizando una unión interna

Esta operación utiliza `pd.concat()` para unir las series `animals` y `fruits` horizontalmente (`axis=1`).

El parámetro `join="inner"` indica que solo se conservarán los índices que estén presentes en ambas series. De esta forma, el resultado incluirá únicamente las filas cuyos índices sean comunes a todos los objetos concatenados.

Como ambas series comparten los índices `a`, `b` y `c`, estos serán los únicos que aparecerán en el DataFrame resultante.

Esta opción es útil cuando se desea trabajar únicamente con los datos que existen en todas las estructuras involucradas en la combinación. 📊🔗

In [21]:
pd.concat([animals, fruits], axis=1, join="inner")

          0       1
b    badger  banana
c    cougar  cherry
a  anaconda   apple

## Concatenating DataFrames By Columns

### 🥔🌱 Crear dos DataFrames con información de cosechas

Se crean dos DataFrames llamados `harvest_21` y `harvest_22`, cada uno con datos de productos agrícolas y sus cantidades cosechadas.

Ambos DataFrames contienen dos columnas:

- 🌾 `crop`: nombre del cultivo.
- 📦 `qty`: cantidad cosechada.

El DataFrame `harvest_21` almacena información correspondiente a una cosecha, mientras que `harvest_22` contiene datos de otra cosecha diferente.

Algunos cultivos aparecen en ambos conjuntos de datos, como **garlic** y **onions**, mientras que otros son exclusivos de una sola cosecha. Esto permite realizar posteriormente operaciones de concatenación, combinación o comparación para analizar la evolución de las cantidades cosechadas entre ambos periodos. 📊🚜

In [22]:
harvest_21 = pd.DataFrame(
    [['potatoes', 900], ['garlic', 1350], ['onions', 875]], 
    columns=['crop', 'qty']
)

harvest_22 = pd.DataFrame(
    [['garlic', 1600], ['spinach', 560], ['turnips', 999], ['onions', 1000]], 
    columns=['crop', 'qty']
)

In [23]:
harvest_21

       crop   qty
0  potatoes   900
1    garlic  1350
2    onions   875

In [24]:
harvest_22

      crop   qty
0   garlic  1600
1  spinach   560
2  turnips   999
3   onions  1000

### 📊 Unir dos DataFrames y reiniciar los índices

Esta operación utiliza `pd.concat()` para combinar los DataFrames `harvest_21` y `harvest_22` verticalmente, agregando las filas de un DataFrame debajo de las del otro.

El parámetro `ignore_index=True` indica que los índices originales deben descartarse y reemplazarse por una nueva secuencia de índices consecutivos que comienza en **0**.

El resultado es un único DataFrame que contiene todos los registros de ambas cosechas, facilitando el análisis conjunto de la información sin preocuparse por posibles índices duplicados o desordenados. 🌾📦📊

In [25]:
pd.concat([harvest_21, harvest_22], ignore_index=True)

       crop   qty
0  potatoes   900
1    garlic  1350
2    onions   875
3    garlic  1600
4   spinach   560
5   turnips   999
6    onions  1000

### 📊 Unir dos DataFrames utilizando claves

Esta operación utiliza `pd.concat()` para combinar los DataFrames `harvest_21` y `harvest_22` verticalmente.

El parámetro `keys` agrega un nivel adicional al índice, permitiendo identificar el origen de cada fila. En este caso, las claves **2021** y **2022** indican a qué cosecha pertenece cada registro.

El resultado es un DataFrame con un índice jerárquico (*MultiIndex*), donde el primer nivel representa el año de la cosecha y el segundo nivel corresponde al índice original de cada fila.

Esta técnica es útil para conservar información sobre la procedencia de los datos después de combinarlos en una sola estructura. 🌾📦🗓️

In [26]:
pd.concat([harvest_21, harvest_22], keys=[2021, 2022])

            crop   qty
2021 0  potatoes   900
     1    garlic  1350
     2    onions   875
2022 0    garlic  1600
     1   spinach   560
     2   turnips   999
     3    onions  1000

### 🌾📦💰 Crear un DataFrame con cantidades y ganancias de cosecha

Se crea un DataFrame llamado `harvest_23` que almacena información sobre distintos cultivos, la cantidad cosechada y la ganancia obtenida.

El DataFrame contiene tres columnas:

- 🌱 `crop`: nombre del cultivo.
- 📦 `qty`: cantidad cosechada.
- 💰 `profit`: ganancia asociada a ese cultivo.

Cada fila representa un cultivo diferente junto con sus datos de producción y rentabilidad.

Este tipo de estructura permite analizar no solo la cantidad producida, sino también el beneficio económico generado por cada cultivo, facilitando comparaciones y estudios de rendimiento agrícola. 📊🚜💵

In [27]:
harvest_23 = pd.DataFrame(
    [['potatoes', 900, 500], ['garlic', 1350, 1200], ['onions', 875, 950]], 
    columns=['crop', 'qty', 'profit']
)

### 📊 Unir varios DataFrames con diferentes columnas

Esta operación utiliza `pd.concat()` para combinar verticalmente los DataFrames `harvest_21`, `harvest_22` y `harvest_23`.

Pandas incluye todas las columnas que aparecen en cualquiera de los DataFrames. Cuando una fila proviene de un DataFrame que no contiene alguna de esas columnas, se asigna un valor faltante (`NaN`) en la posición correspondiente.

En este caso, la columna **`profit`** solo existe en `harvest_23`, por lo que las filas provenientes de `harvest_21` y `harvest_22` tendrán valores faltantes en dicha columna.

El resultado es un único DataFrame que reúne toda la información disponible, conservando los datos de producción y, cuando existan, las ganancias asociadas a cada cultivo. 🌾📦💰

In [28]:
pd.concat([harvest_21, harvest_22, harvest_23])

       crop   qty  profit
0  potatoes   900     NaN
1    garlic  1350     NaN
2    onions   875     NaN
0    garlic  1600     NaN
1   spinach   560     NaN
2   turnips   999     NaN
3    onions  1000     NaN
0  potatoes   900   500.0
1    garlic  1350  1200.0
2    onions   875   950.0

### 📊 Unir varios DataFrames conservando solo las columnas comunes

Esta operación utiliza `pd.concat()` para combinar verticalmente los DataFrames `harvest_21`, `harvest_22` y `harvest_23`.

El parámetro `join="inner"` indica que únicamente deben conservarse las columnas que están presentes en **todos** los DataFrames involucrados.

Como la columna **`profit`** solo existe en `harvest_23`, esta será excluida del resultado. Únicamente se mantendrán las columnas comunes, como **`crop`** y **`qty`**.

El resultado es un DataFrame unificado que contiene únicamente la información compartida por todos los conjuntos de datos, evitando la aparición de valores faltantes (`NaN`) debido a diferencias en la estructura de las columnas. 🌾📦📊

In [29]:
pd.concat([harvest_21, harvest_22, harvest_23], join="inner")

       crop   qty
0  potatoes   900
1    garlic  1350
2    onions   875
0    garlic  1600
1   spinach   560
2   turnips   999
3    onions  1000
0  potatoes   900
1    garlic  1350
2    onions   875

## 📌 Concatenación de DataFrames por Índice

### 🐾📊 Crear dos DataFrames relacionados con animales

Se crean dos DataFrames llamados `livestock` y `weights`, ambos utilizando nombres de animales como índices.

#### 🏠 `livestock`
Contiene información sobre los animales y el lugar donde se encuentran, además de la cantidad registrada de cada uno.

Sus columnas son:

- 📍 `location`: ubicación del animal.
- 🔢 `qty`: cantidad registrada.

#### ⚖️ `weights`
Contiene información sobre los pesos mínimo y máximo asociados a cada tipo de animal.

Sus columnas son:

- ⚖️ `min_weight`: peso mínimo.
- 🏋️ `max_weight`: peso máximo.

Los índices de ambos DataFrames representan especies de animales. Algunos animales aparecen en ambos conjuntos de datos, como **alpaca**, **horse** y **chicken**, mientras que otros solo están presentes en uno de ellos.

Esta estructura es ideal para realizar operaciones de combinación (*merge* o *join*), ya que los índices pueden utilizarse para relacionar la información de ubicación, cantidad y peso de cada animal. 🐴🐔🦙📊

In [30]:
livestock = pd.DataFrame(
    [['pasture', 9], ['stable', 3], ['coop', 34]], 
    columns=['location', 'qty'],
    index=['alpaca', 'horse', 'chicken']
)
weights = pd.DataFrame(
    [[4,10], [900, 2000], [1.2, 4], [110, 150]], 
    columns=['min_weight', 'max_weight'],
    index=['chicken', 'horse', 'duck', 'alpaca']
)

In [31]:
livestock

        location  qty
alpaca   pasture    9
horse     stable    3
chicken     coop   34

In [32]:
weights

         min_weight  max_weight
chicken         4.0          10
horse         900.0        2000
duck            1.2           4
alpaca        110.0         150

### 📊 Unir DataFrames con columnas diferentes

Esta operación utiliza `pd.concat()` para combinar verticalmente los DataFrames `livestock` y `weights`, agregando las filas de uno debajo de las del otro.

Como ambos DataFrames tienen columnas distintas, Pandas crea un conjunto de columnas que incluye todas las existentes en ambos. Cuando una fila proviene de un DataFrame que no contiene alguna de esas columnas, se asigna un valor faltante (`NaN`).

El resultado es un único DataFrame que reúne información de ubicación, cantidad y pesos de los animales, aunque algunas celdas contendrán valores faltantes debido a las diferencias en la estructura original de los datos.

Esta forma de concatenación es útil para combinar conjuntos de datos relacionados, incluso cuando no comparten exactamente las mismas columnas. 🐔🐴🦙📊

In [33]:
pd.concat([livestock, weights])

        location   qty  min_weight  max_weight
alpaca   pasture   9.0         NaN         NaN
horse     stable   3.0         NaN         NaN
chicken     coop  34.0         NaN         NaN
chicken      NaN   NaN         4.0        10.0
horse        NaN   NaN       900.0      2000.0
duck         NaN   NaN         1.2         4.0
alpaca       NaN   NaN       110.0       150.0

### 📊 Combinar DataFrames por columnas utilizando los índices

Esta operación utiliza `pd.concat()` con `axis=1` para unir los DataFrames `livestock` y `weights` horizontalmente, colocando sus columnas lado a lado.

Pandas alinea automáticamente los datos utilizando los índices de ambos DataFrames. Los animales que aparecen en ambos conjuntos de datos tendrán toda su información en la misma fila.

Si un animal existe en un DataFrame pero no en el otro, las columnas faltantes se completarán con valores `NaN`.

El resultado es un nuevo DataFrame que reúne información sobre ubicación, cantidad y rango de peso para cada animal, aprovechando los índices como criterio de correspondencia. 🐔🐴🦙⚖️📊

In [34]:
pd.concat([livestock, weights], axis=1)

        location   qty  min_weight  max_weight
alpaca   pasture   9.0       110.0         150
horse     stable   3.0       900.0        2000
chicken     coop  34.0         4.0          10
duck         NaN   NaN         1.2           4

### 📊 Combinar DataFrames por columnas conservando solo los índices comunes

Esta operación utiliza `pd.concat()` para unir los DataFrames `livestock` y `weights` horizontalmente (`axis=1`).

El parámetro `join="inner"` indica que únicamente se conservarán las filas cuyos índices estén presentes en ambos DataFrames.

En este caso, solo aparecerán los animales que existen tanto en `livestock` como en `weights`, mientras que aquellos que estén presentes en uno solo de los DataFrames serán excluidos.

El resultado es un DataFrame que combina la información de ubicación, cantidad y peso únicamente para los animales compartidos por ambos conjuntos de datos, evitando la generación de valores faltantes (`NaN`). 🐔🐴🦙📊

In [35]:
pd.concat([livestock, weights], axis=1, join="inner")

        location  qty  min_weight  max_weight
alpaca   pasture    9       110.0         150
horse     stable    3       900.0        2000
chicken     coop   34         4.0          10

### 🔄 Combinando DataFrames con `merge()`

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda muestra una operación relacionada con `pd.concat()` o `merge()` para combinar datos en pandas.

📌 **Explicación:** Esta celda muestra una operación de pandas relacionada con la combinación de datos.

In [36]:
teams = pd.DataFrame(
    [
        ["Suns", "Phoenix", 20, 4], 
        ["Mavericks", "Dallas", 11,12], 
        ["Rockets", "Houston", 7, 16],
        ['Nuggets', "Denver", 11, 12]
    ], 
    columns=["team", "city", "wins", "losses"]
)

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda muestra una operación relacionada con `pd.concat()` o `merge()` para combinar datos en pandas.

📌 **Explicación:** Esta celda muestra una operación de pandas relacionada con la combinación de datos.

In [37]:
cities = pd.DataFrame(
    [
        ["Houston", "Texas", 2310000], 
        ["Phoenix", "Arizona", 1630000], 
        ["San Diego", "California", 1410000],
        ["Dallas", "Texas", 1310000]
    ],
    columns=["city", "state", "population"]
)

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda muestra una operación relacionada con `pd.concat()` o `merge()` para combinar datos en pandas.

📌 **Explicación:** Esta celda muestra una operación de pandas relacionada con la combinación de datos.

In [38]:
teams

        team     city  wins  losses
0       Suns  Phoenix    20       4
1  Mavericks   Dallas    11      12
2    Rockets  Houston     7      16
3    Nuggets   Denver    11      12

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda muestra una operación relacionada con `pd.concat()` o `merge()` para combinar datos en pandas.

📌 **Explicación:** Esta celda muestra una operación de pandas relacionada con la combinación de datos.

In [39]:
cities

        city       state  population
0    Houston       Texas     2310000
1    Phoenix     Arizona     1630000
2  San Diego  California     1410000
3     Dallas       Texas     1310000

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda muestra una operación relacionada con `pd.concat()` o `merge()` para combinar datos en pandas.

📌 **Explicación:** Se realiza una combinación entre DataFrames usando la función `merge()`.

In [40]:
teams.merge(cities)

        team     city  wins  losses    state  population
0       Suns  Phoenix    20       4  Arizona     1630000
1  Mavericks   Dallas    11      12    Texas     1310000
2    Rockets  Houston     7      16    Texas     2310000

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda muestra una operación relacionada con `pd.concat()` o `merge()` para combinar datos en pandas.

📌 **Explicación:** Se realiza una combinación entre DataFrames usando la función `merge()`.

In [41]:
teams.merge(cities, on="city")

        team     city  wins  losses    state  population
0       Suns  Phoenix    20       4  Arizona     1630000
1  Mavericks   Dallas    11      12    Texas     1310000
2    Rockets  Houston     7      16    Texas     2310000

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda muestra una operación relacionada con `pd.concat()` o `merge()` para combinar datos en pandas.

📌 **Explicación:** Se realiza una combinación entre DataFrames usando la función `merge()`.

In [42]:
teams.merge(cities, on="city", how="inner")

        team     city  wins  losses    state  population
0       Suns  Phoenix    20       4  Arizona     1630000
1  Mavericks   Dallas    11      12    Texas     1310000
2    Rockets  Houston     7      16    Texas     2310000

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda muestra una operación relacionada con `pd.concat()` o `merge()` para combinar datos en pandas.

📌 **Explicación:** Se realiza una combinación entre DataFrames usando la función `merge()`.

In [43]:
teams.merge(cities, how="left")

        team     city  wins  losses    state  population
0       Suns  Phoenix    20       4  Arizona   1630000.0
1  Mavericks   Dallas    11      12    Texas   1310000.0
2    Rockets  Houston     7      16    Texas   2310000.0
3    Nuggets   Denver    11      12      NaN         NaN

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda muestra una operación relacionada con `pd.concat()` o `merge()` para combinar datos en pandas.

📌 **Explicación:** Se realiza una combinación entre DataFrames usando la función `merge()`.

In [44]:
teams.merge(cities, how="right")

        team       city  wins  losses       state  population
0    Rockets    Houston   7.0    16.0       Texas     2310000
1       Suns    Phoenix  20.0     4.0     Arizona     1630000
2        NaN  San Diego   NaN     NaN  California     1410000
3  Mavericks     Dallas  11.0    12.0       Texas     1310000

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda muestra una operación relacionada con `pd.concat()` o `merge()` para combinar datos en pandas.

📌 **Explicación:** Se realiza una combinación entre DataFrames usando la función `merge()`.

In [45]:
teams.merge(cities, how="outer")

        team       city  wins  losses       state  population
0  Mavericks     Dallas  11.0    12.0       Texas   1310000.0
1    Nuggets     Denver  11.0    12.0         NaN         NaN
2    Rockets    Houston   7.0    16.0       Texas   2310000.0
3       Suns    Phoenix  20.0     4.0     Arizona   1630000.0
4        NaN  San Diego   NaN     NaN  California   1410000.0

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda muestra una operación relacionada con `pd.concat()` o `merge()` para combinar datos en pandas.

📌 **Explicación:** Se realiza una combinación entre DataFrames usando la función `merge()`.

In [46]:
cities.merge(teams, on="city", how="left")

        city       state  population       team  wins  losses
0    Houston       Texas     2310000    Rockets   7.0    16.0
1    Phoenix     Arizona     1630000       Suns  20.0     4.0
2  San Diego  California     1410000        NaN   NaN     NaN
3     Dallas       Texas     1310000  Mavericks  11.0    12.0

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda muestra una operación relacionada con `pd.concat()` o `merge()` para combinar datos en pandas.

📌 **Explicación:** Se realiza una combinación entre DataFrames usando la función `merge()`.

In [47]:
teams.merge(cities, on="city", how="right")

        team       city  wins  losses       state  population
0    Rockets    Houston   7.0    16.0       Texas     2310000
1       Suns    Phoenix  20.0     4.0     Arizona     1630000
2        NaN  San Diego   NaN     NaN  California     1410000
3  Mavericks     Dallas  11.0    12.0       Texas     1310000

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda muestra una operación relacionada con `pd.concat()` o `merge()` para combinar datos en pandas.

📌 **Explicación:** Esta celda muestra una operación de pandas relacionada con la combinación de datos.

In [48]:
midterms = pd.DataFrame(
    [['alex', 'padilla', 92], ['rayna', 'wilson', 83], ['juan', 'gomez', 78], ['angela', 'smith', 66],['stephen', 'yu', 98]], 
    columns=['first', 'last', 'score']
)
finals = pd.DataFrame(
    [['alex','padilla', 97, False], ['rayna', 'wilson', 88, False], ['alex', 'smith', 86, True], ['juan', 'gomez', 71, True], ['stephen', 'yu', 78, False], ['sakura', 'steel', 100, True]], 
    columns=['first', 'last','score', 'extra_credit']
)

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda muestra una operación relacionada con `pd.concat()` o `merge()` para combinar datos en pandas.

📌 **Explicación:** Esta celda muestra una operación de pandas relacionada con la combinación de datos.

In [49]:
midterms

     first     last  score
0     alex  padilla     92
1    rayna   wilson     83
2     juan    gomez     78
3   angela    smith     66
4  stephen       yu     98

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda muestra una operación relacionada con `pd.concat()` o `merge()` para combinar datos en pandas.

📌 **Explicación:** Esta celda muestra una operación de pandas relacionada con la combinación de datos.

In [50]:
finals

     first     last  score  extra_credit
0     alex  padilla     97         False
1    rayna   wilson     88         False
2     alex    smith     86          True
3     juan    gomez     71          True
4  stephen       yu     78         False
5   sakura    steel    100          True

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda muestra una operación relacionada con `pd.concat()` o `merge()` para combinar datos en pandas.

📌 **Explicación:** Se realiza una combinación entre DataFrames usando la función `merge()`.

In [51]:
midterms.merge(finals, on="score")

  first_x last_x  score  first_y last_y  extra_credit
0    juan  gomez     78  stephen     yu         False

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda muestra una operación relacionada con `pd.concat()` o `merge()` para combinar datos en pandas.

📌 **Explicación:** Se realiza una combinación entre DataFrames usando la función `merge()`.

In [52]:
midterms.merge(finals, on="first")

     first   last_x  score_x   last_y  score_y  extra_credit
0     alex  padilla       92  padilla       97         False
1     alex  padilla       92    smith       86          True
2    rayna   wilson       83   wilson       88         False
3     juan    gomez       78    gomez       71          True
4  stephen       yu       98       yu       78         False

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda muestra una operación relacionada con `pd.concat()` o `merge()` para combinar datos en pandas.

📌 **Explicación:** Se realiza una combinación entre DataFrames usando la función `merge()`.

In [53]:
midterms.merge(finals, on=["first", "last"], how="inner")

     first     last  score_x  score_y  extra_credit
0     alex  padilla       92       97         False
1    rayna   wilson       83       88         False
2     juan    gomez       78       71          True
3  stephen       yu       98       78         False

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda muestra una operación relacionada con `pd.concat()` o `merge()` para combinar datos en pandas.

📌 **Explicación:** Se realiza una combinación entre DataFrames usando la función `merge()`.

In [54]:
midterms.merge(finals, on=["first", "last"], how="inner", suffixes=("_midterms", "_finals"))

     first     last  score_midterms  score_finals  extra_credit
0     alex  padilla              92            97         False
1    rayna   wilson              83            88         False
2     juan    gomez              78            71          True
3  stephen       yu              98            78         False

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda muestra una operación relacionada con `pd.concat()` o `merge()` para combinar datos en pandas.

📌 **Explicación:** Se realiza una combinación entre DataFrames usando la función `merge()`.

In [55]:
combo = midterms.merge(finals, on=["first", "last"], how="inner", suffixes=("_m", "_f"))

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda muestra una operación relacionada con `pd.concat()` o `merge()` para combinar datos en pandas.

📌 **Explicación:** Esta celda muestra una operación de pandas relacionada con la combinación de datos.

In [56]:
combo["avg"] = (combo["score_m"] + combo["score_f"])/2

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda muestra una operación relacionada con `pd.concat()` o `merge()` para combinar datos en pandas.

📌 **Explicación:** Esta celda muestra una operación de pandas relacionada con la combinación de datos.

In [57]:
combo

     first     last  score_m  score_f  extra_credit   avg
0     alex  padilla       92       97         False  94.5
1    rayna   wilson       83       88         False  85.5
2     juan    gomez       78       71          True  74.5
3  stephen       yu       98       78         False  88.0

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda muestra una operación relacionada con `pd.concat()` o `merge()` para combinar datos en pandas.

📌 **Explicación:** Esta celda muestra una operación de pandas relacionada con la combinación de datos.

In [58]:
combo.loc[combo["extra_credit"] == True, 'avg'] += 5

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda muestra una operación relacionada con `pd.concat()` o `merge()` para combinar datos en pandas.

📌 **Explicación:** Esta celda muestra una operación de pandas relacionada con la combinación de datos.

In [59]:
combo

     first     last  score_m  score_f  extra_credit   avg
0     alex  padilla       92       97         False  94.5
1    rayna   wilson       83       88         False  85.5
2     juan    gomez       78       71          True  79.5
3  stephen       yu       98       78         False  88.0

## UFOS + State Pops Example

![Screen%20Shot%202021-12-08%20at%206.40.43%20PM.png](attachment:Screen%20Shot%202021-12-08%20at%206.40.43%20PM.png)

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda muestra una operación relacionada con `pd.concat()` o `merge()` para combinar datos en pandas.

📌 **Explicación:** Esta celda muestra una operación de pandas relacionada con la combinación de datos.

In [60]:
ufos = pd.read_csv("data/nuforc_reports.csv", parse_dates=["date_time"])

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda muestra una operación relacionada con `pd.concat()` o `merge()` para combinar datos en pandas.

📌 **Explicación:** Esta celda muestra una operación de pandas relacionada con la combinación de datos.

In [61]:
ufos

,summary,city,state,date_time,shape,duration,stats,report_link,text,posted,city_latitude,city_longitude
0,My wife was driving southeast on a fairly popu...,Chester,VA,2019-12-12 18:43:00,light,5 seconds,Occurred : 12/12/2019 18:43 (Entered as : 12/...,http://www.nuforc.org/webreports/151/S151739.html,My wife was driving southeast on a fairly popu...,2019-12-22T00:00:00,37.343152,-77.408582
1,I think that I may caught a UFO on the NBC Nig...,Rocky Hill,CT,2019-03-22 18:30:00,circle,3-5 seconds,Occurred : 3/22/2019 18:30 (Entered as : 03/2...,http://www.nuforc.org/webreports/145/S145297.html,I think that I may caught a UFO on the NBC Nig...,2019-03-29T00:00:00,41.664800,-72.639300
2,I woke up late in the afternoon 3:30-4pm. I we...,NaN,NaN,NaT,NaN,NaN,Occurred : 4/1/2019 15:45 (Entered as : April...,http://www.nuforc.org/webreports/145/S145556.html,I woke up late in the afternoon 3:30-4pm. I w...,NaN,NaN,NaN
3,I was driving towards the intersection of fall...,Ottawa,ON,2019-04-17 02:00:00,teardrop,10 seconds,Occurred : 4/17/2019 02:00 (Entered as : 04-1...,http://www.nuforc.org/webreports/145/S145697.html,I was driving towards the intersection of fall...,2019-04-18T00:00:00,45.381383,-75.708501
4,"In Peoria Arizona, I saw a cigar shaped craft ...",Peoria,NY,2009-03-15 18:00:00,cigar,2 minutes,Occurred : 3/15/2009 18:00 (Entered as : 03/1...,http://www.nuforc.org/webreports/145/S145723.html,"In Peoria, Arizona, I saw a cigar shaped craft...",2019-04-18T00:00:00,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
88120,4 lights in formation over Tempe appear while ...,Tempe,AZ,2019-10-02 20:00:00,formation,3 minutes,Occurred : 10/2/2019 20:00 (Entered as : 10/2...,http://www.nuforc.org/webreports/149/S149463.html,4 lights in formation over Tempe appear while ...,2019-10-04T00:00:00,33.414036,-111.920920
88121,"2 bright star like lights in the NNW skys, ((...",Bolivar,MO,2019-10-02 20:00:00,light,20 seconds,Occurred : 10/2/2019 20:00 (Entered as : 10/0...,http://www.nuforc.org/webreports/149/S149405.html,2 bright star like lights in the NNW sky two b...,2019-10-04T00:00:00,37.642200,-93.399600
88122,I just witnessed a ‘Phoenix Lights’ type of fo...,North Port,FL,2019-10-02 20:03:00,formation,20 seconds,Occurred : 10/2/2019 20:03 (Entered as : 10/0...,http://www.nuforc.org/webreports/149/S149424.html,10/2/19 @ 8:03PM EST UFO SIGHTING in the 3428...,2019-10-04T00:00:00,27.076210,-82.223280
88123,"Witnessed an orange, slow moving light. Was lo...",Black Mountain,NC,2019-10-02 22:00:00,fireball,2 minutes,Occurred : 10/2/2019 22:00 (Entered as : 10/0...,http://www.nuforc.org/webreports/149/S149447.html,"Witnessed an orange, slow moving light. Was lo...",2019-10-04T00:00:00,35.605000,-82.313200
88124,Glowing lights in formation just south of San...,Marin County,CA,2019-10-02 22:00:00,sphere,3 minutes,Occurred : 10/2/2019 22:00 (Entered as : 10-0...,http://www.nuforc.org/webreports/149/S149436.html,Glowing lights in formation just south of San...,2019-10-04T00:00:00,NaN,NaN

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda muestra una operación relacionada con `pd.concat()` o `merge()` para combinar datos en pandas.

📌 **Explicación:** Esta celda muestra una operación de pandas relacionada con la combinación de datos.

In [62]:
ufos_19 = ufos[ufos["date_time"].dt.year == 2019]

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda muestra una operación relacionada con `pd.concat()` o `merge()` para combinar datos en pandas.

📌 **Explicación:** Esta celda muestra una operación de pandas relacionada con la combinación de datos.

In [63]:
ufos_19

,summary,city,state,date_time,shape,duration,stats,report_link,text,posted,city_latitude,city_longitude
0,My wife was driving southeast on a fairly popu...,Chester,VA,2019-12-12 18:43:00,light,5 seconds,Occurred : 12/12/2019 18:43 (Entered as : 12/...,http://www.nuforc.org/webreports/151/S151739.html,My wife was driving southeast on a fairly popu...,2019-12-22T00:00:00,37.343152,-77.408582
1,I think that I may caught a UFO on the NBC Nig...,Rocky Hill,CT,2019-03-22 18:30:00,circle,3-5 seconds,Occurred : 3/22/2019 18:30 (Entered as : 03/2...,http://www.nuforc.org/webreports/145/S145297.html,I think that I may caught a UFO on the NBC Nig...,2019-03-29T00:00:00,41.664800,-72.639300
3,I was driving towards the intersection of fall...,Ottawa,ON,2019-04-17 02:00:00,teardrop,10 seconds,Occurred : 4/17/2019 02:00 (Entered as : 04-1...,http://www.nuforc.org/webreports/145/S145697.html,I was driving towards the intersection of fall...,2019-04-18T00:00:00,45.381383,-75.708501
5,"The object has flashing lights that are green,...",Kirbyville,TX,2019-04-02 20:25:00,disk,15 minutes,Occurred : 4/2/2019 20:25 (Entered as : 04/02...,http://www.nuforc.org/webreports/145/S145476.html,"The object has flashing lights that are green,...",2019-04-08T00:00:00,30.677200,-94.005200
6,Description is the same as Washington DC event...,Tucson,AZ,2019-05-01 11:00:00,unknown,5 minutes,Occurred : 5/1/2019 11:00 (Entered as : 5/1/1...,http://www.nuforc.org/webreports/145/S145947.html,"Description is the same as Washington, DC, eve...",2019-05-09T00:00:00,32.259941,-110.927542
...,...,...,...,...,...,...,...,...,...,...,...,...
88120,4 lights in formation over Tempe appear while ...,Tempe,AZ,2019-10-02 20:00:00,formation,3 minutes,Occurred : 10/2/2019 20:00 (Entered as : 10/2...,http://www.nuforc.org/webreports/149/S149463.html,4 lights in formation over Tempe appear while ...,2019-10-04T00:00:00,33.414036,-111.920920
88121,"2 bright star like lights in the NNW skys, ((...",Bolivar,MO,2019-10-02 20:00:00,light,20 seconds,Occurred : 10/2/2019 20:00 (Entered as : 10/0...,http://www.nuforc.org/webreports/149/S149405.html,2 bright star like lights in the NNW sky two b...,2019-10-04T00:00:00,37.642200,-93.399600
88122,I just witnessed a ‘Phoenix Lights’ type of fo...,North Port,FL,2019-10-02 20:03:00,formation,20 seconds,Occurred : 10/2/2019 20:03 (Entered as : 10/0...,http://www.nuforc.org/webreports/149/S149424.html,10/2/19 @ 8:03PM EST UFO SIGHTING in the 3428...,2019-10-04T00:00:00,27.076210,-82.223280
88123,"Witnessed an orange, slow moving light. Was lo...",Black Mountain,NC,2019-10-02 22:00:00,fireball,2 minutes,Occurred : 10/2/2019 22:00 (Entered as : 10/0...,http://www.nuforc.org/webreports/149/S149447.html,"Witnessed an orange, slow moving light. Was lo...",2019-10-04T00:00:00,35.605000,-82.313200
88124,Glowing lights in formation just south of San...,Marin County,CA,2019-10-02 22:00:00,sphere,3 minutes,Occurred : 10/2/2019 22:00 (Entered as : 10-0...,http://www.nuforc.org/webreports/149/S149436.html,Glowing lights in formation just south of San...,2019-10-04T00:00:00,NaN,NaN

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda muestra una operación relacionada con `pd.concat()` o `merge()` para combinar datos en pandas.

📌 **Explicación:** Esta celda muestra una operación de pandas relacionada con la combinación de datos.

In [64]:
state_pops = pd.read_csv('data/nst-est2020.csv')

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda muestra una operación relacionada con `pd.concat()` o `merge()` para combinar datos en pandas.

📌 **Explicación:** Esta celda muestra una operación de pandas relacionada con la combinación de datos.

In [65]:
state_pops = state_pops[["NAME", "POPESTIMATE2019"]]
state_pops

                    NAME  POPESTIMATE2019
0          United States        328329953
1       Northeast Region         56002934
2         Midwest Region         68340091
3           South Region        125686544
4            West Region         78300384
5                Alabama          4907965
6                 Alaska           733603
7                Arizona          7291843
8               Arkansas          3020985
9             California         39437610
10              Colorado          5758486
11           Connecticut          3566022
12              Delaware           976668
13  District of Columbia           708253
14               Florida         21492056
15               Georgia         10628020
16                Hawaii          1415615
17                 Idaho          1789060
18              Illinois         12667017
19               Indiana          6731010
20                  Iowa          3159596
21                Kansas          2912635
22              Kentucky          4472345
23             Louisiana          4658285
24                 Maine          1345770
25              Maryland          6054954
26         Massachusetts          6894883
27              Michigan          9984795
28             Minnesota          5640053
29           Mississippi          2978227
30              Missouri          6140475
31               Montana          1070123
32              Nebraska          1932571
33                Nevada          3090771
34         New Hampshire          1360783
35            New Jersey          8891258
36            New Mexico          2099634
37              New York         19463131
38        North Carolina         10501384
39          North Dakota           763724
40                  Ohio         11696507
41              Oklahoma          3960676
42                Oregon          4216116
43          Pennsylvania         12798883
44          Rhode Island          1058158
45        South Carolina          5157702
46          South Dakota           887127
47             Tennessee          6830325
48                 Texas         28986794
49                  Utah          3203383
50               Vermont           624046
51              Virginia          8556642
52            Washington          7614024
53         West Virginia          1795263
54             Wisconsin          5824581
55               Wyoming           580116
56           Puerto Rico          3193553

📌 **Explicación:** Esta celda muestra una operación de pandas relacionada con la combinación de datos.

In [66]:
state_names = pd.read_csv("data/states.csv")
state_names

                  Estado Abreviatura Codigo
0                Alabama        Ala.     AL
1                 Alaska      Alaska     AK
2                Arizona       Ariz.     AZ
3               Arkansas        Ark.     AR
4             California      Calif.     CA
5               Colorado       Colo.     CO
6            Connecticut       Conn.     CT
7               Delaware        Del.     DE
8   District of Columbia        D.C.     DC
9                Florida        Fla.     FL
10               Georgia         Ga.     GA
11                Hawaii      Hawaii     HI
12                 Idaho       Idaho     ID
13              Illinois        Ill.     IL
14               Indiana        Ind.     IN
15                  Iowa        Iowa     IA
16                Kansas       Kans.     KS
17              Kentucky         Ky.     KY
18             Louisiana         La.     LA
19                 Maine       Maine     ME
20              Maryland         Md.     MD
21         Massachusetts       Mass.     MA
22              Michigan       Mich.     MI
23             Minnesota       Minn.     MN
24           Mississippi       Miss.     MS
25              Missouri         Mo.     MO
26               Montana       Mont.     MT
27              Nebraska       Nebr.     NE
28                Nevada        Nev.     NV
29         New Hampshire        N.H.     NH
30            New Jersey        N.J.     NJ
31            New Mexico        N.M.     NM
32              New York        N.Y.     NY
33        North Carolina        N.C.     NC
34          North Dakota        N.D.     ND
35                  Ohio        Ohio     OH
36              Oklahoma       Okla.     OK
37                Oregon        Ore.     OR
38          Pennsylvania         Pa.     PA
39          Rhode Island        R.I.     RI
40        South Carolina        S.C.     SC
41          South Dakota        S.D.     SD
42             Tennessee       Tenn.     TN
43                 Texas        Tex.     TX
44                  Utah        Utah     UT
45               Vermont         Vt.     VT
46              Virginia         Va.     VA
47            Washington       Wash.     WA
48         West Virginia       W.Va.     WV
49             Wisconsin        Wis.     WI
50               Wyoming        Wyo.     WY

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda muestra una operación relacionada con `pd.concat()` o `merge()` para combinar datos en pandas.

📌 **Explicación:** Se realiza una combinación entre DataFrames usando la función `merge()`.

In [67]:
state_pops_with_code = state_pops.merge(state_names, left_on="NAME", right_on="State")

KeyError: 'State'

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda muestra una operación relacionada con `pd.concat()` o `merge()` para combinar datos en pandas.

📌 **Explicación:** Esta celda muestra una operación de pandas relacionada con la combinación de datos.

In [68]:
state_pops_2019 = state_pops_with_code.set_index("Code")["POPESTIMATE2019"]

NameError: name 'state_pops_with_code' is not defined

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda muestra una operación relacionada con `pd.concat()` o `merge()` para combinar datos en pandas.

📌 **Explicación:** Esta celda muestra una operación de pandas relacionada con la combinación de datos.

In [ ]:
state_pops_2019

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda muestra una operación relacionada con `pd.concat()` o `merge()` para combinar datos en pandas.

📌 **Explicación:** Esta celda muestra una operación de pandas relacionada con la combinación de datos.

In [ ]:
ufos_19 = ufos_19.state.value_counts()

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda muestra una operación relacionada con `pd.concat()` o `merge()` para combinar datos en pandas.

📌 **Explicación:** Se combinan Series o DataFrames, conservando los índices originales.

In [ ]:
df = pd.concat([ufos_19, state_pops_2019], axis=1).rename({"state": "num_sightings", "POPESTIMATE2019": "population"}, axis=1)

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda muestra una operación relacionada con `pd.concat()` o `merge()` para combinar datos en pandas.

📌 **Explicación:** Esta celda muestra una operación de pandas relacionada con la combinación de datos.

In [ ]:
df

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda muestra una operación relacionada con `pd.concat()` o `merge()` para combinar datos en pandas.

📌 **Explicación:** Esta celda muestra una operación de pandas relacionada con la combinación de datos.

In [ ]:
df["ufos_per_cap"] = df["num_sightings"] / df["population"]

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda muestra una operación relacionada con `pd.concat()` o `merge()` para combinar datos en pandas.

📌 **Explicación:** Esta celda muestra una operación de pandas relacionada con la combinación de datos.

In [ ]:
df.sort_values("ufos_per_cap", ascending=False).head(10)

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda muestra una operación relacionada con `pd.concat()` o `merge()` para combinar datos en pandas.

📌 **Explicación:** Esta celda muestra una operación de pandas relacionada con la combinación de datos.

In [ ]:
import matplotlib.pyplot as plt
df["ufos_per_cap"].sort_values(ascending=False).head(10).plot(kind="barh")
plt.title("UFO Sightings Per Capita")

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda muestra una operación relacionada con `pd.concat()` o `merge()` para combinar datos en pandas.

📌 **Explicación:** Se combinan Series o DataFrames, conservando los índices originales.

In [ ]:
d = pd.concat([ufos.state.value_counts(), state_pops_2019], axis=1)

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda muestra una operación relacionada con `pd.concat()` o `merge()` para combinar datos en pandas.

📌 **Explicación:** Esta celda muestra una operación de pandas relacionada con la combinación de datos.

In [ ]:
d["cap"] = d["state"] / d['POPESTIMATE2019']

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda muestra una operación relacionada con `pd.concat()` o `merge()` para combinar datos en pandas.

📌 **Explicación:** Esta celda muestra una operación de pandas relacionada con la combinación de datos.

In [ ]:
d.cap.sort_values(ascending=False).head(10).plot(kind="barh")

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda realiza una operación relacionada con la combinación de DataFrames o Series. Observa cómo se utiliza la función correspondiente de pandas.

📌 **Explicación:** Esta celda muestra una operación relacionada con `pd.concat()` o `merge()` para combinar datos en pandas.

📌 **Explicación:** Esta celda muestra una operación de pandas relacionada con la combinación de datos.

In [ ]:
ufos.state.value_counts().head(10).plot(kind="barh")