In [1]:
import pandas as pd

In [2]:
votantes = pd.read_csv("../data/votantes_13660_edades.csv")
votantes.head()

   id_votante  genero  edad    voto
0           1   Mujer    80   Obama
1           2  Hombre    50  McCain
2           3   Mujer    37   Obama
3           4   Mujer    50  McCain
4           5   Mujer    80  McCain

In [4]:
# Definir los límites de los rangos
limites = [17, 29, 44, 64, float("inf")]

# Etiquetas de los rangos
etiquetas = [
    "18 a 29",
    "30 a 44",
    "45 a 64",
    "65 y más"
]

# Crear la nueva columna
votantes["rango_edad"] = pd.cut(
    votantes["edad"],
    bins=limites,
    labels=etiquetas
)

In [5]:
votantes.head()

   id_votante  genero  edad    voto rango_edad
0           1   Mujer    80   Obama   65 y más
1           2  Hombre    50  McCain    45 a 64
2           3   Mujer    37   Obama    30 a 44
3           4   Mujer    50  McCain    45 a 64
4           5   Mujer    80  McCain   65 y más

In [6]:
tabla_edades = votantes["rango_edad"].value_counts().sort_index()
print(tabla_edades)

rango_edad
18 a 29     1912
30 a 44     3688
45 a 64     5328
65 y más    2732
Name: count, dtype: int64

In [11]:
tabla_edad_voto = pd.crosstab(
    votantes["rango_edad"],
    votantes["voto"],
    margins=True,
    margins_name="Total"
)
print(tabla_edad_voto)

voto        McCain  Obama  Otros  Total
rango_edad
18 a 29        832   1064     16   1912
30 a 44       1932   1720     36   3688
45 a 64       2590   2667     71   5328
65 y más      1372   1360      0   2732
Total         6726   6811    123  13660

In [43]:
print(tabla_edad_voto.loc["65 y más", "Obama"] )
print(tabla_edad_voto.loc["65 y más", "Total"])

# prob_18_29_mcCain = (tabla_edad_voto.loc["18 a 29", "McCain"] / tabla_edad_voto.loc["18 a 29", "Total"])
# prob_30_44_mcCain = (tabla_edad_voto.loc["30 a 44", "McCain"] / tabla_edad_voto.loc["30 a 44", "Total"])
# prob_45_64_mcCain = (tabla_edad_voto.loc["45 a 64", "McCain"] / tabla_edad_voto.loc["45 a 64", "Total"])
# prob_65_mas_mcCain = (tabla_edad_voto.loc["65 y más", "McCain"] / tabla_edad_voto.loc["65 y más", "Total"])

# print("18 a 29 mcCain:",(prob_18_29_mcCain * 100).round(0))
# print((prob_30_44_mcCain * 100).round(0))
# print((prob_45_64_mcCain * 100).round(0))
# print((prob_65_mas_mcCain * 100).round(0))

1360
2732

In [33]:
prob_18_29 = (tabla_edad_voto.loc["18 a 29", "Total"] / tabla_edad_voto.loc["Total", "Total"])
prob_30_44 = (tabla_edad_voto.loc["30 a 44", "Total"] / tabla_edad_voto.loc["Total", "Total"])
prob_45_64 = (tabla_edad_voto.loc["45 a 64", "Total"] / tabla_edad_voto.loc["Total", "Total"])
prob_65_mas = (tabla_edad_voto.loc["65 y más", "Total"] / tabla_edad_voto.loc["Total", "Total"])

print("18 a 29:", (prob_18_29 * 100).round(0), "%")
print("30 a 44:", (prob_30_44 * 100).round(0), "%")
print("45 a 64:", (prob_45_64 * 100).round(0), "%")
print("65 y más:", (prob_65_mas * 100).round(0), "%")

18 a 29: 14.0 %
30 a 44: 27.0 %
45 a 64: 39.0 %
65 y más: 20.0 %

In [20]:
tabla_genero_voto = pd.crosstab(
    votantes["genero"],
    votantes["voto"],
    margins=True,
    margins_name="Total"
)
print(tabla_genero_voto)

voto    McCain  Obama  Otros  Total
genero
Hombre    3369   3122     66   6557
Mujer     3357   3689     57   7103
Total     6726   6811    123  13660

In [22]:
prob_mujer_mcCain = (tabla_genero_voto.loc["Mujer", "McCain"] / tabla_genero_voto.loc["Mujer", "Total"])
print((prob_mujer_mcCain * 100).round(0))

47.0

In [23]:
prob_hombre_mcCain = (tabla_genero_voto.loc["Hombre", "McCain"] / tabla_genero_voto.loc["Hombre", "Total"])
print((prob_hombre_mcCain * 100).round(0))

51.0

In [24]:
prob_hombre = (tabla_genero_voto.loc["Hombre"] / tabla_genero_voto.loc["Total"])
print((prob_hombre * 100).round(0))

voto
McCain    50.0
Obama     46.0
Otros     54.0
Total     48.0
dtype: float64

In [34]:
prob_hombre = (
    tabla_genero_voto.loc["Hombre", "Total"] /
    tabla_genero_voto.loc["Total", "Total"]
)

prob_mujer = (
    tabla_genero_voto.loc["Mujer", "Total"] /
    tabla_genero_voto.loc["Total", "Total"]
)



print("Hombre:", (prob_hombre * 100).round(0), "%")
print("Mujer:", (prob_mujer * 100).round(0), "%")

print("Suma:", prob_hombre + prob_mujer)

Hombre: 48.0 %
Mujer: 52.0 %
Suma: 1.0

18 a 29: 14.0 %
30 a 44: 27.0 %
45 a 64: 39.0 %
65 y más: 20.0 %